// Generated by d2w fhir generate - do not edit

// The QR -> DHIS2 aggregate conversion as a published StructureMap. The map is a contract, not an
// engine: nothing in this project executes it, and the rules whose meaning a transform cannot state
// carry that on their own `documentation`. The resource is authored directly in FSH because SUSHI
// compiles no FHIR Mapping Language - a `.fml` file is ignored wherever it is placed - and the
// contract a consumer reads is the StructureMap resource either way.
Instance: D2AggregateResponseToDataValueSet
InstanceOf: StructureMap
Title: "DHIS2 aggregate response to data value set"
Description: "How one aggregate QuestionnaireResponse becomes the DHIS2 data value set it is imported as, element by element. The map is the conversion contract a third party builds their own bridge from; it is not executed at runtime, and the rules whose meaning exceeds what a transform can state carry that on their own documentation."
Usage: #definition
* id = "d2-aggregate-response-to-data-value-set"
* name = "D2AggregateResponseToDataValueSet"
* status = #draft
* experimental = true
* structure[0].url = "http://hl7.org/fhir/StructureDefinition/QuestionnaireResponse"
* structure[0].mode = #source
* structure[0].alias = "QuestionnaireResponse"
* structure[1].url = Canonical(D2DataValueSet)
* structure[1].mode = #target
* structure[1].alias = "DataValueSet"

// The envelope: the four keys DHIS2 stores a data value under, the completeness date, and the
// hand-off to the group that walks the answered items.
* group[0].name = "AggregateResponseToDataValueSet"
* group[0].typeMode = #none
* group[0].documentation = "One aggregate QuestionnaireResponse becomes one data value set."
* group[0].input[0].name = "response"
* group[0].input[0].type = "QuestionnaireResponse"
* group[0].input[0].mode = #source
* group[0].input[1].name = "dataValueSet"
* group[0].input[1].type = "DataValueSet"
* group[0].input[1].mode = #target

* group[0].rule[0].name = "dataSet"
* group[0].rule[0].documentation = "The data set is a fact about the form rather than about the response: it is the http://dhis2.org/fhir/id/data-set identifier of the Questionnaire the response answers, so an engine executing this map needs that Questionnaire in scope."
* group[0].rule[0].source[0].context = "response"
* group[0].rule[0].source[0].element = "questionnaire"
* group[0].rule[0].source[0].variable = "questionnaire"
* group[0].rule[0].target[0].context = "dataValueSet"
* group[0].rule[0].target[0].contextType = #variable
* group[0].rule[0].target[0].element = "dataSet"
* group[0].rule[0].target[0].transform = #evaluate
* group[0].rule[0].target[0].parameter[0].valueString = "%questionnaire.resolve().identifier.where($this.system = 'http://dhis2.org/fhir/id/data-set').value"

* group[0].rule[1].name = "period"
* group[0].rule[1].documentation = "The DHIS2 ISO period is what the import is keyed by. The date range the same extension carries is a rendering of that period, and a range disagreeing with the ISO period is ignored rather than obeyed."
* group[0].rule[1].source[0].context = "response"
* group[0].rule[1].source[0].element = "extension"
* group[0].rule[1].source[0].variable = "reportingPeriod"
* group[0].rule[1].source[0].condition = "url = 'http://example.org/fhir/examples/aggregate-minimal/StructureDefinition/d2-period'"
* group[0].rule[1].rule[0].name = "periodIsoExtension"
* group[0].rule[1].rule[0].source[0].context = "reportingPeriod"
* group[0].rule[1].rule[0].source[0].element = "extension"
* group[0].rule[1].rule[0].source[0].variable = "isoExtension"
* group[0].rule[1].rule[0].source[0].condition = "url = 'iso'"
* group[0].rule[1].rule[0].rule[0].name = "periodIso"
* group[0].rule[1].rule[0].rule[0].source[0].context = "isoExtension"
* group[0].rule[1].rule[0].rule[0].source[0].element = "value"
* group[0].rule[1].rule[0].rule[0].source[0].variable = "iso"
* group[0].rule[1].rule[0].rule[0].target[0].context = "dataValueSet"
* group[0].rule[1].rule[0].rule[0].target[0].contextType = #variable
* group[0].rule[1].rule[0].rule[0].target[0].element = "period"
* group[0].rule[1].rule[0].rule[0].target[0].transform = #copy
* group[0].rule[1].rule[0].rule[0].target[0].parameter[0].valueId = "iso"

* group[0].rule[2].name = "orgUnit"
* group[0].rule[2].documentation = "The organisation unit is the http://dhis2.org/fhir/id/org-unit identifier of the published Location the response is subject to, so an engine executing this map needs the Location registry in scope. Reading the UID off the reference's own id is only correct where the guide names its Locations by DHIS2 id."
* group[0].rule[2].source[0].context = "response"
* group[0].rule[2].source[0].element = "subject"
* group[0].rule[2].source[0].variable = "subject"
* group[0].rule[2].target[0].context = "dataValueSet"
* group[0].rule[2].target[0].contextType = #variable
* group[0].rule[2].target[0].element = "orgUnit"
* group[0].rule[2].target[0].transform = #evaluate
* group[0].rule[2].target[0].parameter[0].valueString = "%subject.resolve().identifier.where($this.system = 'http://dhis2.org/fhir/id/org-unit').value"

* group[0].rule[3].name = "attributeOptionCombo"
* group[0].rule[3].documentation = "The response names its attribute option combo as a coding of the vocabulary its own form declares. The code is the DHIS2 UID wherever the guide's concept codes are DHIS2 ids; where they are DHIS2 codes, the combo's own ConceptMap translates the code onto http://dhis2.org/fhir/id/category-option-combo and this rule is that translation's input. A data set on the default category combo names no combo at all, and DHIS2 fills the field itself."
* group[0].rule[3].source[0].context = "response"
* group[0].rule[3].source[0].element = "extension"
* group[0].rule[3].source[0].variable = "attributeOptionComboExtension"
* group[0].rule[3].source[0].condition = "url = 'http://example.org/fhir/examples/aggregate-minimal/StructureDefinition/d2-attribute-option-combo'"
* group[0].rule[3].rule[0].name = "attributeOptionComboCoding"
* group[0].rule[3].rule[0].source[0].context = "attributeOptionComboExtension"
* group[0].rule[3].rule[0].source[0].element = "value"
* group[0].rule[3].rule[0].source[0].variable = "coding"
* group[0].rule[3].rule[0].rule[0].name = "attributeOptionComboCode"
* group[0].rule[3].rule[0].rule[0].source[0].context = "coding"
* group[0].rule[3].rule[0].rule[0].source[0].element = "code"
* group[0].rule[3].rule[0].rule[0].source[0].variable = "comboCode"
* group[0].rule[3].rule[0].rule[0].target[0].context = "dataValueSet"
* group[0].rule[3].rule[0].rule[0].target[0].contextType = #variable
* group[0].rule[3].rule[0].rule[0].target[0].element = "attributeOptionCombo"
* group[0].rule[3].rule[0].rule[0].target[0].transform = #copy
* group[0].rule[3].rule[0].rule[0].target[0].parameter[0].valueId = "comboCode"

* group[0].rule[4].name = "completeDate"
* group[0].rule[4].documentation = "The report is complete on the day the response records itself as authored. `authored` carries an offset and DHIS2 stores a zone-less wall clock, so a bridge reads the instant in the project's own time zone before taking its date part; the substring below is the structural claim, not the zone arithmetic."
* group[0].rule[4].source[0].context = "response"
* group[0].rule[4].source[0].element = "authored"
* group[0].rule[4].source[0].variable = "authored"
* group[0].rule[4].target[0].context = "dataValueSet"
* group[0].rule[4].target[0].contextType = #variable
* group[0].rule[4].target[0].element = "completeDate"
* group[0].rule[4].target[0].transform = #evaluate
* group[0].rule[4].target[0].parameter[0].valueString = "%authored.toString().substring(0, 10)"

* group[0].rule[5].name = "dataValues"
* group[0].rule[5].source[0].context = "response"
* group[0].rule[5].source[0].element = "item"
* group[0].rule[5].source[0].variable = "item"
* group[0].rule[5].dependent[0].name = "ResponseItemToDataValues"
* group[0].rule[5].dependent[0].variable[0] = "item"
* group[0].rule[5].dependent[0].variable[1] = "dataValueSet"

// The cells: one data value per answered question, wherever the question sits in the item tree.
* group[1].name = "ResponseItemToDataValues"
* group[1].typeMode = #none
* group[1].documentation = "One answered item becomes one data value. A form's questions sit under section groups and a group carries no data value of its own, so the group recurses into its children and writes only where an answer is."
* group[1].input[0].name = "item"
* group[1].input[0].mode = #source
* group[1].input[1].name = "dataValueSet"
* group[1].input[1].type = "DataValueSet"
* group[1].input[1].mode = #target

* group[1].rule[0].name = "nestedItem"
* group[1].rule[0].source[0].context = "item"
* group[1].rule[0].source[0].element = "item"
* group[1].rule[0].source[0].variable = "childItem"
* group[1].rule[0].dependent[0].name = "ResponseItemToDataValues"
* group[1].rule[0].dependent[0].variable[0] = "childItem"
* group[1].rule[0].dependent[0].variable[1] = "dataValueSet"

* group[1].rule[1].name = "answeredItem"
* group[1].rule[1].source[0].context = "item"
* group[1].rule[1].source[0].element = "answer"
* group[1].rule[1].source[0].variable = "answer"
* group[1].rule[1].target[0].context = "dataValueSet"
* group[1].rule[1].target[0].contextType = #variable
* group[1].rule[1].target[0].element = "dataValues"
* group[1].rule[1].target[0].variable = "dataValue"
* group[1].rule[1].target[0].transform = #create

* group[1].rule[1].rule[0].name = "dataElement"
* group[1].rule[1].rule[0].documentation = "The link-id grammar is the whole disaggregation contract: an undisaggregated question is answered on the data element UID alone, and one cell of a category grid on the data element UID, a dot, and the category option combo UID."
* group[1].rule[1].rule[0].source[0].context = "item"
* group[1].rule[1].rule[0].source[0].element = "linkId"
* group[1].rule[1].rule[0].source[0].variable = "linkId"
* group[1].rule[1].rule[0].target[0].context = "dataValue"
* group[1].rule[1].rule[0].target[0].contextType = #variable
* group[1].rule[1].rule[0].target[0].element = "dataElement"
* group[1].rule[1].rule[0].target[0].transform = #evaluate
* group[1].rule[1].rule[0].target[0].parameter[0].valueString = "%linkId.substring(0, %linkId.iif(%linkId.contains('.'), %linkId.indexOf('.'), %linkId.length()))"

* group[1].rule[1].rule[1].name = "categoryOptionCombo"
* group[1].rule[1].rule[1].source[0].context = "item"
* group[1].rule[1].rule[1].source[0].element = "linkId"
* group[1].rule[1].rule[1].source[0].variable = "linkId"
* group[1].rule[1].rule[1].target[0].context = "dataValue"
* group[1].rule[1].rule[1].target[0].contextType = #variable
* group[1].rule[1].rule[1].target[0].element = "categoryOptionCombo"
* group[1].rule[1].rule[1].target[0].transform = #evaluate
* group[1].rule[1].rule[1].target[0].parameter[0].valueString = "%linkId.iif(%linkId.contains('.'), %linkId.substring(%linkId.indexOf('.') + 1), {})"

* group[1].rule[1].rule[2].name = "booleanValue"
* group[1].rule[1].rule[2].documentation = "Every DHIS2 data value is a string on the wire, and one rule per answered `value[x]` type is what states that string: the validator types an evaluate expression against the element it reads, so a branch naming its own type is the form an expression over a choice can take. What no transform can state stays in prose: a TRUE_ONLY question answered false drops the whole cell, a MULTI_TEXT answer is the comma-joined set of its codes, a decimal keeps the lexical form it was captured in, a coded answer is resolved through the question's own terminology, and a zoned timestamp is read to the wall clock DHIS2 stores. `dhis2w_fhir.conversion.values` is the reference implementation of that table. An attachment answers no data value at all - DHIS2 stores a file resource through a separate upload - so no branch reads one."
* group[1].rule[1].rule[2].source[0].context = "answer"
* group[1].rule[1].rule[2].source[0].element = "value"
* group[1].rule[1].rule[2].source[0].type = "boolean"
* group[1].rule[1].rule[2].source[0].variable = "answerBoolean"
* group[1].rule[1].rule[2].target[0].context = "dataValue"
* group[1].rule[1].rule[2].target[0].contextType = #variable
* group[1].rule[1].rule[2].target[0].element = "value"
* group[1].rule[1].rule[2].target[0].transform = #evaluate
* group[1].rule[1].rule[2].target[0].parameter[0].valueString = "%answerBoolean.toString()"

* group[1].rule[1].rule[3].name = "decimalValue"
* group[1].rule[1].rule[3].documentation = "A decimal keeps the lexical form the answer was captured in, so a whole number stays whole."
* group[1].rule[1].rule[3].source[0].context = "answer"
* group[1].rule[1].rule[3].source[0].element = "value"
* group[1].rule[1].rule[3].source[0].type = "decimal"
* group[1].rule[1].rule[3].source[0].variable = "answerDecimal"
* group[1].rule[1].rule[3].target[0].context = "dataValue"
* group[1].rule[1].rule[3].target[0].contextType = #variable
* group[1].rule[1].rule[3].target[0].element = "value"
* group[1].rule[1].rule[3].target[0].transform = #evaluate
* group[1].rule[1].rule[3].target[0].parameter[0].valueString = "%answerDecimal.toString()"

* group[1].rule[1].rule[4].name = "integerValue"
* group[1].rule[1].rule[4].source[0].context = "answer"
* group[1].rule[1].rule[4].source[0].element = "value"
* group[1].rule[1].rule[4].source[0].type = "integer"
* group[1].rule[1].rule[4].source[0].variable = "answerInteger"
* group[1].rule[1].rule[4].target[0].context = "dataValue"
* group[1].rule[1].rule[4].target[0].contextType = #variable
* group[1].rule[1].rule[4].target[0].element = "value"
* group[1].rule[1].rule[4].target[0].transform = #evaluate
* group[1].rule[1].rule[4].target[0].parameter[0].valueString = "%answerInteger.toString()"

* group[1].rule[1].rule[5].name = "dateValue"
* group[1].rule[1].rule[5].source[0].context = "answer"
* group[1].rule[1].rule[5].source[0].element = "value"
* group[1].rule[1].rule[5].source[0].type = "date"
* group[1].rule[1].rule[5].source[0].variable = "answerDate"
* group[1].rule[1].rule[5].target[0].context = "dataValue"
* group[1].rule[1].rule[5].target[0].contextType = #variable
* group[1].rule[1].rule[5].target[0].element = "value"
* group[1].rule[1].rule[5].target[0].transform = #evaluate
* group[1].rule[1].rule[5].target[0].parameter[0].valueString = "%answerDate.toString()"

* group[1].rule[1].rule[6].name = "dateTimeValue"
* group[1].rule[1].rule[6].documentation = "A zoned timestamp is read back to the zone-less wall clock DHIS2 stores before it is written; the copy below is the structural claim, not the zone arithmetic."
* group[1].rule[1].rule[6].source[0].context = "answer"
* group[1].rule[1].rule[6].source[0].element = "value"
* group[1].rule[1].rule[6].source[0].type = "dateTime"
* group[1].rule[1].rule[6].source[0].variable = "answerDateTime"
* group[1].rule[1].rule[6].target[0].context = "dataValue"
* group[1].rule[1].rule[6].target[0].contextType = #variable
* group[1].rule[1].rule[6].target[0].element = "value"
* group[1].rule[1].rule[6].target[0].transform = #evaluate
* group[1].rule[1].rule[6].target[0].parameter[0].valueString = "%answerDateTime.toString()"

* group[1].rule[1].rule[7].name = "timeValue"
* group[1].rule[1].rule[7].source[0].context = "answer"
* group[1].rule[1].rule[7].source[0].element = "value"
* group[1].rule[1].rule[7].source[0].type = "time"
* group[1].rule[1].rule[7].source[0].variable = "answerTime"
* group[1].rule[1].rule[7].target[0].context = "dataValue"
* group[1].rule[1].rule[7].target[0].contextType = #variable
* group[1].rule[1].rule[7].target[0].element = "value"
* group[1].rule[1].rule[7].target[0].transform = #evaluate
* group[1].rule[1].rule[7].target[0].parameter[0].valueString = "%answerTime.toString()"

* group[1].rule[1].rule[8].name = "stringValue"
* group[1].rule[1].rule[8].source[0].context = "answer"
* group[1].rule[1].rule[8].source[0].element = "value"
* group[1].rule[1].rule[8].source[0].type = "string"
* group[1].rule[1].rule[8].source[0].variable = "answerString"
* group[1].rule[1].rule[8].target[0].context = "dataValue"
* group[1].rule[1].rule[8].target[0].contextType = #variable
* group[1].rule[1].rule[8].target[0].element = "value"
* group[1].rule[1].rule[8].target[0].transform = #evaluate
* group[1].rule[1].rule[8].target[0].parameter[0].valueString = "%answerString.toString()"

* group[1].rule[1].rule[9].name = "uriValue"
* group[1].rule[1].rule[9].source[0].context = "answer"
* group[1].rule[1].rule[9].source[0].element = "value"
* group[1].rule[1].rule[9].source[0].type = "uri"
* group[1].rule[1].rule[9].source[0].variable = "answerUri"
* group[1].rule[1].rule[9].target[0].context = "dataValue"
* group[1].rule[1].rule[9].target[0].contextType = #variable
* group[1].rule[1].rule[9].target[0].element = "value"
* group[1].rule[1].rule[9].target[0].transform = #evaluate
* group[1].rule[1].rule[9].target[0].parameter[0].valueString = "%answerUri.toString()"

* group[1].rule[1].rule[10].name = "codedValue"
* group[1].rule[1].rule[10].documentation = "A coded answer is stored as the code of the option it names, which is the DHIS2 option code wherever the guide's concept codes are DHIS2 codes."
* group[1].rule[1].rule[10].source[0].context = "answer"
* group[1].rule[1].rule[10].source[0].element = "value"
* group[1].rule[1].rule[10].source[0].type = "Coding"
* group[1].rule[1].rule[10].source[0].variable = "answerCoding"
* group[1].rule[1].rule[10].target[0].context = "dataValue"
* group[1].rule[1].rule[10].target[0].contextType = #variable
* group[1].rule[1].rule[10].target[0].element = "value"
* group[1].rule[1].rule[10].target[0].transform = #evaluate
* group[1].rule[1].rule[10].target[0].parameter[0].valueString = "%answerCoding.code"

* group[1].rule[1].rule[11].name = "organisationUnitValue"
* group[1].rule[1].rule[11].documentation = "An organisation-unit answer references a published Location, and the data value is that Location's http://dhis2.org/fhir/id/org-unit identifier."
* group[1].rule[1].rule[11].source[0].context = "answer"
* group[1].rule[1].rule[11].source[0].element = "value"
* group[1].rule[1].rule[11].source[0].type = "Reference"
* group[1].rule[1].rule[11].source[0].variable = "answerReference"
* group[1].rule[1].rule[11].target[0].context = "dataValue"
* group[1].rule[1].rule[11].target[0].contextType = #variable
* group[1].rule[1].rule[11].target[0].element = "value"
* group[1].rule[1].rule[11].target[0].transform = #evaluate
* group[1].rule[1].rule[11].target[0].parameter[0].valueString = "%answerReference.resolve().identifier.where($this.system = 'http://dhis2.org/fhir/id/org-unit').value"
