// Generated by d2w fhir generate - do not edit

// DHIS2 identifier systems, derived from [generate] identifier_system_base in fhir.toml.
// Each one is declared by a NamingSystem in foundation/d2-naming-systems.fsh.

Alias: $DHIS2-OU = http://dhis2.org/fhir/id/org-unit
Alias: $DHIS2-OU-CODE = http://dhis2.org/fhir/id/org-unit-code
Alias: $DHIS2-OS = http://dhis2.org/fhir/id/option-set
Alias: $DHIS2-OS-CODE = http://dhis2.org/fhir/id/option-set-code
Alias: $DHIS2-OPTION = http://dhis2.org/fhir/id/option
Alias: $DHIS2-OPTION-CODE = http://dhis2.org/fhir/id/option-code
Alias: $DHIS2-DS = http://dhis2.org/fhir/id/data-set
Alias: $DHIS2-DS-CODE = http://dhis2.org/fhir/id/data-set-code
Alias: $DHIS2-PROGRAM = http://dhis2.org/fhir/id/program
Alias: $DHIS2-PROGRAM-CODE = http://dhis2.org/fhir/id/program-code
Alias: $DHIS2-DE = http://dhis2.org/fhir/id/data-element
Alias: $DHIS2-CO = http://dhis2.org/fhir/id/category-option
Alias: $DHIS2-CO-CODE = http://dhis2.org/fhir/id/category-option-code
Alias: $DHIS2-COC = http://dhis2.org/fhir/id/category-option-combo
Alias: $DHIS2-PS = http://dhis2.org/fhir/id/program-stage
Alias: $DHIS2-PS-CODE = http://dhis2.org/fhir/id/program-stage-code
Alias: $DHIS2-TET = http://dhis2.org/fhir/id/tracked-entity-type
Alias: $DHIS2-TET-CODE = http://dhis2.org/fhir/id/tracked-entity-type-code
Alias: $DHIS2-TE = http://dhis2.org/fhir/id/tracked-entity
Alias: $DHIS2-TRACKER-ENROLLMENT = http://dhis2.org/fhir/id/tracker-enrollment
