// Generated by d2w fhir generate - do not edit

Extension: D2AttributeOptionCombo
Id: d2-attribute-option-combo
Title: "DHIS2 attribute option combo"
Description: "The DHIS2 attribute option combo one aggregate response's values are keyed under, drawn from the ValueSet the form's D2AttributeOptionCombos extension names. Absent means the default attribute option combo."
* ^status = #draft
* ^experimental = true
* ^context[+].type = #element
* ^context[=].expression = "QuestionnaireResponse"
* value[x] only Coding
* valueCoding 1..1
* valueCoding.system 1..1
* valueCoding.code 1..1
