// Generated by d2w fhir generate - do not edit

Extension: D2DateLabels
Id: d2-date-labels
Title: "DHIS2 date labels"
Description: "The words a DHIS2 instance puts on the dates a form captures: the date the enrollment began, the date of the incident it follows, and the date the event happened. A slice is present only where the instance states a label, so a form the instance labels nothing on carries no extension at all, and a capture client then falls back to its own wording."
* ^status = #draft
* ^experimental = true
* ^context[+].type = #element
* ^context[=].expression = "Questionnaire"
* extension contains
    enrollmentDate 0..1 and
    incidentDate 0..1 and
    eventDate 0..1
* extension[enrollmentDate] ^short = "What this instance calls the date a tracker enrollment began."
* extension[enrollmentDate].value[x] only string
* extension[enrollmentDate].valueString 1..1
* extension[incidentDate] ^short = "What this instance calls the date of the incident a tracker enrollment follows."
* extension[incidentDate].value[x] only string
* extension[incidentDate].valueString 1..1
* extension[eventDate] ^short = "What this instance calls the date an event was captured on."
* extension[eventDate].value[x] only string
* extension[eventDate].valueString 1..1
