// Generated by d2w fhir generate - do not edit

Extension: D2OriginalCode
Id: d2-original-code
Title: "DHIS2 original code"
Description: "The code the DHIS2 instance holds for the object this resource publishes, stated where the run published that code rewritten. A run under the substitute posture hyphenates every space in a code, and this states the instance's own spelling beside it, so a consumer reading a rewritten code can join it back to the instance."
* ^status = #draft
* ^experimental = true
* ^context[+].type = #element
* ^context[=].expression = "CodeSystem"
* ^context[+].type = #element
* ^context[=].expression = "ValueSet"
* value[x] only string
* valueString 1..1
