// Generated by d2w fhir generate - do not edit

Extension: D2OrganisationUnitLevel
Id: d2-organisation-unit-level
Title: "DHIS2 organisation unit level"
Description: "The level of the DHIS2 organisation unit hierarchy a place sits at, as a code of the published level CodeSystem."
* ^status = #draft
* ^experimental = true
* ^context[+].type = #element
* ^context[=].expression = "Location"
* value[x] only Coding
* valueCoding 1..1
* valueCoding from D2OU_Level_VS (extensible)
