// Generated by d2w fhir generate - do not edit

Extension: D2OrganisationUnitAssignment
Id: d2-organisation-unit-assignment
Title: "DHIS2 organisation unit assignment"
Description: "The organisation units a form may be captured against, as a reference to the List of their Locations. Absent means every unit the registry publishes."
* ^status = #draft
* ^experimental = true
* ^context[+].type = #element
* ^context[=].expression = "Questionnaire"
* value[x] only Reference(List)
* valueReference 1..1
