// Generated by d2w fhir generate - do not edit

Extension: D2ProgramRule
Id: d2-program-rule
Title: "DHIS2 program rule"
Description: "One DHIS2 program rule this form does not express: the expression the instance evaluates, what it does, and the rule's own identity. Non-normative - it states that the server may refuse an answer this form admits."
* ^status = #draft
* ^experimental = true
* ^context[+].type = #element
* ^context[=].expression = "Questionnaire"
* extension contains
    rule 1..1 and
    name 1..1 and
    description 0..1 and
    condition 1..1 and
    action 1..1
* extension[rule] ^short = "The UID of the DHIS2 program rule."
* extension[rule].value[x] only id
* extension[rule].valueId 1..1
* extension[name] ^short = "The name the instance holds the rule under."
* extension[name].value[x] only string
* extension[name].valueString 1..1
* extension[description] ^short = "The rule's free text, absent when the instance states none."
* extension[description].value[x] only string
* extension[condition] ^short = "The DHIS2 expression the server evaluates, exactly as the instance holds it."
* extension[condition].value[x] only string
* extension[condition].valueString 1..1
* extension[action] ^short = "What the rule does when its condition holds."
* extension[action].value[x] only code
* extension[action].valueCode 1..1
* extension[action].valueCode from D2ProgramRuleAction_VS (required)

CodeSystem: D2ProgramRuleAction_CS
Id: d2-program-rule-action-cs
Title: "DHIS2 program rule actions"
Description: "What a DHIS2 program rule does when its condition holds."
* ^status = #draft
* ^experimental = true
* ^content = #complete
* ^caseSensitive = true
* ^valueSet = Canonical(D2ProgramRuleAction_VS)
* #DISPLAYTEXT "Show text"
* #DISPLAYKEYVALUEPAIR "Show a labelled value"
* #HIDEFIELD "Hide a question"
* #HIDESECTION "Hide a section"
* #HIDEPROGRAMSTAGE "Hide a program stage"
* #HIDEOPTION "Hide an answer option"
* #HIDEOPTIONGROUP "Hide a group of answer options"
* #SHOWOPTIONGROUP "Show a group of answer options"
* #ASSIGN "Compute an answer"
* #SHOWWARNING "Warn about an answer"
* #WARNINGONCOMPLETE "Warn when the form is completed"
* #SHOWERROR "Refuse an answer"
* #ERRORONCOMPLETE "Refuse the form on completion"
* #CREATEEVENT "Create an event"
* #SCHEDULEEVENT "Schedule an event"
* #SETMANDATORYFIELD "Require an answer"
* #SENDMESSAGE "Send a message"
* #SCHEDULEMESSAGE "Schedule a message"
* #UNKNOWN "An action type this guide does not name"

ValueSet: D2ProgramRuleAction_VS
Id: d2-program-rule-action-vs
Title: "DHIS2 program rule actions"
Description: "What a DHIS2 program rule does when its condition holds."
* ^status = #draft
* ^experimental = true
* include codes from system D2ProgramRuleAction_CS
