// Generated by d2w fhir generate - do not edit

Extension: D2Repeatable
Id: d2-repeatable
Title: "DHIS2 stage is repeatable"
Description: "Whether one enrollment may capture this DHIS2 tracker program stage more than once. True means a person can be given several events of the stage - a follow-up visit, a repeat measurement - and false means the enrollment holds at most one. Only a tracker program stage form declares it, and it declares it either way, so a reader never has to guess."
* ^status = #draft
* ^experimental = true
* ^context[+].type = #element
* ^context[=].expression = "Questionnaire"
* value[x] only boolean
* valueBoolean 1..1
