// Generated by d2w fhir generate - do not edit

Extension: D2SubjectExists
Id: d2-subject-exists
Title: "DHIS2 subject exists"
Description: "Whether the tracked entity a registration response is subject to is already held by the DHIS2 instance. True means the subject identifier names a person the instance already stores, and the response enrols that person rather than creating one - so it is imported as an enrollment alone, with no tracked entity beside it. Absent or false means the response creates the person it names, which is what a registration does by default."
* ^status = #draft
* ^experimental = true
* ^context[+].type = #element
* ^context[=].expression = "QuestionnaireResponse"
* value[x] only boolean
* valueBoolean 1..1
