// Generated by d2w fhir generate - do not edit

Instance: Questionnaire-EVTsupVis01
InstanceOf: Questionnaire
Title: "Questionnaire - Supervision visit"
Description: "DHIS2 event program Supervision visit (EVTsupVis01) as a data capture form."
Usage: #definition
* id = "EVTsupVis01"
* extension[D2FormType].valueCode = #event
* extension[D2OrganisationUnitAssignment].valueReference = Reference(List/d2-pr-EVTsupVis01-org-units)
* url = "http://example.org/fhir/examples/aggregate-minimal/Questionnaire/EVTsupVis01"
* identifier[+].system = $DHIS2-PROGRAM
* identifier[=].value = "EVTsupVis01"
* identifier[+].system = $DHIS2-PROGRAM-CODE
* identifier[=].value = "EVTsupVis01"
* name = "D2PR_EVTsupVis01"
* title = "Supervision visit"
* description = "DHIS2 event program Supervision visit (EVTsupVis01) as a data capture form."
* status = #draft
* experimental = true
* subjectType = #Location
* code = D2FormType_CS#event
* item[+].linkId = "s46m5MS0hxu"
* item[=].code = D2DE_CS#s46m5MS0hxu "BCG doses given"
* item[=].text = "BCG doses given"
* item[=].type = #integer
* item[=].extension[+].url = "http://example.org/fhir/examples/aggregate-minimal/StructureDefinition/d2-description"
* item[=].extension[=].valueString = "BCG doses administered."
* item[+].linkId = "YtbsuPPo010"
* item[=].code = D2DE_CS#YtbsuPPo010 "Measles doses given"
* item[=].text = "Measles doses given"
* item[=].type = #decimal
