// Generated by d2w fhir generate - do not edit

Instance: Questionnaire-lxAQ7Zs9VYR
InstanceOf: Questionnaire
Title: "Questionnaire - Antenatal care visit"
Description: "DHIS2 event program Antenatal care visit (lxAQ7Zs9VYR) as a data capture form."
Usage: #definition
* id = "lxAQ7Zs9VYR"
* extension[D2FormType].valueCode = #event
* extension[D2DateLabels].extension[eventDate].valueString = "Visit date"
* extension[D2OrganisationUnitAssignment].valueReference = Reference(List/d2-pr-lxAQ7Zs9VYR-org-units)
* extension[D2ProgramRule][+].extension[rule].valueId = "GC4gpdoSD4r"
* extension[D2ProgramRule][=].extension[name].valueString = "Hemoglobin warning"
* extension[D2ProgramRule][=].extension[condition].valueString = "#{hemoglobin} < 9"
* extension[D2ProgramRule][=].extension[action].valueCode = #SHOWWARNING
* extension[D2ProgramRule][=].extension[description].valueString = "Show warning if hemoglobin is dangerously low"
* extension[D2ProgramRule][+].extension[rule].valueId = "xOe5qCzRS0Y"
* extension[D2ProgramRule][=].extension[name].valueString = "Hide smoking cessation councelling"
* extension[D2ProgramRule][=].extension[condition].valueString = "!#{womanSmoking} "
* extension[D2ProgramRule][=].extension[action].valueCode = #HIDEFIELD
* extension[D2ProgramRule][=].extension[description].valueString = "Hide smoking cessation councelling dataelement unless patient is smoking"
* url = "http://example.org/fhir/examples/event-program/Questionnaire/lxAQ7Zs9VYR"
* identifier[+].system = $DHIS2-PROGRAM
* identifier[=].value = "lxAQ7Zs9VYR"
* identifier[+].system = $DHIS2-PROGRAM-CODE
* identifier[=].value = "lxAQ7Zs9VYR"
* name = "D2PR_lxAQ7Zs9VYR"
* title = "Antenatal care visit"
* description = "DHIS2 event program Antenatal care visit (lxAQ7Zs9VYR) as a data capture form."
* status = #draft
* experimental = true
* subjectType = #Location
* code = D2FormType_CS#event
* item[+].linkId = "sWoqcoByYmD"
* item[=].code = D2DE_CS#sWoqcoByYmD "WHOMCH Smoking"
* item[=].text = "WHOMCH Smoking"
* item[=].type = #boolean
* item[+].linkId = "Ok9OQpitjQr"
* item[=].code = D2DE_CS#Ok9OQpitjQr "WHOMCH Smoking cessation counselling provided"
* item[=].text = "WHOMCH Smoking cessation counselling provided"
* item[=].type = #boolean
* item[=].extension[+].url = "http://example.org/fhir/examples/event-program/StructureDefinition/d2-description"
* item[=].extension[=].valueString = "Counselling and behavioural interventions on smoking cessation."
* item[+].linkId = "vANAXwtLwcT"
* item[=].code = D2DE_CS#vANAXwtLwcT "WHOMCH Hemoglobin value"
* item[=].text = "WHOMCH Hemoglobin value"
* item[=].type = #decimal
* item[=].extension[+].url = "http://example.org/fhir/examples/event-program/StructureDefinition/d2-description"
* item[=].extension[=].valueString = "Screening for anemia."
* item[=].extension[+].url = "http://hl7.org/fhir/StructureDefinition/maxValue"
* item[=].extension[=].valueDecimal = 99
