// Generated by d2w fhir generate - do not edit

Instance: Questionnaire-TuL8IOPzpHh
InstanceOf: Questionnaire
Title: "Questionnaire - EPI Stock"
Description: "DHIS2 data set EPI Stock (TuL8IOPzpHh) as a data capture form."
Usage: #definition
* id = "TuL8IOPzpHh"
* extension[D2FormType].valueCode = #aggregate
* extension[D2PeriodType].valueCode = #Monthly
* extension[D2OrganisationUnitAssignment].valueReference = Reference(List/d2-ds-TuL8IOPzpHh-org-units)
* extension[D2AttributeOptionCombos].valueCanonical = Canonical(D2AOC_idcDPkDtepR_VS)
* url = "http://example.org/fhir/examples/patient-summary/Questionnaire/TuL8IOPzpHh"
* identifier[+].system = $DHIS2-DS
* identifier[=].value = "TuL8IOPzpHh"
* identifier[+].system = $DHIS2-DS-CODE
* identifier[=].value = "DS_1149441"
* name = "D2DS_TuL8IOPzpHh"
* title = "EPI Stock"
* description = "DHIS2 data set EPI Stock (TuL8IOPzpHh) as a data capture form."
* status = #draft
* experimental = true
* subjectType = #Location
* code = D2FormType_CS#aggregate
* item[+].linkId = "cZnQDuF3IDz"
* item[=].code = D2DE_CS#cZnQDuF3IDz "Stock PHU discarded BCG"
* item[=].text = "Stock PHU discarded BCG"
* item[=].type = #group
* item[=].item[+].linkId = "cZnQDuF3IDz.fsFN9T4ck3E"
* item[=].item[=].code = D2COC_CS#fsFN9T4ck3E "Expired"
* item[=].item[=].text = "Expired"
* item[=].item[=].type = #decimal
* item[=].item[+].linkId = "cZnQDuF3IDz.pn1upwnbxfn"
* item[=].item[=].code = D2COC_CS#pn1upwnbxfn "Damages"
* item[=].item[=].text = "Damages"
* item[=].item[=].type = #decimal
* item[=].item[+].linkId = "cZnQDuF3IDz.TxaWpw1pN5G"
* item[=].item[=].code = D2COC_CS#TxaWpw1pN5G "VVM Change"
* item[=].item[=].text = "VVM Change"
* item[=].item[=].type = #decimal
* item[+].linkId = "FvKdfA2SuWI"
* item[=].code = D2DE_CS#FvKdfA2SuWI "Stock PHU discarded Measles"
* item[=].text = "Stock PHU discarded Measles"
* item[=].type = #group
* item[=].item[+].linkId = "FvKdfA2SuWI.fsFN9T4ck3E"
* item[=].item[=].code = D2COC_CS#fsFN9T4ck3E "Expired"
* item[=].item[=].text = "Expired"
* item[=].item[=].type = #decimal
* item[=].item[+].linkId = "FvKdfA2SuWI.pn1upwnbxfn"
* item[=].item[=].code = D2COC_CS#pn1upwnbxfn "Damages"
* item[=].item[=].text = "Damages"
* item[=].item[=].type = #decimal
* item[=].item[+].linkId = "FvKdfA2SuWI.TxaWpw1pN5G"
* item[=].item[=].code = D2COC_CS#TxaWpw1pN5G "VVM Change"
* item[=].item[=].text = "VVM Change"
* item[=].item[=].type = #decimal
* item[+].linkId = "WVrH6j3Wfye"
* item[=].code = D2DE_CS#WVrH6j3Wfye "Stock PHU discarded OPV"
* item[=].text = "Stock PHU discarded OPV"
* item[=].type = #group
* item[=].item[+].linkId = "WVrH6j3Wfye.fsFN9T4ck3E"
* item[=].item[=].code = D2COC_CS#fsFN9T4ck3E "Expired"
* item[=].item[=].text = "Expired"
* item[=].item[=].type = #decimal
* item[=].item[+].linkId = "WVrH6j3Wfye.pn1upwnbxfn"
* item[=].item[=].code = D2COC_CS#pn1upwnbxfn "Damages"
* item[=].item[=].text = "Damages"
* item[=].item[=].type = #decimal
* item[=].item[+].linkId = "WVrH6j3Wfye.TxaWpw1pN5G"
* item[=].item[=].code = D2COC_CS#TxaWpw1pN5G "VVM Change"
* item[=].item[=].text = "VVM Change"
* item[=].item[=].type = #decimal
* item[+].linkId = "p1MDHOT6ENy"
* item[=].code = D2DE_CS#p1MDHOT6ENy "Stock PHU dispensed BCG"
* item[=].text = "Stock PHU dispensed BCG"
* item[=].type = #decimal
* item[+].linkId = "lVknokmR4Ip"
* item[=].code = D2DE_CS#lVknokmR4Ip "Stock PHU dispensed Measles"
* item[=].text = "Stock PHU dispensed Measles"
* item[=].type = #decimal
* item[+].linkId = "FTINmL2lehN"
* item[=].code = D2DE_CS#FTINmL2lehN "Stock PHU dispensed OPV"
* item[=].text = "Stock PHU dispensed OPV"
* item[=].type = #decimal
* item[+].linkId = "axVhq1itoQD"
* item[=].code = D2DE_CS#axVhq1itoQD "Stock PHU received BCG"
* item[=].text = "Stock PHU received BCG"
* item[=].type = #decimal
* item[+].linkId = "XNrjXqZrHD8"
* item[=].code = D2DE_CS#XNrjXqZrHD8 "Stock PHU received Measles"
* item[=].text = "Stock PHU received Measles"
* item[=].type = #decimal
* item[+].linkId = "nGCLjZDn0Q4"
* item[=].code = D2DE_CS#nGCLjZDn0Q4 "Stock PHU received OPV"
* item[=].text = "Stock PHU received OPV"
* item[=].type = #decimal
* item[+].linkId = "t99PL3gUxIl"
* item[=].code = D2DE_CS#t99PL3gUxIl "Stock PHU start balance BCG"
* item[=].text = "Stock PHU start balance BCG"
* item[=].type = #decimal
* item[+].linkId = "vEAo4KwsAzl"
* item[=].code = D2DE_CS#vEAo4KwsAzl "Stock PHU start balance Measles"
* item[=].text = "Stock PHU start balance Measles"
* item[=].type = #decimal
* item[+].linkId = "iuSIObmKutb"
* item[=].code = D2DE_CS#iuSIObmKutb "Stock PHU start balance OPV"
* item[=].text = "Stock PHU start balance OPV"
* item[=].type = #decimal
