// Generated by d2w fhir generate - do not edit

Instance: Questionnaire-A03MvHHogjR
InstanceOf: Questionnaire
Title: "Questionnaire - Child Programme - Birth"
Description: "DHIS2 tracker program stage Birth (A03MvHHogjR) of program Child Programme (IpHINAT79UW) as a data capture form."
Usage: #definition
* id = "A03MvHHogjR"
* extension[D2FormType].valueCode = #tracker-event
* extension[D2Repeatable].valueBoolean = false
* extension[D2DateLabels].extension[eventDate].valueString = "Report date"
* extension[D2OrganisationUnitAssignment].valueReference = Reference(List/d2-pr-IpHINAT79UW-org-units)
* extension[D2ProgramRule][+].extension[rule].valueId = "NAgjOfWMXg6"
* extension[D2ProgramRule][=].extension[name].valueString = "Ask for comment for low apgar"
* extension[D2ProgramRule][=].extension[condition].valueString = "#{apgarscore} >= 0 && #{apgarscore} < 4 && #{apgarcomment} == ''"
* extension[D2ProgramRule][=].extension[action].valueCode = #SHOWWARNING
* extension[D2ProgramRule][=].extension[description].valueString = "Show warrning if Apgar is between 0 and 4 and there is no comment provided."
* extension[D2ProgramRule][+].extension[rule].valueId = "tTPMkizzUZg"
* extension[D2ProgramRule][=].extension[name].valueString = "Demand comment if apgar is under zero"
* extension[D2ProgramRule][=].extension[condition].valueString = "#{apgarscore} <0 && #{apgarcomment} == ''"
* extension[D2ProgramRule][=].extension[action].valueCode = #SHOWERROR
* extension[D2ProgramRule][=].extension[description].valueString = "If Apgar is provided as being under zero and there is no comment for the anomaly, show an error message."
* url = "http://example.org/fhir/examples/patient-summary/Questionnaire/A03MvHHogjR"
* identifier[+].system = $DHIS2-PS
* identifier[=].value = "A03MvHHogjR"
* identifier[+].system = $DHIS2-PS-CODE
* identifier[=].value = "A03MvHHogjR"
* identifier[+].system = $DHIS2-PROGRAM
* identifier[=].value = "IpHINAT79UW"
* name = "D2PS_A03MvHHogjR"
* title = "Child Programme - Birth"
* description = "DHIS2 tracker program stage Birth (A03MvHHogjR) of program Child Programme (IpHINAT79UW) as a data capture form."
* status = #draft
* experimental = true
* subjectType = #Patient
* code = D2FormType_CS#tracker-event
* item[+].linkId = "a3kGcGDCuk6"
* item[=].code = D2DE_CS#a3kGcGDCuk6 "MCH Apgar Score"
* item[=].text = "Apgar Score"
* item[=].type = #decimal
* item[=].extension[+].url = "http://example.org/fhir/examples/patient-summary/StructureDefinition/d2-description"
* item[=].extension[=].valueString = "Apgar is a quick test performed on a baby at 1 and 5 minutes after birth. The 1-minute score determines how well the baby tolerated the birthing process. The 5-minute score tells the doctor how well the baby is doing outside the mother's womb."
* item[+].linkId = "H6uSAMO5WLD"
* item[=].code = D2DE_CS#H6uSAMO5WLD "MCH Apgar comment"
* item[=].text = "Apgar comment"
* item[=].type = #text
* item[=].enableWhen[+].question = "a3kGcGDCuk6"
* item[=].enableWhen[=].operator = #"<="
* item[=].enableWhen[=].answerDecimal = 7
* item[=].enableWhen[+].question = "a3kGcGDCuk6"
* item[=].enableWhen[=].operator = #exists
* item[=].enableWhen[=].answerBoolean = false
* item[=].enableBehavior = #any
* item[+].linkId = "UXz7xuGCEhU"
* item[=].code = D2DE_CS#UXz7xuGCEhU "MCH Weight (g)"
* item[=].text = "Weight (g)"
* item[=].type = #decimal
* item[+].linkId = "wQLfBvPrXqq"
* item[=].code = D2DE_CS#wQLfBvPrXqq "MCH ARV at birth"
* item[=].text = "ARV at birth"
* item[=].type = #choice
* item[=].answerValueSet = Canonical(D2OS_f38bstJioPs_VS)
* item[=].extension[+].url = "http://example.org/fhir/examples/patient-summary/StructureDefinition/d2-description"
* item[=].extension[=].valueString = "Onlu used for birth details."
* item[+].linkId = "bx6fsa0t90x"
* item[=].code = D2DE_CS#bx6fsa0t90x "MCH BCG dose"
* item[=].text = "BCG dose"
* item[=].type = #boolean
* item[+].linkId = "ebaJjqltK5N"
* item[=].code = D2DE_CS#ebaJjqltK5N "MCH OPV dose"
* item[=].text = "OPV dose"
* item[=].type = #choice
* item[=].answerValueSet = Canonical(D2OS_kzgQRhOCadd_VS)
* item[+].linkId = "X8zyunlgUfM"
* item[=].code = D2DE_CS#X8zyunlgUfM "MCH Infant Feeding"
* item[=].text = "Infant Feeding"
* item[=].type = #choice
* item[=].answerValueSet = Canonical(D2OS_x31y45jvIQL_VS)
* item[+].linkId = "uf3svrmp8Oj"
* item[=].code = D2DE_CS#uf3svrmp8Oj "Birth certificate"
* item[=].text = "Birth certificate"
* item[=].type = #attachment
