// Generated by d2w fhir generate - do not edit

Instance: Questionnaire-IpHINAT79UW
InstanceOf: Questionnaire
Title: "Questionnaire - Child Programme"
Description: "DHIS2 tracker program Child Programme (IpHINAT79UW) as a registration form: the tracked entity attributes captured when a person is enrolled in the program."
Usage: #definition
* id = "IpHINAT79UW"
* extension[D2FormType].valueCode = #tracker
* extension[D2CollectsIncidentDate].valueBoolean = true
* extension[D2DateLabels].extension[enrollmentDate].valueString = "Date of enrollment"
* extension[D2DateLabels].extension[incidentDate].valueString = "Date of birth"
* extension[D2OrganisationUnitAssignment].valueReference = Reference(List/d2-pr-IpHINAT79UW-org-units)
* extension[D2ProgramRule][+].extension[rule].valueId = "NAgjOfWMXg6"
* extension[D2ProgramRule][=].extension[name].valueString = "Ask for comment for low apgar"
* extension[D2ProgramRule][=].extension[condition].valueString = "#{apgarscore} >= 0 && #{apgarscore} < 4 && #{apgarcomment} == ''"
* extension[D2ProgramRule][=].extension[action].valueCode = #SHOWWARNING
* extension[D2ProgramRule][=].extension[description].valueString = "Show warrning if Apgar is between 0 and 4 and there is no comment provided."
* extension[D2ProgramRule][+].extension[rule].valueId = "tTPMkizzUZg"
* extension[D2ProgramRule][=].extension[name].valueString = "Demand comment if apgar is under zero"
* extension[D2ProgramRule][=].extension[condition].valueString = "#{apgarscore} <0 && #{apgarcomment} == ''"
* extension[D2ProgramRule][=].extension[action].valueCode = #SHOWERROR
* extension[D2ProgramRule][=].extension[description].valueString = "If Apgar is provided as being under zero and there is no comment for the anomaly, show an error message."
* url = "http://example.org/fhir/examples/patient-summary/Questionnaire/IpHINAT79UW"
* identifier[+].system = $DHIS2-PROGRAM
* identifier[=].value = "IpHINAT79UW"
* identifier[+].system = $DHIS2-PROGRAM-CODE
* identifier[=].value = "IpHINAT79UW"
* identifier[+].system = $DHIS2-TET
* identifier[=].value = "nEenWmSyUEp"
* name = "D2PR_IpHINAT79UW"
* title = "Child Programme"
* description = "DHIS2 tracker program Child Programme (IpHINAT79UW) as a registration form: the tracked entity attributes captured when a person is enrolled in the program."
* status = #draft
* experimental = true
* subjectType = #Patient
* code = D2FormType_CS#tracker
* item[+].linkId = "w75KJ2mc4zz"
* item[=].code = D2TEA_CS#w75KJ2mc4zz "First name"
* item[=].text = "First name"
* item[=].type = #string
* item[=].extension[+].url = "http://example.org/fhir/examples/patient-summary/StructureDefinition/d2-description"
* item[=].extension[=].valueString = "First name"
* item[=].extension[+].url = "http://example.org/fhir/examples/patient-summary/StructureDefinition/d2-entity-level"
* item[=].extension[=].valueBoolean = true
* item[+].linkId = "zDhUuAYrxNC"
* item[=].code = D2TEA_CS#zDhUuAYrxNC "Last name"
* item[=].text = "Last name"
* item[=].type = #string
* item[=].extension[+].url = "http://example.org/fhir/examples/patient-summary/StructureDefinition/d2-description"
* item[=].extension[=].valueString = "Last name"
* item[=].extension[+].url = "http://example.org/fhir/examples/patient-summary/StructureDefinition/d2-entity-level"
* item[=].extension[=].valueBoolean = true
* item[+].linkId = "cejWyOfXge6"
* item[=].code = D2TEA_CS#cejWyOfXge6 "Gender"
* item[=].text = "Gender"
* item[=].type = #choice
* item[=].answerValueSet = Canonical(D2OS_pC3N9N77UmT_VS)
* item[=].extension[+].url = "http://example.org/fhir/examples/patient-summary/StructureDefinition/d2-description"
* item[=].extension[=].valueString = "Gender"
* item[=].extension[+].url = "http://example.org/fhir/examples/patient-summary/StructureDefinition/d2-entity-level"
* item[=].extension[=].valueBoolean = false
* item[+].linkId = "lZGmxYbs97q"
* item[=].code = D2TEA_CS#lZGmxYbs97q "Unique ID"
* item[=].text = "Unique ID"
* item[=].type = #string
* item[=].readOnly = true
* item[=].extension[+].url = "http://example.org/fhir/examples/patient-summary/StructureDefinition/d2-description"
* item[=].extension[=].valueString = "Unique identiifer"
* item[=].extension[+].url = "http://example.org/fhir/examples/patient-summary/StructureDefinition/d2-entity-level"
* item[=].extension[=].valueBoolean = true
