// Generated by d2w fhir generate - do not edit

Instance: Questionnaire-ZzYYXq4fJie
InstanceOf: Questionnaire
Title: "Questionnaire - Child Programme - Baby Postnatal"
Description: "DHIS2 tracker program stage Baby Postnatal (ZzYYXq4fJie) of program Child Programme (IpHINAT79UW) as a data capture form."
Usage: #definition
* id = "ZzYYXq4fJie"
* extension[D2FormType].valueCode = #tracker-event
* extension[D2Repeatable].valueBoolean = false
* extension[D2OrganisationUnitAssignment].valueReference = Reference(List/d2-pr-IpHINAT79UW-org-units)
* extension[D2ProgramRule][+].extension[rule].valueId = "NAgjOfWMXg6"
* extension[D2ProgramRule][=].extension[name].valueString = "Ask for comment for low apgar"
* extension[D2ProgramRule][=].extension[condition].valueString = "#{apgarscore} >= 0 && #{apgarscore} < 4 && #{apgarcomment} == ''"
* extension[D2ProgramRule][=].extension[action].valueCode = #SHOWWARNING
* extension[D2ProgramRule][=].extension[description].valueString = "Show warrning if Apgar is between 0 and 4 and there is no comment provided."
* extension[D2ProgramRule][+].extension[rule].valueId = "tTPMkizzUZg"
* extension[D2ProgramRule][=].extension[name].valueString = "Demand comment if apgar is under zero"
* extension[D2ProgramRule][=].extension[condition].valueString = "#{apgarscore} <0 && #{apgarcomment} == ''"
* extension[D2ProgramRule][=].extension[action].valueCode = #SHOWERROR
* extension[D2ProgramRule][=].extension[description].valueString = "If Apgar is provided as being under zero and there is no comment for the anomaly, show an error message."
* url = "http://example.org/fhir/examples/patient-summary/Questionnaire/ZzYYXq4fJie"
* identifier[+].system = $DHIS2-PS
* identifier[=].value = "ZzYYXq4fJie"
* identifier[+].system = $DHIS2-PS-CODE
* identifier[=].value = "ZzYYXq4fJie"
* identifier[+].system = $DHIS2-PROGRAM
* identifier[=].value = "IpHINAT79UW"
* name = "D2PS_ZzYYXq4fJie"
* title = "Child Programme - Baby Postnatal"
* description = "DHIS2 tracker program stage Baby Postnatal (ZzYYXq4fJie) of program Child Programme (IpHINAT79UW) as a data capture form."
* status = #draft
* experimental = true
* subjectType = #Patient
* code = D2FormType_CS#tracker-event
* item[+].linkId = "GQY2lXrypjO"
* item[=].code = D2DE_CS#GQY2lXrypjO "MCH Infant Weight (g)"
* item[=].text = "Infant Weight (g)"
* item[=].type = #decimal
* item[=].extension[+].url = "http://example.org/fhir/examples/patient-summary/StructureDefinition/d2-description"
* item[=].extension[=].valueString = "Infant weight in grams"
* item[+].linkId = "X8zyunlgUfM"
* item[=].code = D2DE_CS#X8zyunlgUfM "MCH Infant Feeding"
* item[=].text = "Infant Feeding"
* item[=].type = #choice
* item[=].answerValueSet = Canonical(D2OS_x31y45jvIQL_VS)
* item[+].linkId = "FqlgKAG8HOu"
* item[=].code = D2DE_CS#FqlgKAG8HOu "MCH Measles dose"
* item[=].text = "Measles dose"
* item[=].type = #boolean
* item[+].linkId = "vTUhAUZFoys"
* item[=].code = D2DE_CS#vTUhAUZFoys "MCH Penta dose"
* item[=].text = "Penta dose"
* item[=].type = #choice
* item[=].answerValueSet = Canonical(D2OS_kzgQRhOCadd_VS)
* item[+].linkId = "rxBfISxXS2U"
* item[=].code = D2DE_CS#rxBfISxXS2U "MCH Yellow fever dose"
* item[=].text = "Yellow fever dose"
* item[=].type = #boolean
* item[+].linkId = "lNNb3truQoi"
* item[=].code = D2DE_CS#lNNb3truQoi "MCH IPT dose"
* item[=].text = "IPT dose"
* item[=].type = #choice
* item[=].answerValueSet = Canonical(D2OS_nH8Y04zS7UV_VS)
* item[+].linkId = "pOe0ogW4OWd"
* item[=].code = D2DE_CS#pOe0ogW4OWd "MCH DPT dose"
* item[=].text = "DPT dose"
* item[=].type = #choice
* item[=].answerValueSet = Canonical(D2OS_udkr3ihaeD3_VS)
* item[+].linkId = "HLmTEmupdX0"
* item[=].code = D2DE_CS#HLmTEmupdX0 "MCH Vit A"
* item[=].text = "Vit A"
* item[=].type = #boolean
* item[+].linkId = "cYGaxwK615G"
* item[=].code = D2DE_CS#cYGaxwK615G "MCH Infant HIV Test Result"
* item[=].text = "Infant HIV Test Result"
* item[=].type = #choice
* item[=].answerValueSet = Canonical(D2OS_oXR37f2wOb1_VS)
* item[+].linkId = "hDZbpskhqDd"
* item[=].code = D2DE_CS#hDZbpskhqDd "MCH HIV Test Type"
* item[=].text = "HIV Test Type"
* item[=].type = #choice
* item[=].answerValueSet = Canonical(D2OS_OGmE3wUMEzu_VS)
* item[+].linkId = "sj3j9Hwc7so"
* item[=].code = D2DE_CS#sj3j9Hwc7so "MCH Child ARVs"
* item[=].text = "Child ARVs"
* item[=].type = #choice
* item[=].answerValueSet = Canonical(D2OS_dgsftM0rXu2_VS)
* item[=].extension[+].url = "http://example.org/fhir/examples/patient-summary/StructureDefinition/d2-description"
* item[=].extension[=].valueString = "ARVs for child postnatal visits."
* item[+].linkId = "aei1xRjSU2l"
* item[=].code = D2DE_CS#aei1xRjSU2l "MCH Septrin Given"
* item[=].text = "Septrin Given"
* item[=].type = #choice
* item[=].answerValueSet = Canonical(D2OS_XdI8KRJiRoZ_VS)
* item[+].linkId = "BeynU4L6VCQ"
* item[=].code = D2DE_CS#BeynU4L6VCQ "MCH Results given to caretaker"
* item[=].text = "Results given to caretaker"
* item[=].type = #choice
* item[=].answerValueSet = Canonical(D2OS_XdI8KRJiRoZ_VS)
* item[+].linkId = "OuJ6sgPyAbC"
* item[=].code = D2DE_CS#OuJ6sgPyAbC "MCH Visit Comment"
* item[=].text = "Visit comment (optional)"
* item[=].type = #text
* item[=].extension[+].url = "http://example.org/fhir/examples/patient-summary/StructureDefinition/d2-description"
* item[=].extension[=].valueString = "Free text comment used to put additional information for a visit."
