// Generated by d2w fhir generate - do not edit

CodeSystem: D2COC_CS
Id: d2-coc-cs
Title: "DHIS2 category option combinations"
Description: "DHIS2 category option combinations the generated questionnaires disaggregate by. Concept codes are DHIS2 category option combo UIDs."
* ^status = #draft
* ^experimental = true
* ^content = #complete
* ^caseSensitive = true
* ^valueSet = Canonical(D2COC_VS)
* ^property[+].code = #dhis2-code
* ^property[=].uri = "http://dhis2.org/fhir/property/dhis2-code"
* ^property[=].description = "DHIS2 category option combo code."
* ^property[=].type = #string
* ^property[+].code = #category-Qzh0MSUx4RM
* ^property[=].uri = "http://dhis2.org/fhir/property/category-Qzh0MSUx4RM"
* ^property[=].description = "DHIS2 category Stock discarded."
* ^property[=].type = #Coding
* #pn1upwnbxfn "Damages"
* #pn1upwnbxfn ^property[+].code = #dhis2-code
* #pn1upwnbxfn ^property[=].valueString = "COC_360271"
* #pn1upwnbxfn ^property[+].code = #category-Qzh0MSUx4RM
* #pn1upwnbxfn ^property[=].valueCoding = http://example.org/fhir/examples/event-program/CodeSystem/d2-cat-Qzh0MSUx4RM-cs#mInFlpnx6TQ "Damages"
* #fsFN9T4ck3E "Expired"
* #fsFN9T4ck3E ^property[+].code = #dhis2-code
* #fsFN9T4ck3E ^property[=].valueString = "COC_360270"
* #fsFN9T4ck3E ^property[+].code = #category-Qzh0MSUx4RM
* #fsFN9T4ck3E ^property[=].valueCoding = http://example.org/fhir/examples/event-program/CodeSystem/d2-cat-Qzh0MSUx4RM-cs#YHb43JqCAmI "Expired"
* #TxaWpw1pN5G "VVM Change"
* #TxaWpw1pN5G ^property[+].code = #dhis2-code
* #TxaWpw1pN5G ^property[=].valueString = "COC_360272"
* #TxaWpw1pN5G ^property[+].code = #category-Qzh0MSUx4RM
* #TxaWpw1pN5G ^property[=].valueCoding = http://example.org/fhir/examples/event-program/CodeSystem/d2-cat-Qzh0MSUx4RM-cs#qKc2WhjMPKC "VVM Change"

ValueSet: D2COC_VS
Id: d2-coc-vs
Title: "DHIS2 category option combinations"
Description: "DHIS2 category option combinations the generated questionnaires disaggregate by. Concept codes are DHIS2 category option combo UIDs."
* ^status = #draft
* ^experimental = true
* include codes from system D2COC_CS
