// Generated by d2w fhir generate - do not edit

CodeSystem: D2DE_CS
Id: d2-de-cs
Title: "DHIS2 data elements"
Description: "DHIS2 data elements captured by the generated questionnaires. Concept codes are DHIS2 data element UIDs."
* ^status = #draft
* ^experimental = true
* ^content = #complete
* ^caseSensitive = true
* ^valueSet = Canonical(D2DE_VS)
* ^property[+].code = #dhis2-code
* ^property[=].uri = "http://dhis2.org/fhir/property/dhis2-code"
* ^property[=].description = "DHIS2 data element code."
* ^property[=].type = #string
* ^property[+].code = #domain
* ^property[=].uri = "http://dhis2.org/fhir/property/domain"
* ^property[=].description = "DHIS2 data element domain type."
* ^property[=].type = #code
* ^property[+].code = #value-type
* ^property[=].uri = "http://dhis2.org/fhir/property/value-type"
* ^property[=].description = "DHIS2 data element value type."
* ^property[=].type = #code
* #DeAncDanger "ANC danger signs present"
* #DeAncDanger ^property[+].code = #domain
* #DeAncDanger ^property[=].valueCode = #tracker
* #DeAncDanger ^property[+].code = #value-type
* #DeAncDanger ^property[=].valueCode = #BOOLEAN
* #DeAncBpSys1 "ANC systolic blood pressure"
* #DeAncBpSys1 ^property[+].code = #domain
* #DeAncBpSys1 ^property[=].valueCode = #tracker
* #DeAncBpSys1 ^property[+].code = #value-type
* #DeAncBpSys1 ^property[=].valueCode = #INTEGER
* #DeAncVisNo1 "ANC visit number"
* #DeAncVisNo1 ^property[+].code = #domain
* #DeAncVisNo1 ^property[=].valueCode = #tracker
* #DeAncVisNo1 ^property[+].code = #value-type
* #DeAncVisNo1 ^property[=].valueCode = #INTEGER_POSITIVE
* #cZnQDuF3IDz "Stock PHU discarded BCG"
* #cZnQDuF3IDz ^property[+].code = #dhis2-code
* #cZnQDuF3IDz ^property[=].valueString = "DE_360103"
* #cZnQDuF3IDz ^property[+].code = #domain
* #cZnQDuF3IDz ^property[=].valueCode = #aggregate
* #cZnQDuF3IDz ^property[+].code = #value-type
* #cZnQDuF3IDz ^property[=].valueCode = #NUMBER
* #FvKdfA2SuWI "Stock PHU discarded Measles"
* #FvKdfA2SuWI ^property[+].code = #dhis2-code
* #FvKdfA2SuWI ^property[=].valueString = "DE_360126"
* #FvKdfA2SuWI ^property[+].code = #domain
* #FvKdfA2SuWI ^property[=].valueCode = #aggregate
* #FvKdfA2SuWI ^property[+].code = #value-type
* #FvKdfA2SuWI ^property[=].valueCode = #NUMBER
* #WVrH6j3Wfye "Stock PHU discarded OPV"
* #WVrH6j3Wfye ^property[+].code = #dhis2-code
* #WVrH6j3Wfye ^property[=].valueString = "DE_360129"
* #WVrH6j3Wfye ^property[+].code = #domain
* #WVrH6j3Wfye ^property[=].valueCode = #aggregate
* #WVrH6j3Wfye ^property[+].code = #value-type
* #WVrH6j3Wfye ^property[=].valueCode = #NUMBER
* #p1MDHOT6ENy "Stock PHU dispensed BCG"
* #p1MDHOT6ENy ^property[+].code = #dhis2-code
* #p1MDHOT6ENy ^property[=].valueString = "DE_360049"
* #p1MDHOT6ENy ^property[+].code = #domain
* #p1MDHOT6ENy ^property[=].valueCode = #aggregate
* #p1MDHOT6ENy ^property[+].code = #value-type
* #p1MDHOT6ENy ^property[=].valueCode = #NUMBER
* #lVknokmR4Ip "Stock PHU dispensed Measles"
* #lVknokmR4Ip ^property[+].code = #dhis2-code
* #lVknokmR4Ip ^property[=].valueString = "DE_360072"
* #lVknokmR4Ip ^property[+].code = #domain
* #lVknokmR4Ip ^property[=].valueCode = #aggregate
* #lVknokmR4Ip ^property[+].code = #value-type
* #lVknokmR4Ip ^property[=].valueCode = #NUMBER
* #FTINmL2lehN "Stock PHU dispensed OPV"
* #FTINmL2lehN ^property[+].code = #dhis2-code
* #FTINmL2lehN ^property[=].valueString = "DE_360075"
* #FTINmL2lehN ^property[+].code = #domain
* #FTINmL2lehN ^property[=].valueCode = #aggregate
* #FTINmL2lehN ^property[+].code = #value-type
* #FTINmL2lehN ^property[=].valueCode = #NUMBER
* #axVhq1itoQD "Stock PHU received BCG"
* #axVhq1itoQD ^property[+].code = #dhis2-code
* #axVhq1itoQD ^property[=].valueString = "DE_359995"
* #axVhq1itoQD ^property[+].code = #domain
* #axVhq1itoQD ^property[=].valueCode = #aggregate
* #axVhq1itoQD ^property[+].code = #value-type
* #axVhq1itoQD ^property[=].valueCode = #NUMBER
* #XNrjXqZrHD8 "Stock PHU received Measles"
* #XNrjXqZrHD8 ^property[+].code = #dhis2-code
* #XNrjXqZrHD8 ^property[=].valueString = "DE_360018"
* #XNrjXqZrHD8 ^property[+].code = #domain
* #XNrjXqZrHD8 ^property[=].valueCode = #aggregate
* #XNrjXqZrHD8 ^property[+].code = #value-type
* #XNrjXqZrHD8 ^property[=].valueCode = #NUMBER
* #nGCLjZDn0Q4 "Stock PHU received OPV"
* #nGCLjZDn0Q4 ^property[+].code = #dhis2-code
* #nGCLjZDn0Q4 ^property[=].valueString = "DE_360021"
* #nGCLjZDn0Q4 ^property[+].code = #domain
* #nGCLjZDn0Q4 ^property[=].valueCode = #aggregate
* #nGCLjZDn0Q4 ^property[+].code = #value-type
* #nGCLjZDn0Q4 ^property[=].valueCode = #NUMBER
* #t99PL3gUxIl "Stock PHU start balance BCG"
* #t99PL3gUxIl ^property[+].code = #dhis2-code
* #t99PL3gUxIl ^property[=].valueString = "DE_359941"
* #t99PL3gUxIl ^property[+].code = #domain
* #t99PL3gUxIl ^property[=].valueCode = #aggregate
* #t99PL3gUxIl ^property[+].code = #value-type
* #t99PL3gUxIl ^property[=].valueCode = #NUMBER
* #vEAo4KwsAzl "Stock PHU start balance Measles"
* #vEAo4KwsAzl ^property[+].code = #dhis2-code
* #vEAo4KwsAzl ^property[=].valueString = "DE_359964"
* #vEAo4KwsAzl ^property[+].code = #domain
* #vEAo4KwsAzl ^property[=].valueCode = #aggregate
* #vEAo4KwsAzl ^property[+].code = #value-type
* #vEAo4KwsAzl ^property[=].valueCode = #NUMBER
* #iuSIObmKutb "Stock PHU start balance OPV"
* #iuSIObmKutb ^property[+].code = #dhis2-code
* #iuSIObmKutb ^property[=].valueString = "DE_359967"
* #iuSIObmKutb ^property[+].code = #domain
* #iuSIObmKutb ^property[=].valueCode = #aggregate
* #iuSIObmKutb ^property[+].code = #value-type
* #iuSIObmKutb ^property[=].valueCode = #NUMBER
* #vANAXwtLwcT "WHOMCH Hemoglobin value"
* #vANAXwtLwcT ^property[+].code = #dhis2-code
* #vANAXwtLwcT ^property[=].valueString = "LAB_HB"
* #vANAXwtLwcT ^property[+].code = #domain
* #vANAXwtLwcT ^property[=].valueCode = #tracker
* #vANAXwtLwcT ^property[+].code = #value-type
* #vANAXwtLwcT ^property[=].valueCode = #NUMBER
* #sWoqcoByYmD "WHOMCH Smoking"
* #sWoqcoByYmD ^property[+].code = #dhis2-code
* #sWoqcoByYmD ^property[=].valueString = "STA_SMO"
* #sWoqcoByYmD ^property[+].code = #domain
* #sWoqcoByYmD ^property[=].valueCode = #tracker
* #sWoqcoByYmD ^property[+].code = #value-type
* #sWoqcoByYmD ^property[=].valueCode = #BOOLEAN
* #Ok9OQpitjQr "WHOMCH Smoking cessation counselling provided"
* #Ok9OQpitjQr ^property[+].code = #dhis2-code
* #Ok9OQpitjQr ^property[=].valueString = "EA5_TRE_SMO"
* #Ok9OQpitjQr ^property[+].code = #domain
* #Ok9OQpitjQr ^property[=].valueCode = #tracker
* #Ok9OQpitjQr ^property[+].code = #value-type
* #Ok9OQpitjQr ^property[=].valueCode = #BOOLEAN

ValueSet: D2DE_VS
Id: d2-de-vs
Title: "DHIS2 data elements"
Description: "DHIS2 data elements captured by the generated questionnaires. Concept codes are DHIS2 data element UIDs."
* ^status = #draft
* ^experimental = true
* include codes from system D2DE_CS
