// Generated by d2w fhir generate - do not edit

CodeSystem: D2TEA_CS
Id: d2-tea-cs
Title: "DHIS2 tracked entity attributes"
Description: "DHIS2 tracked entity attributes captured by the generated tracker registration forms. Concept codes are DHIS2 tracked entity attribute UIDs."
* ^status = #draft
* ^experimental = true
* ^content = #complete
* ^caseSensitive = true
* ^valueSet = Canonical(D2TEA_VS)
* ^property[+].code = #dhis2-code
* ^property[=].uri = "http://dhis2.org/fhir/property/dhis2-code"
* ^property[=].description = "DHIS2 tracked entity attribute code."
* ^property[=].type = #string
* ^property[+].code = #value-type
* ^property[=].uri = "http://dhis2.org/fhir/property/value-type"
* ^property[=].description = "DHIS2 tracked entity attribute value type."
* ^property[=].type = #code
* ^property[+].code = #unique
* ^property[=].uri = "http://dhis2.org/fhir/property/unique"
* ^property[=].description = "Whether DHIS2 declares the tracked entity attribute unique."
* ^property[=].type = #boolean
* ^property[+].code = #searchable
* ^property[=].uri = "http://dhis2.org/fhir/property/searchable"
* ^property[=].description = "Whether DHIS2 declares the tracked entity attribute searchable in any context this guide publishes."
* ^property[=].type = #boolean
* ^property[+].code = #generated
* ^property[=].uri = "http://dhis2.org/fhir/property/generated"
* ^property[=].description = "Whether DHIS2 mints the tracked entity attribute's value itself."
* ^property[=].type = #boolean
* ^property[+].code = #pattern
* ^property[=].uri = "http://dhis2.org/fhir/property/pattern"
* ^property[=].description = "The DHIS2 reserved-value pattern a generated tracked entity attribute is minted from."
* ^property[=].type = #string
* ^property[+].code = #display-in-list
* ^property[=].uri = "http://dhis2.org/fhir/property/display-in-list"
* ^property[=].description = "Whether DHIS2 shows the tracked entity attribute in the working lists of any context this guide publishes."
* ^property[=].type = #boolean
* ^property[+].code = #searchable-PrAncCare01
* ^property[=].uri = "http://dhis2.org/fhir/property/searchable-PrAncCare01"
* ^property[=].description = "Whether DHIS2 declares the tracked entity attribute searchable in tracker program ANC follow-up (PrAncCare01)."
* ^property[=].type = #boolean
* ^property[+].code = #searchable-nEenWmSyUEp
* ^property[=].uri = "http://dhis2.org/fhir/property/searchable-nEenWmSyUEp"
* ^property[=].description = "Whether DHIS2 declares the tracked entity attribute searchable in tracked entity type Person (Play) (nEenWmSyUEp)."
* ^property[=].type = #boolean
* #w75KJ2mc4zz "First name (Play)"
* #w75KJ2mc4zz ^property[+].code = #dhis2-code
* #w75KJ2mc4zz ^property[=].valueString = "MMD_PER_NAM"
* #w75KJ2mc4zz ^property[+].code = #value-type
* #w75KJ2mc4zz ^property[=].valueCode = #TEXT
* #w75KJ2mc4zz ^property[+].code = #unique
* #w75KJ2mc4zz ^property[=].valueBoolean = false
* #w75KJ2mc4zz ^property[+].code = #searchable
* #w75KJ2mc4zz ^property[=].valueBoolean = true
* #w75KJ2mc4zz ^property[+].code = #generated
* #w75KJ2mc4zz ^property[=].valueBoolean = false
* #w75KJ2mc4zz ^property[+].code = #display-in-list
* #w75KJ2mc4zz ^property[=].valueBoolean = true
* #w75KJ2mc4zz ^property[+].code = #searchable-PrAncCare01
* #w75KJ2mc4zz ^property[=].valueBoolean = false
* #w75KJ2mc4zz ^property[+].code = #searchable-nEenWmSyUEp
* #w75KJ2mc4zz ^property[=].valueBoolean = true
* #zDhUuAYrxNC "Last name (Play)"
* #zDhUuAYrxNC ^property[+].code = #value-type
* #zDhUuAYrxNC ^property[=].valueCode = #TEXT
* #zDhUuAYrxNC ^property[+].code = #unique
* #zDhUuAYrxNC ^property[=].valueBoolean = false
* #zDhUuAYrxNC ^property[+].code = #searchable
* #zDhUuAYrxNC ^property[=].valueBoolean = true
* #zDhUuAYrxNC ^property[+].code = #generated
* #zDhUuAYrxNC ^property[=].valueBoolean = false
* #zDhUuAYrxNC ^property[+].code = #display-in-list
* #zDhUuAYrxNC ^property[=].valueBoolean = true
* #zDhUuAYrxNC ^property[+].code = #searchable-PrAncCare01
* #zDhUuAYrxNC ^property[=].valueBoolean = false
* #zDhUuAYrxNC ^property[+].code = #searchable-nEenWmSyUEp
* #zDhUuAYrxNC ^property[=].valueBoolean = true
* #lZGmxYbs97q "Unique ID (Play)"
* #lZGmxYbs97q ^property[+].code = #dhis2-code
* #lZGmxYbs97q ^property[=].valueString = "MMD_PER_ID"
* #lZGmxYbs97q ^property[+].code = #value-type
* #lZGmxYbs97q ^property[=].valueCode = #TEXT
* #lZGmxYbs97q ^property[+].code = #unique
* #lZGmxYbs97q ^property[=].valueBoolean = true
* #lZGmxYbs97q ^property[+].code = #searchable
* #lZGmxYbs97q ^property[=].valueBoolean = false
* #lZGmxYbs97q ^property[+].code = #generated
* #lZGmxYbs97q ^property[=].valueBoolean = true
* #lZGmxYbs97q ^property[+].code = #pattern
* #lZGmxYbs97q ^property[=].valueString = "RANDOM(#######)"
* #lZGmxYbs97q ^property[+].code = #display-in-list
* #lZGmxYbs97q ^property[=].valueBoolean = false
* #lZGmxYbs97q ^property[+].code = #searchable-nEenWmSyUEp
* #lZGmxYbs97q ^property[=].valueBoolean = false

ValueSet: D2TEA_VS
Id: d2-tea-vs
Title: "DHIS2 tracked entity attributes"
Description: "DHIS2 tracked entity attributes captured by the generated tracker registration forms. Concept codes are DHIS2 tracked entity attribute UIDs."
* ^status = #draft
* ^experimental = true
* include codes from system D2TEA_CS
