// Generated by d2w fhir generate - do not edit

CodeSystem: D2TET_CS
Id: d2-tet-cs
Title: "DHIS2 tracked entity types"
Description: "DHIS2 tracked entity types the generated forms register an entity as. Concept codes are DHIS2 tracked entity type UIDs."
* ^status = #draft
* ^experimental = true
* ^content = #complete
* ^caseSensitive = true
* ^valueSet = Canonical(D2TET_VS)
* #nEenWmSyUEp "Person (Play)"

ValueSet: D2TET_VS
Id: d2-tet-vs
Title: "DHIS2 tracked entity types"
Description: "DHIS2 tracked entity types the generated forms register an entity as. Concept codes are DHIS2 tracked entity type UIDs."
* ^status = #draft
* ^experimental = true
* include codes from system D2TET_CS

// The resource each concept stands for, published so a consumer resolves it off the guide rather
// than off this project's fhir.toml, which states only the types that are not the default.
Instance: D2TET_CM
InstanceOf: ConceptMap
Title: "DHIS2 tracked entity types as FHIR resource types"
Description: "Every DHIS2 tracked entity type the generated forms register, mapped onto the FHIR resource type its registrations are published as. A type this project maps to nothing is a Patient."
Usage: #definition
* id = "d2-tet-cm"
* name = "D2TET_CM"
* status = #draft
* experimental = true
* sourceCanonical = Canonical(D2TET_VS)
* targetCanonical = "http://hl7.org/fhir/ValueSet/resource-types"
* group[0].source = "http://example.org/fhir/examples/event-program/CodeSystem/d2-tet-cs"
* group[0].target = "http://hl7.org/fhir/resource-types"
* group[0].element[0].code = #nEenWmSyUEp
* group[0].element[0].display = "Person (Play)"
* group[0].element[0].target[0].code = #Patient
* group[0].element[0].target[0].equivalence = #equal
