// Generated by d2w fhir generate - do not edit

Extension: D2AttributeValue
Id: d2-attribute-value
Title: "DHIS2 attribute value"
Description: "One DHIS2 attribute value: the attribute it belongs to, the code DHIS2 gave that attribute, and the value the object holds."
* ^status = #draft
* ^experimental = true
* ^context[+].type = #element
* ^context[=].expression = "Organization"
* ^context[+].type = #element
* ^context[=].expression = "Location"
* ^context[+].type = #element
* ^context[=].expression = "CodeSystem"
* ^context[+].type = #element
* ^context[=].expression = "ValueSet"
* ^context[+].type = #element
* ^context[=].expression = "Questionnaire"
* extension contains
    attributeId 1..1 and
    attributeCode 0..1 and
    value 1..1
* extension[attributeId] ^short = "The UID of the DHIS2 attribute the value belongs to."
* extension[attributeId].value[x] only string
* extension[attributeId].valueString 1..1
* extension[attributeCode] ^short = "The DHIS2 attribute's code, absent when the instance left it unset."
* extension[attributeCode].value[x] only string
* extension[value] ^short = "The value the DHIS2 object holds for the attribute, as DHIS2 sends it."
* extension[value].value[x] only string
* extension[value].valueString 1..1
