// Generated by d2w fhir generate - do not edit

Instance: D2CaptureServer
InstanceOf: CapabilityStatement
Title: "DHIS2 capture server"
Description: "The interactions a server capturing DHIS2 data as QuestionnaireResponses supports: one response created per request, against the aggregate, event, tracker registration, tracker event, or tracked entity response profile, plus read and search over the definitional resources a capture client resolves a form from."
Usage: #definition
* id = "d2-capture-server"
* name = "D2CaptureServer"
* status = #draft
* experimental = true
// R4 makes CapabilityStatement.date mandatory. A generated timestamp would rewrite the file on
// every run, so the date is pinned and regeneration stays byte-stable.
* date = "2026-01-01"
* kind = #requirements
* fhirVersion = #4.0.1
* format[+] = #json
* rest.mode = #server
* rest.documentation = "One QuestionnaireResponse per request: a capture client posts a single response per form submission, and the server accepts exactly one response per request."
* rest.resource[+].type = #QuestionnaireResponse
* rest.resource[=].interaction[+].code = #create
* rest.resource[=].supportedProfile[+] = Canonical(D2AggregateResponse)
* rest.resource[=].supportedProfile[+] = Canonical(D2EventResponse)
* rest.resource[=].supportedProfile[+] = Canonical(D2TrackerRegistrationResponse)
* rest.resource[=].supportedProfile[+] = Canonical(D2TrackerEventResponse)
* rest.resource[=].supportedProfile[+] = Canonical(D2TrackedEntityResponse)
* rest.resource[+].type = #Questionnaire
* rest.resource[=].interaction[+].code = #read
* rest.resource[=].interaction[+].code = #search-type
* rest.resource[+].type = #CodeSystem
* rest.resource[=].interaction[+].code = #read
* rest.resource[=].interaction[+].code = #search-type
* rest.resource[+].type = #ValueSet
* rest.resource[=].interaction[+].code = #read
* rest.resource[=].interaction[+].code = #search-type
* rest.resource[+].type = #Location
* rest.resource[=].interaction[+].code = #read
* rest.resource[=].interaction[+].code = #search-type
* rest.resource[+].type = #Organization
* rest.resource[=].interaction[+].code = #read
* rest.resource[=].interaction[+].code = #search-type
* rest.resource[+].type = #List
* rest.resource[=].interaction[+].code = #read
* rest.resource[=].interaction[+].code = #search-type
