// Generated by d2w fhir generate - do not edit

// The DHIS2 aggregate wire shape as a FHIR logical model. It is a description of what
// `/api/dataValueSets` accepts, not a resource anybody stores: it exists so a StructureMap has a
// target to name, and so the conversion contract is machine-readable rather than prose.
Logical: D2DataValueSet
Id: d2-data-value-set
Title: "DHIS2 data value set"
Description: "The `/api/dataValueSets` envelope one aggregate QuestionnaireResponse is imported as: the data set, the reporting period, the organisation unit, and the attribute option combo the report is keyed by, plus one data value per answered question. This is the DHIS2 wire shape stated in FHIR terms, so a map targeting it says where each DHIS2 field comes from."
* ^status = #draft
* ^experimental = true
* dataSet 1..1 string "Data set" "The DHIS2 data set the values are reported for, as its UID. It comes off the `$DHIS2-DS` identifier of the Questionnaire the response answers, never off the response itself."
* period 1..1 string "Reporting period" "The DHIS2 ISO period the values are reported for (e.g. `202401`), off the `iso` sub-extension of the response's reporting-period extension."
* orgUnit 1..1 string "Organisation unit" "The DHIS2 organisation unit the values are reported for, as its UID. It is the DHIS2 identifier of the published Location the response is subject to."
* attributeOptionCombo 0..1 string "Attribute option combo" "The DHIS2 attribute option combo the values are keyed under, as its UID. A data set on the default category combo carries none, and DHIS2 fills the field itself."
* completeDate 0..1 date "Complete date" "The day the report was completed, as a calendar date. It is the day the response records itself as authored, read in the project's own time zone."
* dataValues 0..* BackboneElement "Data values" "One cell of the report per answered question of the form."
* dataValues.dataElement 1..1 string "Data element" "The DHIS2 data element the cell reports, as its UID. It is the first segment of the answered question's link id."
* dataValues.categoryOptionCombo 0..1 string "Category option combo" "The DHIS2 category option combo the cell is disaggregated by, as its UID. It is the second segment of the answered question's link id, and a question asking an undisaggregated data element carries none."
* dataValues.value 1..1 string "Value" "The value as DHIS2 stores it. Every DHIS2 data value is a string on the wire, whatever the data element's value type, so a lexical decimal and a DHIS2 option code both survive the crossing byte for byte."
