// Generated by d2w fhir generate - do not edit

Extension: D2FormType
Id: d2-form-type
Title: "DHIS2 form type"
Description: "The kind of DHIS2 form a Questionnaire came from, carried on the responses captured against it."
* ^status = #draft
* ^experimental = true
* ^context[+].type = #element
* ^context[=].expression = "Questionnaire"
* ^context[+].type = #element
* ^context[=].expression = "QuestionnaireResponse"
* value[x] only code
* valueCode 1..1
* valueCode from D2FormType_VS (required)

CodeSystem: D2FormType_CS
Id: d2-form-type-cs
Title: "DHIS2 form types"
Description: "The DHIS2 form kinds a Questionnaire is generated from."
* ^status = #draft
* ^experimental = true
* ^content = #complete
* ^caseSensitive = true
* ^valueSet = Canonical(D2FormType_VS)
* #aggregate "Aggregate data set form"
* #event "Event program form"
* #tracker "Tracker registration form"
* #tracker-event "Tracker program stage form"
* #tracked-entity "Tracked entity type registration form"

ValueSet: D2FormType_VS
Id: d2-form-type-vs
Title: "DHIS2 form types"
Description: "The DHIS2 form kinds a Questionnaire is generated from."
* ^status = #draft
* ^experimental = true
* include codes from system D2FormType_CS
