// Generated by d2w fhir generate - do not edit

Instance: D2GenerateOperation
InstanceOf: OperationDefinition
Title: "Generate a synthetic response"
Description: "Generate one synthetic QuestionnaireResponse against a served Questionnaire: every question answered with a value its own type, bounds, and terminology binding admit, in the context its form kind's response profile requires. The generated response is immediately postable to the same server's QuestionnaireResponse endpoint, which is what a capture client's fill-with-test-data button and an API-driven stress corpus both need."
Usage: #definition
* id = "d2-generate"
* name = "D2GenerateOperation"
* status = #draft
* experimental = true
// R4 makes OperationDefinition.date optional, but a generated timestamp would rewrite the file
// on every run, so the date is pinned and regeneration stays byte-stable.
* date = "2026-08-01"
* kind = #operation
* affectsState = false
* code = #generate
* comment = "This is a custom operation, not SDC's $populate. $populate means fill this form from real context about a real subject; $generate invents data, and the two must never be confused."
* resource[+] = #Questionnaire
* system = false
* type = false
* instance = true
* parameter[+].name = #seed
* parameter[=].use = #in
* parameter[=].min = 0
* parameter[=].max = "1"
* parameter[=].type = #integer
* parameter[=].documentation = "The seed the generated values are drawn from. The same seed against the same served form returns the same response, so a client can reproduce a submission by naming its seed. Absent, the server draws one and states it on the generated response's identifier."
* parameter[+].name = #return
* parameter[=].use = #out
* parameter[=].min = 1
* parameter[=].max = "1"
* parameter[=].type = #QuestionnaireResponse
* parameter[=].documentation = "The generated QuestionnaireResponse, declaring the response profile of the form's own DHIS2 form kind and identified by the seed it was generated from."
