// Generated by d2w fhir generate - do not edit

Instance: D2OrgUnitIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 organisation unit UIDs"
Description: "The identifier system for DHIS2 organisation unit UIDs. Every generated artifact representing a DHIS2 organisation unit carries the source object's UID under this system."
Usage: #definition
* name = "D2OrgUnitIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/org-unit"
* uniqueId[0].preferred = true

Instance: D2OrgUnitCodeIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 organisation unit codes"
Description: "The identifier system for DHIS2 organisation unit codes. DHIS2 codes are optional, so this slot repeats the UID whenever the organisation unit has no code or its code is not a valid FHIR code."
Usage: #definition
* name = "D2OrgUnitCodeIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/org-unit-code"
* uniqueId[0].preferred = true

Instance: D2OptionSetIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 option set UIDs"
Description: "The identifier system for DHIS2 option set UIDs. Every generated artifact representing a DHIS2 option set carries the source object's UID under this system."
Usage: #definition
* name = "D2OptionSetIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/option-set"
* uniqueId[0].preferred = true

Instance: D2OptionSetCodeIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 option set codes"
Description: "The identifier system for DHIS2 option set codes. DHIS2 codes are optional, so this slot repeats the UID whenever the option set has no code or its code is not a valid FHIR code."
Usage: #definition
* name = "D2OptionSetCodeIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/option-set-code"
* uniqueId[0].preferred = true

Instance: D2OptionIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 option UIDs"
Description: "The identifier system for DHIS2 option UIDs. Every generated artifact representing a DHIS2 option carries the source object's UID under this system."
Usage: #definition
* name = "D2OptionIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/option"
* uniqueId[0].preferred = true

Instance: D2OptionCodeIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 option codes"
Description: "The identifier system for DHIS2 option codes. DHIS2 codes are optional, so this slot repeats the UID whenever the option has no code or its code is not a valid FHIR code."
Usage: #definition
* name = "D2OptionCodeIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/option-code"
* uniqueId[0].preferred = true

Instance: D2CategoryIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 category UIDs"
Description: "The identifier system for DHIS2 category UIDs. Every generated artifact representing a DHIS2 category carries the source object's UID under this system."
Usage: #definition
* name = "D2CategoryIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/category"
* uniqueId[0].preferred = true

Instance: D2CategoryCodeIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 category codes"
Description: "The identifier system for DHIS2 category codes. DHIS2 codes are optional, so this slot repeats the UID whenever the category has no code or its code is not a valid FHIR code."
Usage: #definition
* name = "D2CategoryCodeIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/category-code"
* uniqueId[0].preferred = true

Instance: D2CategoryOptionIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 category option UIDs"
Description: "The identifier system for DHIS2 category option UIDs. Every generated artifact representing a DHIS2 category option carries the source object's UID under this system."
Usage: #definition
* name = "D2CategoryOptionIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/category-option"
* uniqueId[0].preferred = true

Instance: D2CategoryOptionCodeIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 category option codes"
Description: "The identifier system for DHIS2 category option codes. DHIS2 codes are optional, so this slot repeats the UID whenever the category option has no code or its code is not a valid FHIR code."
Usage: #definition
* name = "D2CategoryOptionCodeIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/category-option-code"
* uniqueId[0].preferred = true

Instance: D2CategoryComboIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 category combo UIDs"
Description: "The identifier system for DHIS2 category combo UIDs. Every generated artifact representing a DHIS2 category combo carries the source object's UID under this system."
Usage: #definition
* name = "D2CategoryComboIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/category-combo"
* uniqueId[0].preferred = true

Instance: D2CategoryComboCodeIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 category combo codes"
Description: "The identifier system for DHIS2 category combo codes. DHIS2 codes are optional, so this slot repeats the UID whenever the category combo has no code or its code is not a valid FHIR code."
Usage: #definition
* name = "D2CategoryComboCodeIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/category-combo-code"
* uniqueId[0].preferred = true

Instance: D2DataSetIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 data set UIDs"
Description: "The identifier system for DHIS2 data set UIDs. Every generated artifact representing a DHIS2 data set carries the source object's UID under this system."
Usage: #definition
* name = "D2DataSetIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/data-set"
* uniqueId[0].preferred = true

Instance: D2DataSetCodeIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 data set codes"
Description: "The identifier system for DHIS2 data set codes. DHIS2 codes are optional, so this slot repeats the UID whenever the data set has no code or its code is not a valid FHIR code."
Usage: #definition
* name = "D2DataSetCodeIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/data-set-code"
* uniqueId[0].preferred = true

Instance: D2ProgramIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 program UIDs"
Description: "The identifier system for DHIS2 program UIDs. Every generated artifact representing a DHIS2 program carries the source object's UID under this system."
Usage: #definition
* name = "D2ProgramIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/program"
* uniqueId[0].preferred = true

Instance: D2ProgramCodeIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 program codes"
Description: "The identifier system for DHIS2 program codes. DHIS2 codes are optional, so this slot repeats the UID whenever the program has no code or its code is not a valid FHIR code."
Usage: #definition
* name = "D2ProgramCodeIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/program-code"
* uniqueId[0].preferred = true

Instance: D2DataElementIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 data element UIDs"
Description: "The identifier system for DHIS2 data element UIDs. Every generated artifact representing a DHIS2 data element carries the source object's UID under this system."
Usage: #definition
* name = "D2DataElementIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/data-element"
* uniqueId[0].preferred = true

Instance: D2DataElementCodeIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 data element codes"
Description: "The identifier system for DHIS2 data element codes. DHIS2 codes are optional, so this slot repeats the UID whenever the data element has no code or its code is not a valid FHIR code."
Usage: #definition
* name = "D2DataElementCodeIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/data-element-code"
* uniqueId[0].preferred = true

Instance: D2CategoryOptionComboIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 category option combo UIDs"
Description: "The identifier system for DHIS2 category option combo UIDs. Every generated artifact representing a DHIS2 category option combo carries the source object's UID under this system."
Usage: #definition
* name = "D2CategoryOptionComboIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/category-option-combo"
* uniqueId[0].preferred = true

Instance: D2CategoryOptionComboCodeIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 category option combo codes"
Description: "The identifier system for DHIS2 category option combo codes. DHIS2 codes are optional, so this slot repeats the UID whenever the category option combo has no code or its code is not a valid FHIR code."
Usage: #definition
* name = "D2CategoryOptionComboCodeIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/category-option-combo-code"
* uniqueId[0].preferred = true

Instance: D2ProgramStageIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 program stage UIDs"
Description: "The identifier system for DHIS2 program stage UIDs. Every generated artifact representing a DHIS2 program stage carries the source object's UID under this system."
Usage: #definition
* name = "D2ProgramStageIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/program-stage"
* uniqueId[0].preferred = true

Instance: D2ProgramStageCodeIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 program stage codes"
Description: "The identifier system for DHIS2 program stage codes. DHIS2 codes are optional, so this slot repeats the UID whenever the program stage has no code or its code is not a valid FHIR code."
Usage: #definition
* name = "D2ProgramStageCodeIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/program-stage-code"
* uniqueId[0].preferred = true

Instance: D2TrackedEntityTypeIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 tracked entity type UIDs"
Description: "The identifier system for DHIS2 tracked entity type UIDs. Every generated artifact representing a DHIS2 tracked entity type carries the source object's UID under this system."
Usage: #definition
* name = "D2TrackedEntityTypeIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/tracked-entity-type"
* uniqueId[0].preferred = true

Instance: D2TrackedEntityTypeCodeIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 tracked entity type codes"
Description: "The identifier system for DHIS2 tracked entity type codes. DHIS2 codes are optional, so this slot repeats the UID whenever the tracked entity type has no code or its code is not a valid FHIR code."
Usage: #definition
* name = "D2TrackedEntityTypeCodeIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/tracked-entity-type-code"
* uniqueId[0].preferred = true

Instance: D2TrackedEntityIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 tracked entity UIDs"
Description: "The identifier system for DHIS2 tracked entity UIDs. Every generated artifact representing a DHIS2 tracked entity carries the source object's UID under this system."
Usage: #definition
* name = "D2TrackedEntityIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/tracked-entity"
* uniqueId[0].preferred = true

Instance: D2TrackerEnrollmentIdentifierSystem
InstanceOf: NamingSystem
Title: "DHIS2 tracker enrollment UIDs"
Description: "The identifier system for DHIS2 tracker enrollment UIDs. Every generated artifact representing a DHIS2 tracker enrollment carries the source object's UID under this system."
Usage: #definition
* name = "D2TrackerEnrollmentIdentifierSystem"
* status = #draft
* kind = #identifier
* date = "2026-08-01"
* uniqueId[0].type = #uri
* uniqueId[0].value = "http://dhis2.org/fhir/id/tracker-enrollment"
* uniqueId[0].preferred = true
