// Generated by d2w fhir generate - do not edit

Extension: D2OriginalName
Id: d2-original-name
Title: "DHIS2 original name"
Description: "The name the DHIS2 instance holds for the object this resource publishes, stated where the run published that name in rewritten wording. A run under the substitute posture rewrites a name carrying a comparison character into the words it stands for, and this states the instance's own spelling beside it, so a consumer reading a rewritten name can search the instance on the name the instance answers to."
* ^status = #draft
* ^experimental = true
* ^context[+].type = #element
* ^context[=].expression = "CodeSystem"
* ^context[+].type = #element
* ^context[=].expression = "ValueSet"
* value[x] only string
* valueString 1..1
