// Generated by d2w fhir generate - do not edit

Profile: D2AggregateResponse
Parent: QuestionnaireResponse
Id: d2-aggregate-response
Title: "DHIS2 aggregate response"
Description: "One submission of a DHIS2 data set form: the values captured for one organisation unit, one reporting period, and one attribute option combo, answered on the linkIds of the data set's Questionnaire."
* ^status = #draft
* ^experimental = true
* extension contains
    D2Period named D2Period 1..1 and
    D2AttributeOptionCombo named D2AttributeOptionCombo 0..1 and
    D2FormType named D2FormType 1..1
* extension[D2Period] ^short = "The DHIS2 reporting period the values were captured for."
* extension[D2AttributeOptionCombo] ^short = "The DHIS2 attribute option combo the values were captured under. A response answering a form that declares a D2AttributeOptionCombos vocabulary has to carry it, coded from that ValueSet; absent means the default attribute option combo, which is the only combo a form without that extension has."
* extension[D2FormType] ^short = "The DHIS2 form kind this response answers."
* extension[D2FormType].valueCode = #aggregate (exactly)
* questionnaire 1..1
* subject 1..1
* subject only Reference(D2Location)

Profile: D2EventResponse
Parent: QuestionnaireResponse
Id: d2-event-response
Title: "DHIS2 event response"
Description: "One submission of a DHIS2 event program form: the values captured for one event at one organisation unit, answered on the linkIds of the event program's Questionnaire."
* ^status = #draft
* ^experimental = true
* extension contains D2FormType named D2FormType 1..1
* extension[D2FormType] ^short = "The DHIS2 form kind this response answers."
* extension[D2FormType].valueCode = #event (exactly)
* questionnaire 1..1
* subject 1..1
* subject only Reference(D2Location)
* authored 1..1

Profile: D2TrackerRegistrationResponse
Parent: QuestionnaireResponse
Id: d2-tracker-registration-response
Title: "DHIS2 tracker registration response"
Description: "One submission of a DHIS2 tracker program's registration form: the tracked entity attributes captured when a person is enrolled, answered on the linkIds of the program's Questionnaire. The response mints both DHIS2 identities it creates - the tracked entity it is subject to and the enrollment its extension names - so a client can capture the enrollment's first stage events in the same breath, before either identity exists on the instance. A response stating D2SubjectExists enrols a person the instance already holds instead, and then mints the enrollment alone."
* ^status = #draft
* ^experimental = true
* extension contains
    D2OrganisationUnit named D2OrganisationUnit 1..1 and
    D2TrackerEnrollment named D2TrackerEnrollment 1..1 and
    D2EnrolledAt named D2EnrolledAt 1..1 and
    D2IncidentAt named D2IncidentAt 0..1 and
    D2SubjectExists named D2SubjectExists 0..1 and
    D2FormType named D2FormType 1..1
* extension[D2OrganisationUnit] ^short = "The DHIS2 organisation unit the person is enrolled at, which becomes the organisation unit of both the tracked entity and the enrollment. A response naming a person the instance already holds does not move that person: the organisation unit is the enrollment's alone."
* extension[D2TrackerEnrollment] ^short = "The DHIS2 enrollment this registration creates. The client mints the value as a DHIS2 UID - eleven characters, the first a letter - so the response names the enrollment its own stage responses will be captured against before any of them is sent."
* extension[D2EnrolledAt] ^short = "When the enrollment begins."
* extension[D2IncidentAt] ^short = "When the incident the enrollment follows occurred. Carried by a response to a form whose program collects one, and absent otherwise."
* extension[D2SubjectExists] ^short = "Whether the person this response is subject to is already held by the DHIS2 instance. True means the subject identifier names an existing tracked entity and the response enrols that person, so it is imported as an enrollment on its own. Absent or false means the client minted the subject identifier and the response creates the person along with the enrollment. A response stating true answers only the questions the program asks: an answer belonging to the person's own record cannot ride an enrollment, and rewriting the record of a person this contract does not own is not something an enrollment does."
* extension[D2FormType] ^short = "The DHIS2 form kind this response answers."
* extension[D2FormType].valueCode = #tracker (exactly)
* questionnaire 1..1
* subject 1..1
* subject only Reference(Patient)
* subject.identifier 1..1
* subject.identifier.system 1..1
* subject.identifier.system = "http://dhis2.org/fhir/id/tracked-entity" (exactly)
* subject.identifier.value 1..1
* subject ^short = "The DHIS2 tracked entity this registration enrols, named by identifier rather than by reference: this guide publishes no Patient resource, so the identifier is the person. The client mints the value as a DHIS2 UID, the same way it mints the enrollment - unless the response carries D2SubjectExists as true, and the value is then the UID of a person the instance already holds."
* authored 1..1

Profile: D2TrackerEventResponse
Parent: QuestionnaireResponse
Id: d2-tracker-event-response
Title: "DHIS2 tracker event response"
Description: "One submission of a DHIS2 tracker program stage form: the values captured for one event of one enrollment, answered on the linkIds of the stage's Questionnaire and subject to the tracked entity by identifier."
* ^status = #draft
* ^experimental = true
* extension contains
    D2OrganisationUnit named D2OrganisationUnit 1..1 and
    D2TrackerEnrollment named D2TrackerEnrollment 1..1 and
    D2FormType named D2FormType 1..1
* extension[D2OrganisationUnit] ^short = "The DHIS2 organisation unit the event was captured at."
* extension[D2TrackerEnrollment] ^short = "The DHIS2 tracker enrollment the event belongs to."
* extension[D2FormType] ^short = "The DHIS2 form kind this response answers."
* extension[D2FormType].valueCode = #tracker-event (exactly)
* questionnaire 1..1
* subject 1..1
* subject only Reference(Patient)
* subject.identifier 1..1
* subject.identifier.system 1..1
* subject.identifier.system = "http://dhis2.org/fhir/id/tracked-entity" (exactly)
* subject.identifier.value 1..1
* authored 1..1

Profile: D2TrackedEntityResponse
Parent: QuestionnaireResponse
Id: d2-tracked-entity-response
Title: "DHIS2 tracked entity response"
Description: "One submission of a DHIS2 tracked entity type's registration form: the attributes the type itself collects, captured when a person is registered without being enrolled in any program. The response mints the tracked entity it creates, and names no enrollment at all - there is none, which is the whole point of the form."
* ^status = #draft
* ^experimental = true
* extension contains
    D2OrganisationUnit named D2OrganisationUnit 1..1 and
    D2FormType named D2FormType 1..1
* extension[D2OrganisationUnit] ^short = "The DHIS2 organisation unit the subject is registered at, which becomes the organisation unit of the tracked entity."
* extension[D2FormType] ^short = "The DHIS2 form kind this response answers."
* extension[D2FormType].valueCode = #tracked-entity (exactly)
* questionnaire 1..1
* subject 1..1
* subject only Reference(Patient)
* subject.identifier 1..1
* subject.identifier.system 1..1
* subject.identifier.system = "http://dhis2.org/fhir/id/tracked-entity" (exactly)
* subject.identifier.value 1..1
* subject ^short = "The DHIS2 tracked entity this registration creates, named by identifier rather than by reference: this guide publishes no Patient resource, so the identifier is the person. The client mints the value as a DHIS2 UID, and nothing on the instance holds it until this response is imported."
* authored 1..1
