// Generated by d2w fhir generate - do not edit

Extension: D2TrackerEnrollment
Id: d2-tracker-enrollment
Title: "DHIS2 tracker enrollment"
Description: "The DHIS2 tracker enrollment a response belongs to, carried as the enrollment UID. A registration response mints the UID of the enrollment it creates; an event response names the enrollment it was captured under."
* ^status = #draft
* ^experimental = true
* ^context[+].type = #element
* ^context[=].expression = "QuestionnaireResponse"
* value[x] only Identifier
* valueIdentifier 1..1
* valueIdentifier.system 1..1
* valueIdentifier.system = "http://dhis2.org/fhir/id/tracker-enrollment" (exactly)
* valueIdentifier.value 1..1
