// Generated by d2w fhir generate - do not edit

Instance: QuestionnaireResponse-EVTsupVis01-example-1
InstanceOf: D2EventResponse
Title: "Example response - Supervision visit"
Description: "Example QuestionnaireResponse against the DHIS2 event program Supervision visit (EVTsupVis01)."
Usage: #example
* id = "EVTsupVis01-example-1"
* extension[D2FormType].valueCode = #event
* questionnaire = "http://example.org/fhir/examples/aggregate-minimal/Questionnaire/EVTsupVis01"
* status = #completed
* subject = Reference(Location/ImspTQPwCqd)
* authored = "2026-08-08T16:00:00Z"
* item[+].linkId = "s46m5MS0hxu"
* item[=].answer[+].valueInteger = 148
* item[+].linkId = "YtbsuPPo010"
* item[=].answer[+].valueDecimal = 40.9
