// Generated by d2w fhir generate - do not edit

Instance: QuestionnaireResponse-PrAncCare01-example-1
InstanceOf: D2TrackerRegistrationResponse
Title: "Example response - ANC follow-up"
Description: "Example QuestionnaireResponse against the DHIS2 tracker program registration ANC follow-up (PrAncCare01)."
Usage: #example
* id = "PrAncCare01-example-1"
* extension[D2FormType].valueCode = #tracker
* extension[D2TrackerEnrollment].valueIdentifier.system = $DHIS2-TRACKER-ENROLLMENT
* extension[D2TrackerEnrollment].valueIdentifier.value = "YSPp2WlJf2N"
* extension[D2OrganisationUnit].valueReference = Reference(Location/PMa2VCrupOd)
* extension[D2EnrolledAt].valueDateTime = "2026-08-05T03:00:00Z"
* questionnaire = "http://example.org/fhir/examples/aggregate-minimal/Questionnaire/PrAncCare01"
* status = #completed
* subject.type = "Patient"
* subject.identifier.system = $DHIS2-TE
* subject.identifier.value = "iFN8bM7fEC3"
* authored = "2026-08-03T16:00:00Z"
* item[+].linkId = "w75KJ2mc4zz"
* item[=].answer[+].valueString = "Example First name (Play)"
* item[+].linkId = "zDhUuAYrxNC"
* item[=].answer[+].valueString = "Example Last name (Play)"
