// Generated by d2w fhir generate - do not edit

Instance: QuestionnaireResponse-TuL8IOPzpHh-example-1
InstanceOf: D2AggregateResponse
Title: "Example response - EPI Stock"
Description: "Example QuestionnaireResponse against the DHIS2 data set EPI Stock (TuL8IOPzpHh)."
Usage: #example
* id = "TuL8IOPzpHh-example-1"
* extension[D2FormType].valueCode = #aggregate
* extension[D2Period].extension[iso].valueString = "202607"
* extension[D2Period].extension[type].valueCode = #Monthly
* extension[D2Period].extension[period].valuePeriod.start = "2026-07-01"
* extension[D2Period].extension[period].valuePeriod.end = "2026-07-31"
* extension[D2AttributeOptionCombo].valueCoding = D2AOC_idcDPkDtepR_CS#oawMLLH7OjA "Provide access to basic education"
* questionnaire = "http://example.org/fhir/examples/aggregate-minimal/Questionnaire/TuL8IOPzpHh"
* status = #completed
* subject = Reference(Location/ImspTQPwCqd)
* item[+].linkId = "cZnQDuF3IDz"
* item[=].item[+].linkId = "cZnQDuF3IDz.fsFN9T4ck3E"
* item[=].item[=].answer[+].valueDecimal = 76.8
* item[=].item[+].linkId = "cZnQDuF3IDz.pn1upwnbxfn"
* item[=].item[=].answer[+].valueDecimal = 78.2
* item[=].item[+].linkId = "cZnQDuF3IDz.TxaWpw1pN5G"
* item[=].item[=].answer[+].valueDecimal = 9.1
* item[+].linkId = "FvKdfA2SuWI"
* item[=].item[+].linkId = "FvKdfA2SuWI.fsFN9T4ck3E"
* item[=].item[=].answer[+].valueDecimal = 56.7
* item[=].item[+].linkId = "FvKdfA2SuWI.pn1upwnbxfn"
* item[=].item[=].answer[+].valueDecimal = 38.0
* item[=].item[+].linkId = "FvKdfA2SuWI.TxaWpw1pN5G"
* item[=].item[=].answer[+].valueDecimal = 38.8
* item[+].linkId = "WVrH6j3Wfye"
* item[=].item[+].linkId = "WVrH6j3Wfye.fsFN9T4ck3E"
* item[=].item[=].answer[+].valueDecimal = 6.1
* item[=].item[+].linkId = "WVrH6j3Wfye.pn1upwnbxfn"
* item[=].item[=].answer[+].valueDecimal = 15.7
* item[=].item[+].linkId = "WVrH6j3Wfye.TxaWpw1pN5G"
* item[=].item[=].answer[+].valueDecimal = 97.4
* item[+].linkId = "p1MDHOT6ENy"
* item[=].answer[+].valueDecimal = 29.3
* item[+].linkId = "lVknokmR4Ip"
* item[=].answer[+].valueDecimal = 56.7
* item[+].linkId = "FTINmL2lehN"
* item[=].answer[+].valueDecimal = 29.7
* item[+].linkId = "axVhq1itoQD"
* item[=].answer[+].valueDecimal = 90.8
* item[+].linkId = "XNrjXqZrHD8"
* item[=].answer[+].valueDecimal = 86.7
* item[+].linkId = "nGCLjZDn0Q4"
* item[=].answer[+].valueDecimal = 16.8
* item[+].linkId = "t99PL3gUxIl"
* item[=].answer[+].valueDecimal = 17.8
* item[+].linkId = "vEAo4KwsAzl"
* item[=].answer[+].valueDecimal = 33.0
* item[+].linkId = "iuSIObmKutb"
* item[=].answer[+].valueDecimal = 5.9
