// Generated by d2w fhir generate - do not edit

Instance: D2OrganizationExample
InstanceOf: D2Organization
Title: "Example DHIS2 Organization - Kambia (PMa2VCrupOd)"
Description: "A worked D2Organization: DHIS2 organisation unit Kambia (PMa2VCrupOd) as the legal entity, carrying both DHIS2 identifiers and its hierarchy level."
Usage: #example
* id = "d2-organization-example"
* identifier[dhis2id].system = $DHIS2-OU
* identifier[dhis2id].value = "PMa2VCrupOd"
* identifier[dhis2code].system = $DHIS2-OU-CODE
* identifier[dhis2code].value = "OU_211212"
* active = true
* name = "Kambia"
* type = D2OU_Level_CS#level-2 "Level 2"

Instance: D2LocationExample
InstanceOf: D2Location
Title: "Example DHIS2 Location - Kambia (PMa2VCrupOd)"
Description: "A worked D2Location: DHIS2 organisation unit Kambia (PMa2VCrupOd) as the physical place, managed by the D2Organization of the same unit."
Usage: #example
* id = "d2-location-example"
* identifier[dhis2id].system = $DHIS2-OU
* identifier[dhis2id].value = "PMa2VCrupOd"
* identifier[dhis2code].system = $DHIS2-OU-CODE
* identifier[dhis2code].value = "OU_211212"
* status = #active
* name = "Kambia"
* description = "A worked D2Location: DHIS2 organisation unit Kambia (PMa2VCrupOd) as the physical place, managed by the D2Organization of the same unit."
* position.longitude = -12.805049
* position.latitude = 9.183654
* extension[level].valueCoding = D2OU_Level_CS#level-2 "Level 2"
* managingOrganization = Reference(D2OrganizationExample)
