// Generated by d2w fhir generate - do not edit

Extension: D2AttributeOptionCombos
Id: d2-attribute-option-combos
Title: "DHIS2 attribute option combos"
Description: "The attribute option combos a form's responses may be keyed under, as the canonical of the ValueSet publishing them. Absent means the form's data set rides the default category combo, and its responses carry no D2AttributeOptionCombo extension."
* ^status = #draft
* ^experimental = true
* ^context[+].type = #element
* ^context[=].expression = "Questionnaire"
* value[x] only Canonical(ValueSet)
* valueCanonical 1..1
