// Generated by d2w fhir generate - do not edit

Extension: D2Description
Id: d2-description
Title: "DHIS2 description"
Description: "The free text a DHIS2 instance holds about the object a question or a group is asked from - the description of a data element, of a tracked entity attribute, or of a form section. It is guidance for the person filling the form, which is why it rides the item rather than the item's text, and it is present only where the instance states one."
* ^status = #draft
* ^experimental = true
* ^context[+].type = #element
* ^context[=].expression = "Questionnaire.item"
* value[x] only string
* valueString 1..1
