// Generated by d2w fhir generate - do not edit

Extension: D2EntityLevel
Id: d2-entity-level
Title: "DHIS2 entity level"
Description: "Whether a registration question's answer belongs to the tracked entity itself - true for a tracked entity attribute of the program's tracked entity type, false for an attribute only the program asks, whose answer belongs to the enrollment."
* ^status = #draft
* ^experimental = true
* ^context[+].type = #element
* ^context[=].expression = "Questionnaire.item"
* value[x] only boolean
* valueBoolean 1..1
