// Generated by d2w fhir generate - do not edit

Extension: D2EnrolledAt
Id: d2-enrolled-at
Title: "DHIS2 enrollment date"
Description: "The moment a DHIS2 tracker enrollment began - the enrolledAt of the enrollment a registration response creates."
* ^status = #draft
* ^experimental = true
* ^context[+].type = #element
* ^context[=].expression = "QuestionnaireResponse"
* value[x] only dateTime
* valueDateTime 1..1

Extension: D2IncidentAt
Id: d2-incident-at
Title: "DHIS2 incident date"
Description: "The moment the incident a DHIS2 tracker enrollment follows occurred - the occurredAt of the enrollment. A registration form states on D2CollectsIncidentDate whether its program collects one, and a response to a form declaring false carries none."
* ^status = #draft
* ^experimental = true
* ^context[+].type = #element
* ^context[=].expression = "QuestionnaireResponse"
* value[x] only dateTime
* valueDateTime 1..1

Extension: D2CollectsIncidentDate
Id: d2-collects-incident-date
Title: "DHIS2 program collects an incident date"
Description: "Whether the DHIS2 tracker program a registration form enrols a person into collects the date of the incident the enrollment follows. True means every enrollment the program creates states that date and a response to this form carries D2IncidentAt; false means the program collects none and a response carries none. Only a registration form declares it, because only a program has enrollments."
* ^status = #draft
* ^experimental = true
* ^context[+].type = #element
* ^context[=].expression = "Questionnaire"
* value[x] only boolean
* valueBoolean 1..1
