// Generated by d2w fhir generate - do not edit

Extension: D2OrganisationUnit
Id: d2-organisation-unit
Title: "DHIS2 organisation unit"
Description: "The DHIS2 organisation unit an event was captured at, as a reference to the unit's Location."
* ^status = #draft
* ^experimental = true
* ^context[+].type = #element
* ^context[=].expression = "QuestionnaireResponse"
* value[x] only Reference(D2Location)
* valueReference 1..1
