// Generated by d2w fhir generate - do not edit

Extension: D2Period
Id: d2-period
Title: "DHIS2 reporting period"
Description: "A DHIS2 reporting period: its ISO identifier, its period type, and the dates it covers."
* ^status = #draft
* ^experimental = true
* ^context[+].type = #element
* ^context[=].expression = "QuestionnaireResponse"
* ^context[+].type = #element
* ^context[=].expression = "MeasureReport"
* extension contains
    iso 1..1 and
    type 1..1 and
    period 0..1
* extension[iso] ^short = "The DHIS2 ISO period identifier (e.g. 202401)."
* extension[iso].value[x] only string
* extension[iso].valueString 1..1
* extension[type] ^short = "The DHIS2 period type this identifier is expressed in."
* extension[type].value[x] only code
* extension[type].valueCode 1..1
* extension[type].valueCode from D2PeriodType_VS (required)
* extension[period] ^short = "The date range the ISO period resolves to."
* extension[period].value[x] only Period

Extension: D2PeriodType
Id: d2-period-type
Title: "DHIS2 period type"
Description: "The DHIS2 period type an aggregate form is reported under - the reporting frequency of the data set the Questionnaire was generated from. A response to the form states one period of this type on D2Period, so a client knows which ISO period format the instance accepts before it builds one. Only an aggregate form declares it, because only a data set has a reporting frequency."
* ^status = #draft
* ^experimental = true
* ^context[+].type = #element
* ^context[=].expression = "Questionnaire"
* value[x] only code
* valueCode 1..1
* valueCode from D2PeriodType_VS (required)

CodeSystem: D2PeriodType_CS
Id: d2-period-type-cs
Title: "DHIS2 period types"
Description: "The period types DHIS2 registers, each with the ISO period format it is written in."
* ^status = #draft
* ^experimental = true
* ^content = #complete
* ^caseSensitive = true
* ^valueSet = Canonical(D2PeriodType_VS)
* #Daily "Daily (yyyyMMdd)"
* #Weekly "Weekly (yyyyWn)"
* #WeeklyWednesday "WeeklyWednesday (yyyyWedWn)"
* #WeeklyThursday "WeeklyThursday (yyyyThuWn)"
* #WeeklyFriday "WeeklyFriday (yyyyFriWn)"
* #WeeklySaturday "WeeklySaturday (yyyySatWn)"
* #WeeklySunday "WeeklySunday (yyyySunWn)"
* #BiWeekly "BiWeekly (yyyyBiWn)"
* #Monthly "Monthly (yyyyMM)"
* #BiMonthly "BiMonthly (yyyyMMB)"
* #Quarterly "Quarterly (yyyyQn)"
* #QuarterlyNov "QuarterlyNov (yyyyNovQn)"
* #SixMonthly "SixMonthly (yyyySn)"
* #SixMonthlyApril "SixMonthlyApril (yyyyAprilSn)"
* #SixMonthlyNov "SixMonthlyNov (yyyyNovSn)"
* #Yearly "Yearly (yyyy)"
* #FinancialFeb "FinancialFeb (yyyyFeb)"
* #FinancialApril "FinancialApril (yyyyApril)"
* #FinancialJuly "FinancialJuly (yyyyJuly)"
* #FinancialAug "FinancialAug (yyyyAug)"
* #FinancialSep "FinancialSep (yyyySep)"
* #FinancialOct "FinancialOct (yyyyOct)"
* #FinancialNov "FinancialNov (yyyyNov)"

ValueSet: D2PeriodType_VS
Id: d2-period-type-vs
Title: "DHIS2 period types"
Description: "The period types DHIS2 registers, each with the ISO period format it is written in."
* ^status = #draft
* ^experimental = true
* include codes from system D2PeriodType_CS
