// Generated by d2w fhir generate - do not edit

Extension: D2TrackedEntityAttributeValue
Id: d2-tracked-entity-attribute-value
Title: "DHIS2 tracked entity attribute value"
Description: "One DHIS2 tracked entity attribute value: the attribute it answers, the code DHIS2 gave that attribute, and the value the tracked entity holds. A value of an attribute DHIS2 declares unique is an identifier instead and does not appear here."
* ^status = #draft
* ^experimental = true
* ^context[+].type = #element
* ^context[=].expression = "Patient"
* extension contains
    attributeId 1..1 and
    attributeCode 0..1 and
    value 1..1
* extension[attributeId] ^short = "The UID of the DHIS2 tracked entity attribute the value answers."
* extension[attributeId].value[x] only string
* extension[attributeId].valueString 1..1
* extension[attributeCode] ^short = "The tracked entity attribute's code, absent when the instance left it unset."
* extension[attributeCode].value[x] only string
* extension[value] ^short = "The value the tracked entity holds for the attribute, as DHIS2 sends it."
* extension[value].value[x] only string
* extension[value].valueString 1..1
