// Generated by d2w fhir generate - do not edit

Instance: Questionnaire-PrAncCare01
InstanceOf: Questionnaire
Title: "Questionnaire - ANC follow-up"
Description: "DHIS2 tracker program ANC follow-up (PrAncCare01) as a registration form: the tracked entity attributes captured when a person is enrolled in the program."
Usage: #definition
* id = "PrAncCare01"
* extension[D2FormType].valueCode = #tracker
* extension[D2CollectsIncidentDate].valueBoolean = false
* extension[D2OrganisationUnitAssignment].valueReference = Reference(List/d2-pr-PrAncCare01-org-units)
* url = "http://example.org/fhir/examples/aggregate-minimal/Questionnaire/PrAncCare01"
* identifier[+].system = $DHIS2-PROGRAM
* identifier[=].value = "PrAncCare01"
* identifier[+].system = $DHIS2-PROGRAM-CODE
* identifier[=].value = "PrAncCare01"
* identifier[+].system = $DHIS2-TET
* identifier[=].value = "nEenWmSyUEp"
* name = "D2PR_PrAncCare01"
* title = "ANC follow-up"
* description = "DHIS2 tracker program ANC follow-up (PrAncCare01) as a registration form: the tracked entity attributes captured when a person is enrolled in the program."
* status = #draft
* experimental = true
* subjectType = #Patient
* code = D2FormType_CS#tracker
* item[+].linkId = "w75KJ2mc4zz"
* item[=].code = D2TEA_CS#w75KJ2mc4zz "First name (Play)"
* item[=].text = "First name (Play)"
* item[=].type = #string
* item[=].extension[+].url = "http://example.org/fhir/examples/aggregate-minimal/StructureDefinition/d2-description"
* item[=].extension[=].valueString = "First name"
* item[=].extension[+].url = "http://example.org/fhir/examples/aggregate-minimal/StructureDefinition/d2-entity-level"
* item[=].extension[=].valueBoolean = true
* item[+].linkId = "zDhUuAYrxNC"
* item[=].code = D2TEA_CS#zDhUuAYrxNC "Last name (Play)"
* item[=].text = "Last name (Play)"
* item[=].type = #string
* item[=].extension[+].url = "http://example.org/fhir/examples/aggregate-minimal/StructureDefinition/d2-description"
* item[=].extension[=].valueString = "Last name"
* item[=].extension[+].url = "http://example.org/fhir/examples/aggregate-minimal/StructureDefinition/d2-entity-level"
* item[=].extension[=].valueBoolean = true
