// Generated by d2w fhir generate - do not edit

Instance: QuestionnaireResponse-lxAQ7Zs9VYR-example-1
InstanceOf: D2EventResponse
Title: "Example response - Antenatal care visit"
Description: "Example QuestionnaireResponse against the DHIS2 event program Antenatal care visit (lxAQ7Zs9VYR)."
Usage: #example
* id = "lxAQ7Zs9VYR-example-1"
* extension[D2FormType].valueCode = #event
* questionnaire = "http://example.org/fhir/examples/event-program/Questionnaire/lxAQ7Zs9VYR"
* status = #completed
* subject = Reference(Location/ImspTQPwCqd)
* authored = "2026-07-25T12:00:00Z"
* item[+].linkId = "sWoqcoByYmD"
* item[=].answer[+].valueBoolean = false
* item[+].linkId = "Ok9OQpitjQr"
* item[=].answer[+].valueBoolean = true
* item[+].linkId = "vANAXwtLwcT"
* item[=].answer[+].valueDecimal = 68.8
