// Generated by d2w fhir generate - do not edit

Instance: QuestionnaireResponse-nEenWmSyUEp-example-1
InstanceOf: D2TrackedEntityResponse
Title: "Example response - Person (Play)"
Description: "Example QuestionnaireResponse against the DHIS2 tracked entity type registration Person (Play) (nEenWmSyUEp)."
Usage: #example
* id = "nEenWmSyUEp-example-1"
* extension[D2FormType].valueCode = #tracked-entity
* extension[D2OrganisationUnit].valueReference = Reference(Location/bL4ooGhyHRQ)
* questionnaire = "http://example.org/fhir/examples/event-program/Questionnaire/nEenWmSyUEp"
* status = #completed
* subject.type = "Patient"
* subject.identifier.system = $DHIS2-TE
* subject.identifier.value = "SwMn9pN9cTo"
* authored = "2026-08-09T14:00:00Z"
* item[+].linkId = "w75KJ2mc4zz"
* item[=].answer[+].valueString = "Example First name (Play)"
* item[+].linkId = "zDhUuAYrxNC"
* item[=].answer[+].valueString = "Example Last name (Play)"
* item[+].linkId = "lZGmxYbs97q"
* item[=].answer[+].valueString = "Unique ID (Play) SwMn9pN9cTo"
