// Generated by d2w fhir generate - do not edit

Instance: QuestionnaireResponse-PsAncVisit1-example-1
InstanceOf: D2TrackerEventResponse
Title: "Example response - ANC follow-up - ANC visit"
Description: "Example QuestionnaireResponse against the DHIS2 tracker program stage ANC follow-up - ANC visit (PsAncVisit1)."
Usage: #example
* id = "PsAncVisit1-example-1"
* extension[D2FormType].valueCode = #tracker-event
* extension[D2TrackerEnrollment].valueIdentifier.system = $DHIS2-TRACKER-ENROLLMENT
* extension[D2TrackerEnrollment].valueIdentifier.value = "OQ2lVDfpXUh"
* extension[D2OrganisationUnit].valueReference = Reference(Location/bL4ooGhyHRQ)
* questionnaire = "http://example.org/fhir/examples/event-program/Questionnaire/PsAncVisit1"
* status = #completed
* subject.type = "Patient"
* subject.identifier.system = $DHIS2-TE
* subject.identifier.value = "V8wvAX80riZ"
* authored = "2026-08-08T15:00:00Z"
* item[+].linkId = "DeAncVisNo1"
* item[=].answer[+].valueInteger = 777
* item[+].linkId = "DeAncBpSys1"
* item[=].answer[+].valueInteger = 848
* item[+].linkId = "DeAncDanger"
* item[=].answer[+].valueBoolean = false
