/**
 * A stored receipt read back as what it answered - the join between a spool row and a form.
 *
 * WHY THIS IS ITS OWN MODULE. lib/spool.ts is the receipt envelope and nothing else; lib/fhir.ts
 * is the R4 wire shapes and nothing else; lib/questionnaire.ts is the fill side, which reads a
 * form in order to write answers; lib/answers.ts reads one `value[x]` back as a value a screen
 * shows. This is the join, and it is the one place all of them meet: a `SpoolResponseSummary` says
 * which canonical a receipt answered, the served `Questionnaire` says what that form asks and in
 * which order, and the stored `QuestionnaireResponse` says what was answered. None of those
 * modules can join them without importing one of the others, so the join lives here.
 *
 * WHY THE QUESTIONNAIRE IS A SEPARATE READ, AND WHY IT MAY BE MISSING. A receipt is a fact
 * about a submission; the question texts are a fact about the guide, and the guide can be
 * recompiled between the capture and the reading. So the answers are rendered from the receipt
 * and *labelled* from whatever form is served now - and when that form is gone, or has dropped a
 * question the receipt still carries, the answer is still shown against its link id rather than
 * disappearing. A receipt that renders as a blank page because its form was rebuilt is the one
 * failure this module exists to prevent.
 *
 * Everything here is pure. The reads happen in the page.
 */

import { answerValue, type AnswerValue } from '@/lib/answers'
import { attributeOptionComboLabel, attributeOptionComboOf, canonicalId, conceptDisplay, enrolledAtOf, incidentAtOf, trackedEntityOf, trackerEnrollmentOf, type CodeSystem, type Questionnaire, type QuestionnaireResponse, type QuestionnaireResponseItem } from '@/lib/fhir'
import { DEFAULT_DATE_LABELS, type DateLabels, type ProgramRule, type QuestionnaireSpec } from '@/lib/questionnaire'
import { formatInstant, TRACKED_ENTITY_FACT_LABEL, TRACKER_ENROLLMENT_FACT_LABEL, type SpoolRejectionIssue, type SpoolResponseSummary } from '@/lib/spool'

/**
 * The DHIS2 error code a rejection carries when a program rule refused the import.
 *
 * DHIS2 answers a tracker import that breaks a rule with this and nothing else: no other code names
 * a program rule, so the code alone is what says a row is about one.
 */
export const PROGRAM_RULE_ERROR_CODE = 'E1300'

/**
 * The rule uid a DHIS2 rejection row names, or null when it names none.
 *
 * THE MESSAGE, AND NOT THE SUBJECT. DHIS2 writes the rule into its own sentence - "Generated by
 * ProgramRule (`dahuKlP7jR2`) - ..." - and that is the one place on the row where a uid is stated
 * to be a rule. The `subject` of an `E1300` is the *data element* the rule was about, and it is
 * DHIS2-uid shaped like everything else, so a reader that took it would name the wrong object with
 * full confidence. It is read in `rejectionRuleName` instead, and only when the served form lists
 * it as a rule - which is the form vouching for it rather than a shape being mistaken for a fact.
 *
 * Only a row whose code is `E1300` is read at all. Every other DHIS2 error names a different kind
 * of object, and a uid pulled out of one of those would be a coincidence rendered as a fact.
 */
export function programRuleUidOf(issue: SpoolRejectionIssue): string | null {
    if (issue.error_code !== PROGRAM_RULE_ERROR_CODE) return null
    return PROGRAM_RULE_MESSAGE_PATTERN.exec(issue.message ?? '')?.[1] ?? null
}

/**
 * What one refused-import row is about, with the rule it names read back as that rule's own name.
 *
 * THE NAME IS THE WHOLE POINT. `dahuKlP7jR2` is a uid nobody recognises, and the served form lists
 * every rule its instance enforces with the name a DHIS2 configurer gave it - so the join turns
 * "your submission broke rule dahuKlP7jR2" into "your submission broke: The haemoglobin value
 * cannot be above 99". The uid stays beside it, because it is the string to type into DHIS2.
 *
 * A rule the served form does not list stays unnamed rather than guessed at - a form recompiled
 * since the capture, or a rule added to the instance afterwards, are both ordinary - and the row
 * still renders everything DHIS2 said about it.
 */
export function rejectionRuleName(issue: SpoolRejectionIssue, rules: ProgramRule[]): string | null {
    if (issue.error_code !== PROGRAM_RULE_ERROR_CODE) return null
    const named = programRuleUidOf(issue)
    // The subject is only read as a rule when the form lists it as one. On most `E1300` rows it is
    // the data element the rule was about, and naming that as the rule would be worse than silence.
    const ruleUid = named ?? issue.subject ?? ''
    return rules.find((rule) => rule.ruleUid === ruleUid)?.name ?? null
}

/** How DHIS2 spells the rule inside an `E1300` message - a backquoted uid after `ProgramRule`. */
const PROGRAM_RULE_MESSAGE_PATTERN = /ProgramRule\s*\(\s*`?([A-Za-z][A-Za-z0-9]{10})`?\s*\)/

/** One capture warning, with the questions it named read back as the form asks them. */
export interface NamedCaptureWarning {
    /** The validator's own sentence, with each recognised link id replaced by its question text. */
    text: string
    /** The link ids the sentence named, in the order it named them - kept beside it as chips. */
    linkIds: string[]
}

/**
 * One capture warning with its link ids named.
 *
 * THE UID IS NOT THE QUESTION. The capture validator quotes the link id it is speaking about -
 * "`eMyVanycQSC` is required by the form and was not answered" - because a link id is the only
 * handle it has: it validates a document against a profile and never reads the form. The person
 * opening the receipt did read the form, and what they need is "Date of birth". So the served
 * Questionnaire is asked what each quoted link id is called, and the sentence is rendered in the
 * form's own words.
 *
 * THE UID STAYS. It is the string to search a receipt, a log line, or DHIS2 itself for, and it
 * moves out of the sentence into a chip of its own rather than being dropped. A link id the served
 * form knows nothing about - a form recompiled since the capture - is left in the sentence exactly
 * as the validator wrote it, because a name this UI cannot vouch for is worse than the uid.
 */
export function namedCaptureWarning(
    warning: string,
    questions: ReadonlyMap<string, string>,
): NamedCaptureWarning {
    const linkIds: string[] = []
    const text = warning.replace(/`([^`]+)`/g, (quoted, inner: string) => {
        const named = questions.get(inner)
        if (named === undefined || named.trim() === '') return quoted
        if (!linkIds.includes(inner)) linkIds.push(inner)
        return named
    })
    return { text, linkIds }
}

/** One answered question of a receipt, joined to the question the form asks. */
export interface ReceiptAnswerRow {
    linkId: string
    /** The question as the served form asks it, unescaped; null when no form states one. */
    text: string | null
    /**
     * The enclosing group texts, outermost first.
     *
     * This is what makes a disaggregated cell readable. An aggregate form asks
     * `s46m5MS0hxu.Prlt0C1RF0s` as "Fixed, <1y", which means nothing without the group above it
     * saying "BCG doses given" - so the path is carried on the row rather than reconstructed by
     * whoever renders it.
     */
    groupPath: string[]
    /** Whether the served form still declares this link id. */
    known: boolean
    /** Every answer given to this question, in the order the receipt states them. */
    values: AnswerValue[]
}

/**
 * Every answered question of one receipt, in the order the form asks them.
 *
 * Unanswered questions are absent, because the receipt holds only the branches that were
 * answered and a table of empty rows would bury the ones that matter. Answers to link ids the
 * served form no longer declares come last, marked `known: false` - the honest rendering of a
 * guide that was rebuilt under a receipt that outlived it.
 *
 * A null spec is the whole-form version of that: nothing is known, so every row degrades to its
 * link id and the values it carries, and the page says why.
 */
export function joinAnswersToQuestions(
    spec: QuestionnaireSpec | null,
    response: QuestionnaireResponse,
): ReceiptAnswerRow[] {
    const answered = answeredItems(response)
    if (spec === null) {
        return answered.map((item) => ({
            linkId: item.linkId,
            text: item.text,
            groupPath: item.ancestorTexts,
            known: false,
            values: item.values,
        }))
    }

    const byLinkId = new Map(answered.map((item) => [item.linkId, item]))
    const asked = spec.nodes.flatMap((node) => {
        const item = byLinkId.get(node.linkId)
        if (item === undefined) return []
        return [
            {
                linkId: node.linkId,
                text: node.text,
                groupPath: node.ancestorLinkIds.map((ancestorLinkId) => {
                    const ancestor = spec.byLinkId.get(ancestorLinkId)
                    return ancestor?.text ?? ancestorLinkId
                }),
                known: true,
                values: item.values,
            },
        ]
    })
    const unknown = answered.flatMap((item) =>
        spec.byLinkId.has(item.linkId)
            ? []
            : [
                  {
                      linkId: item.linkId,
                      text: item.text,
                      groupPath: item.ancestorTexts,
                      known: false,
                      values: item.values,
                  },
              ],
    )
    return [...asked, ...unknown]
}

/**
 * What to call the form a receipt answered.
 *
 * The published title when the form is still served, then the id off the canonical, then the
 * canonical itself. A receipt outlives the guide that produced it, so "the form is gone" has to
 * render as something readable rather than as a blank cell.
 */
export function formLabel(summary: SpoolResponseSummary, form: Questionnaire | undefined): string {
    return (
        form?.title ??
        form?.name ??
        summary.questionnaire_id ??
        canonicalId(summary.questionnaire) ??
        summary.questionnaire
    )
}

/** One labelled fact of a receipt's capture context, and whether it reads as a code or as prose. */
export interface ReceiptContextFact {
    label: string
    value: string
    /** True when the value is an identifier rather than something written for a person to read. */
    mono: boolean
    /** An in-app route where this fact's subject has its own page, when it has one. */
    to?: string
}

/**
 * The attribute option combo a receipt reports for, as a fact for the capture-context grid.
 *
 * WHY IT IS READ OFF THE RESOURCE AND NOT THE SPOOL. The period and the organisation unit come
 * from the spool listing, which derives them when it indexes a receipt. This one comes from the
 * stored document itself, so it is on the page for a receipt the spool has no row for at all -
 * and the extension is right there in the resource, which makes a second derivation of it a
 * second thing that can disagree.
 *
 * WHY THE CODESYSTEM IS A SEPARATE ARGUMENT. The coding carries a display, but the served
 * vocabulary is the authority on what a concept is called now, and a coding written by a client
 * that sent system and code alone carries none. When neither answers - a guide recompiled since
 * the capture, a system this server never published - the fact degrades to the two strings the
 * receipt really holds, mono, rather than to a blank cell: `system|code` is exactly what someone
 * needs to go and look the combo up in DHIS2.
 */
export function attributeOptionComboFact(
    response: QuestionnaireResponse,
    codeSystem: CodeSystem | null,
): ReceiptContextFact | null {
    const coding = attributeOptionComboOf(response)
    if (coding === null) return null
    const label = attributeOptionComboLabel(codeSystem?.title ?? codeSystem?.name)
    const resolved =
        conceptDisplay(codeSystem, coding.code) ?? coding.display ?? null
    if (resolved === null) {
        return { label, value: `${coding.system ?? 'no system'} | ${coding.code ?? 'no code'}`, mono: true }
    }
    return { label, value: coding.code === undefined ? resolved : `${resolved} (${coding.code})`, mono: false }
}

/**
 * The tracker context a response carries in its own envelope, as facts for the capture-context grid.
 *
 * WHY THE RESOURCE AND NOT ONLY THE SPOOL. The spool derives the tracked entity and the enrollment
 * when it indexes a receipt, so for most receipts these repeat what it already said - and the
 * merge below drops the repeat. The two dates are the reason this exists: `D2EnrolledAt` and
 * `D2IncidentAt` are QuestionnaireResponse extensions and nothing else on the page reads them, so
 * a registration receipt without this would show which person was enrolled and never say when.
 * Reading all four from one place also means a receipt the spool has no row for still states its
 * whole tracker context, the same way the attribute option combo does.
 *
 * The dates read as local time rather than as the stored instant, because an enrollment date is
 * something a person checks against a calendar; the two uids stay mono, because they are handles
 * to type into DHIS2. Absence is ordinary throughout - an aggregate response has none of these,
 * and a program that displays no incident date generates responses that carry three of the four.
 *
 * THE DATES ARE LABELLED BY THE FORM, not by this module. A DHIS2 programme renames the dates it
 * collects - an antenatal programme's enrollment date is "Date first seen" - and the capture screen
 * labels its controls from `dateLabelsOf`, so a receipt labelling the same facts any other way would
 * be a second vocabulary for one submission. `labels` defaults to this project's own words for the
 * case a receipt outlives the form it answered, which is the same fallback the fill side takes.
 */
export function trackerContextFacts(
    response: QuestionnaireResponse,
    labels: DateLabels = DEFAULT_DATE_LABELS,
): ReceiptContextFact[] {
    const enrolledAt = enrolledAtOf(response)
    const incidentAt = incidentAtOf(response)
    const trackedEntity = trackedEntityOf(response)
    const enrollment = trackerEnrollmentOf(response)
    const facts: ReceiptContextFact[] = []
    if (trackedEntity !== null) facts.push({ label: TRACKED_ENTITY_FACT_LABEL, value: trackedEntity, mono: true })
    if (enrollment !== null) facts.push({ label: TRACKER_ENROLLMENT_FACT_LABEL, value: enrollment, mono: true })
    if (enrolledAt !== null) {
        facts.push({ label: labels.enrollmentDate, value: formatInstant(enrolledAt), mono: false })
    }
    if (incidentAt !== null) {
        facts.push({ label: labels.incidentDate, value: formatInstant(incidentAt), mono: false })
    }
    return facts
}

/**
 * Several sources of capture context in one list, the first statement of a label winning.
 *
 * The grid is keyed by label and the same fact reaches it from two directions - the spool derives
 * the tracked entity and the enrollment while the stored resource carries them - so a plain
 * concatenation would render one enrollment twice. First wins rather than last because the caller
 * orders its groups by how much each can say: the spool's facts are already resolved against the
 * registry by the time they arrive here, and the resource's are the bare uids.
 */
export function mergeContextFacts(...groups: ReceiptContextFact[][]): ReceiptContextFact[] {
    const stated = new Set<string>()
    const merged: ReceiptContextFact[] = []
    for (const group of groups) {
        for (const fact of group) {
            if (stated.has(fact.label)) continue
            stated.add(fact.label)
            merged.push(fact)
        }
    }
    return merged
}

/** One answered item of a stored response, read in document order with its ancestry. */
interface ReceiptAnsweredItem {
    linkId: string
    /** The text the response itself states, if any - R4 lets a response echo the question. */
    text: string | null
    /** The enclosing items' texts, or their link ids when they state none. */
    ancestorTexts: string[]
    values: AnswerValue[]
}

/** Walk a stored response, returning every item that carries at least one renderable answer. */
function answeredItems(response: QuestionnaireResponse): ReceiptAnsweredItem[] {
    const items: ReceiptAnsweredItem[] = []
    const walk = (nodes: QuestionnaireResponseItem[], ancestorTexts: string[]): void => {
        for (const node of nodes) {
            const label = node.text ?? node.linkId
            const values = (node.answer ?? []).flatMap((answer) => {
                const value = answerValue(answer)
                return value === null ? [] : [value]
            })
            if (values.length > 0) {
                items.push({
                    linkId: node.linkId,
                    text: node.text ?? null,
                    ancestorTexts,
                    values,
                })
            }
            // R4 nests follow-up questions under the answer they follow up on, as well as under
            // the item. The DHIS2 emitter writes neither, but a hand-written capture can, and an
            // answer this UI silently dropped would be a receipt read as smaller than it is.
            const nested = (node.answer ?? []).flatMap((answer) => answer.item ?? [])
            walk([...(node.item ?? []), ...nested], [...ancestorTexts, label])
        }
    }
    walk(response.item ?? [], [])
    return items
}
