#!/usr/bin/env bash
#
# Regenerate `packages/dhis2w-client/src/dhis2w_client/generated/v{N}` for each
# DHIS2 version passed (default: v41 v42 v43).
#
# For every version, spins up a fresh empty DHIS2 N via docker, waits for
# readiness, runs `d2w dev codegen generate` against it, and tears the stack
# down before moving on. Per-version dumps under `infra/v{N}/dump.sql.gz` are
# swapped out for 20-byte empty-gzip placeholders for the duration so DHIS2's
# Flyway migrations run cleanly on every version (loading the seeded e2e dump
# into a fresh stack would break).
#
# On exit — success, failure, or Ctrl+C — the script always restores the
# original dumps and brings the stack down, so there's no silent drift in
# the working tree.
#
# Usage:
#   infra/scripts/codegen_all_versions.sh            # default set
#   infra/scripts/codegen_all_versions.sh v42 v43    # subset
#
# Expect ~8-12 minutes per version (pull + boot + schema migrate + codegen
# + teardown). Pre-pull images with `make -C infra pull DHIS2_VERSION=vN`
# beforehand if you want to shave a few minutes off the first run.

set -euo pipefail

DEFAULT_VERSIONS=(v41 v42 v43)
if [ "$#" -gt 0 ]; then
  VERSIONS=("$@")
else
  VERSIONS=("${DEFAULT_VERSIONS[@]}")
fi

INFRA_DIR="$(cd "$(dirname "$0")/.." && pwd)"
REPO_ROOT="$(cd "$INFRA_DIR/.." && pwd)"

cleanup() {
  echo
  echo ">>> Cleaning up: stopping stack + restoring committed dumps"
  make -C "$INFRA_DIR" down >/dev/null 2>&1 || true
  for backup in "$INFRA_DIR"/v*/dump.sql.gz.codegen-backup; do
    [ -f "$backup" ] || continue
    mv -f "$backup" "${backup%.codegen-backup}"
    echo "    restored ${backup%.codegen-backup}"
  done
}
trap cleanup EXIT INT TERM

# Swap each per-version dump out for an empty placeholder. Loading a seeded
# v42 dump into a fresh v41 stack would fail schema migrations; empty lets
# DHIS2 bootstrap its own schema via Flyway on first start.
for dump in "$INFRA_DIR"/v*/dump.sql.gz; do
  [ -f "$dump" ] || continue
  backup="$dump.codegen-backup"
  if [ ! -f "$backup" ]; then
    mv "$dump" "$backup"
    echo ">>> Backed up $dump -> $backup"
  fi
  printf '' | gzip -9 > "$dump"
done

FAILED=()
for v in "${VERSIONS[@]}"; do
  echo
  echo "============================================================"
  echo ">>> DHIS2 $v"
  echo "============================================================"

  if ! make -C "$INFRA_DIR" up-fresh DHIS2_VERSION="$v"; then
    echo "!!! failed to bring up DHIS2 $v (image missing from Docker Hub?)"
    FAILED+=("$v:up")
    continue
  fi

  if ! make -C "$INFRA_DIR" wait; then
    echo "!!! $v did not become ready in time"
    FAILED+=("$v:wait")
    make -C "$INFRA_DIR" down >/dev/null 2>&1 || true
    continue
  fi

  echo ">>> running codegen for $v"
  if (cd "$REPO_ROOT" && uv run d2w dev codegen generate \
        --url http://localhost:8080 --username admin --password district); then
    echo ">>> done with codegen for $v"
  else
    echo "!!! codegen failed for $v"
    FAILED+=("$v:codegen")
  fi

  # Also dump each version's fresh schema state into infra/$v/dump.sql.gz
  # so there's a cheap restore point per version. These are Flyway-bootstrapped
  # empty DBs (no user data) plus whatever codegen probed; loading them gives
  # a usable DHIS2 $v without pulling + booting its image from scratch.
  # Exclusions mirror build_e2e_dump.py: analytics_* / aggregated_* /
  # completeness_* / _* are regenerated by analytics-trigger on restore.
  pg_container=$(docker ps --format '{{.Names}}' | grep -iE 'postgresql|postgres' | head -1 || true)
  out_dir="$INFRA_DIR/$v"
  out_dump="$out_dir/dump.sql.gz"
  if [ -n "$pg_container" ]; then
    mkdir -p "$out_dir"
    echo ">>> dumping $v schema to $out_dump"
    if docker exec "$pg_container" pg_dump --no-owner --no-privileges --no-sync \
          --clean --if-exists \
          --exclude-table="analytics_*" --exclude-table="aggregated_*" \
          --exclude-table="completeness_*" --exclude-table="_*" \
          -U dhis -d dhis | gzip -9 > "$out_dump"; then
      size=$(wc -c < "$out_dump")
      echo "    wrote $out_dump ($size bytes)"
    else
      echo "!!! pg_dump failed for $v"
      FAILED+=("$v:dump")
      rm -f "$out_dump"
    fi
  else
    echo "!!! no postgres container found to dump $v"
    FAILED+=("$v:dump-missing-container")
  fi

  make -C "$INFRA_DIR" down >/dev/null 2>&1 || true
done

echo
echo "============================================================"
if [ "${#FAILED[@]}" -eq 0 ]; then
  echo ">>> All versions generated successfully: ${VERSIONS[*]}"
  exit 0
fi
echo ">>> Finished with failures: ${FAILED[*]}"
exit 1
