"""Version-neutral FHIR IG generation: fhir.toml config, FSH emission, and project scaffolding.

Each component owns its schemas; this module is the one stable import
surface over them, so `from dhis2w_fhir import GenerateConfig` keeps working
however the components are arranged internally.
"""

from dhis2w_fhir.config import (
    FHIR_CONFIG_FILENAME,
    REPORTS_DIRECTORY,
    FhirProject,
    FhirProjectConfig,
    GenerateConfig,
    IgConfig,
    NamingConfig,
    NoFhirProjectError,
    find_project_fhir_config,
    load_fhir_config,
    load_project,
    write_fhir_config,
)
from dhis2w_fhir.foundation import (
    CAPTURE_SERVER_READ_RESOURCE_TYPES,
    FORM_TYPE_DEFINITIONS,
    FormTypeDefinition,
    FoundationNaming,
    NamingSystemDeclaration,
    ResponseProfileDeclaration,
    build_foundation_artifacts,
    build_naming_system_declarations,
    build_response_profile_declarations,
)
from dhis2w_fhir.i18n import TRANSLATION_EXTENSION_URL, TranslationIn, name_translations, normalize_locale
from dhis2w_fhir.names import markdown_text
from dhis2w_fhir.notes import aggregate_note
from dhis2w_fhir.period import (
    PERIOD_TYPE_DEFINITIONS,
    PERIOD_TYPE_NAMES,
    PeriodTypeDefinition,
    PeriodValue,
    parse_period,
    recent_periods,
)
from dhis2w_fhir.resources.examples import (
    EXAMPLES_DIRECTORY,
    SyntheticBuild,
    answer_element,
    build_example_artifacts,
    build_synthetic_responses,
    response_status_code,
    zoned_date_time,
)
from dhis2w_fhir.resources.examples.schemas import (
    ExampleAnswerIn,
    ExampleResponseIn,
    ExampleSelection,
)
from dhis2w_fhir.resources.option_sets import (
    build_option_set_artifacts,
    concept_assignments,
    max_slug_length,
    option_set_code_fallback,
    option_set_fsh_name,
    option_set_identities,
    option_set_identity_index,
)
from dhis2w_fhir.resources.option_sets.schemas import (
    ConceptAssignment,
    ConceptAssignmentPlan,
    OptionIn,
    OptionSetIdentity,
    OptionSetIdentityIndex,
    OptionSetIdentityPlan,
    OptionSetIn,
    OptionSetSelection,
)
from dhis2w_fhir.resources.organisation_units import (
    build_organisation_unit_instances,
    build_organisation_unit_level_terminology,
    build_organisation_unit_profiles,
    build_organisation_unit_terminology,
)
from dhis2w_fhir.resources.organisation_units.schemas import (
    GeoPoint,
    OrganisationUnitIn,
    OrganisationUnitSelection,
)
from dhis2w_fhir.resources.pages import (
    INTRO_SUFFIX,
    PAGES_BASE_SUBDIRECTORY,
    PAGES_DIRECTORY,
    SITE_PAGE_FILENAMES,
    build_page_artifacts,
)
from dhis2w_fhir.resources.pages.schemas import PagesIn
from dhis2w_fhir.resources.questionnaires import (
    BOUNDS_BY_VALUE_TYPE,
    ITEM_CONTROL_CODE_SYSTEM_URL,
    ITEM_CONTROL_EXTENSION_URL,
    ITEM_TYPES_BY_VALUE_TYPE,
    MAXIMUM_VALUE_EXTENSION_URL,
    MINIMUM_VALUE_EXTENSION_URL,
    NumericBounds,
    build_questionnaire_artifacts,
    domain_code,
    is_multi_valued,
)
from dhis2w_fhir.resources.questionnaires.schemas import (
    CategoryComboIn,
    CategoryOptionComboIn,
    QuestionnaireItemIn,
    QuestionnaireNaming,
    QuestionnaireSectionIn,
    QuestionnaireSourceIn,
    TargetSelection,
)
from dhis2w_fhir.scaffold import build_scaffold_files
from dhis2w_fhir.scaffold.schemas import (
    DEFAULT_SUSHI_TIMEOUT_SECONDS,
    InitOptions,
    ScaffoldFile,
    ScaffoldReport,
)
from dhis2w_fhir.service import GenerateAllReport, GenerateReport, UnsupportedProgramError
from dhis2w_fhir.validation import build_code_validation, render_validation_markdown
from dhis2w_fhir.validation.pdf import render_validation_pdf
from dhis2w_fhir.validation.report import render_validation_csv
from dhis2w_fhir.validation.schemas import (
    FhirValidationReport,
    MetadataCollectionIn,
    MetadataItemIn,
    SeverityBreakdown,
    ValidationFinding,
)
from dhis2w_fhir.writer import (
    GENERATED_HEADER,
    GENERATED_MARKDOWN_HEADER,
    FshArtifact,
    FshBuild,
    SyncReport,
    clean_generated_files,
    generated_header,
    is_generated_file,
    sync_artifacts,
    write_artifacts,
)

__all__ = [
    "BOUNDS_BY_VALUE_TYPE",
    "CAPTURE_SERVER_READ_RESOURCE_TYPES",
    "DEFAULT_SUSHI_TIMEOUT_SECONDS",
    "EXAMPLES_DIRECTORY",
    "FHIR_CONFIG_FILENAME",
    "REPORTS_DIRECTORY",
    "FORM_TYPE_DEFINITIONS",
    "GENERATED_HEADER",
    "GENERATED_MARKDOWN_HEADER",
    "INTRO_SUFFIX",
    "ITEM_CONTROL_CODE_SYSTEM_URL",
    "ITEM_CONTROL_EXTENSION_URL",
    "ITEM_TYPES_BY_VALUE_TYPE",
    "MAXIMUM_VALUE_EXTENSION_URL",
    "MINIMUM_VALUE_EXTENSION_URL",
    "PAGES_BASE_SUBDIRECTORY",
    "PAGES_DIRECTORY",
    "PERIOD_TYPE_DEFINITIONS",
    "PERIOD_TYPE_NAMES",
    "SITE_PAGE_FILENAMES",
    "TRANSLATION_EXTENSION_URL",
    "CategoryComboIn",
    "CategoryOptionComboIn",
    "ConceptAssignment",
    "ConceptAssignmentPlan",
    "ExampleAnswerIn",
    "ExampleResponseIn",
    "ExampleSelection",
    "FhirProject",
    "FhirProjectConfig",
    "FhirValidationReport",
    "FormTypeDefinition",
    "FoundationNaming",
    "FshArtifact",
    "FshBuild",
    "GenerateAllReport",
    "GenerateConfig",
    "GenerateReport",
    "GeoPoint",
    "IgConfig",
    "InitOptions",
    "MetadataCollectionIn",
    "MetadataItemIn",
    "NamingConfig",
    "NamingSystemDeclaration",
    "NoFhirProjectError",
    "NumericBounds",
    "OptionIn",
    "OptionSetIdentity",
    "OptionSetIdentityIndex",
    "OptionSetIdentityPlan",
    "OptionSetIn",
    "OptionSetSelection",
    "OrganisationUnitIn",
    "OrganisationUnitSelection",
    "PagesIn",
    "PeriodTypeDefinition",
    "PeriodValue",
    "QuestionnaireItemIn",
    "QuestionnaireNaming",
    "QuestionnaireSectionIn",
    "QuestionnaireSourceIn",
    "ResponseProfileDeclaration",
    "ScaffoldFile",
    "ScaffoldReport",
    "SeverityBreakdown",
    "SyncReport",
    "SyntheticBuild",
    "TargetSelection",
    "TranslationIn",
    "UnsupportedProgramError",
    "ValidationFinding",
    "aggregate_note",
    "answer_element",
    "build_code_validation",
    "build_example_artifacts",
    "build_foundation_artifacts",
    "build_naming_system_declarations",
    "build_option_set_artifacts",
    "build_page_artifacts",
    "build_organisation_unit_instances",
    "build_organisation_unit_level_terminology",
    "build_organisation_unit_profiles",
    "build_organisation_unit_terminology",
    "build_questionnaire_artifacts",
    "build_response_profile_declarations",
    "build_scaffold_files",
    "build_synthetic_responses",
    "clean_generated_files",
    "concept_assignments",
    "domain_code",
    "find_project_fhir_config",
    "generated_header",
    "is_generated_file",
    "is_multi_valued",
    "load_fhir_config",
    "load_project",
    "markdown_text",
    "max_slug_length",
    "name_translations",
    "normalize_locale",
    "option_set_code_fallback",
    "option_set_fsh_name",
    "option_set_identities",
    "option_set_identity_index",
    "parse_period",
    "recent_periods",
    "render_validation_csv",
    "render_validation_markdown",
    "render_validation_pdf",
    "response_status_code",
    "sync_artifacts",
    "write_artifacts",
    "write_fhir_config",
    "zoned_date_time",
]
