"""Disk I/O for generated FSH files: header bookkeeping, cleanup, and writes.

Every file this package writes starts with `GENERATED_HEADER`; cleanup deletes
only files carrying that first line, so hand-authored FSH in the same tree is
never touched.
"""

from __future__ import annotations

from pathlib import Path

from dhis2w_fhir.models import FshArtifact

GENERATED_HEADER = "// Generated by d2w fhir generate - do not edit"


def clean_generated_files(directory: Path) -> list[str]:
    """Delete `*.fsh` files under `directory` whose first line is the generated header; return their names."""
    deleted: list[str] = []
    if not directory.is_dir():
        return deleted
    for path in sorted(directory.glob("*.fsh")):
        first_line = path.read_text(encoding="utf-8").split("\n", 1)[0]
        if first_line == GENERATED_HEADER:
            path.unlink()
            deleted.append(path.name)
    return deleted


def write_artifacts(fsh_directory: Path, artifacts: list[FshArtifact]) -> list[str]:
    """Write artifacts under `fsh_directory` with the generated header prepended; return relative paths."""
    written: list[str] = []
    for artifact in sorted(artifacts, key=lambda item: item.relative_path):
        destination = fsh_directory / artifact.relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(f"{GENERATED_HEADER}\n\n{artifact.content}", encoding="utf-8")
        written.append(artifact.relative_path)
    return written
