"""The generated-artifact contract plus the disk I/O behind it: header bookkeeping, sync, and writes.

Two output formats travel through this module, each with its own way of telling
generated files from hand-authored ones.

`FshArtifact` is what every FSH emitter returns. Those files start with a
generated header chosen by extension - the FSH line comment for `.fsh`, the HTML
comment markdown renders invisibly for `.md` - and cleanup deletes only files
carrying one of those two first lines, so hand-authored FSH and the
hand-authored `pagecontent/index.md` in the same trees are never touched.

`JsonArtifact` carries a pre-built FHIR JSON document. JSON has no comment
syntax, so a header cannot mark those files: the content is written verbatim and
`sync_json_artifacts` instead owns its target directory outright, deleting every
`*.json` in it that the current build did not produce.

Both syncs compare content before writing, so an unchanged run leaves timestamps
and diffs quiet.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class FshArtifact(BaseModel):
    """One generated file, path relative to the sync base directory (`ig/input/fsh/`, or `ig/input/` for pages)."""

    model_config = ConfigDict(frozen=True)

    relative_path: str
    kind: Literal["aliases", "extension", "terminology-pair", "profile", "instances", "page"]
    fsh_name: str
    content: str


class JsonArtifact(BaseModel):
    """One generated JSON file: a path relative to the sync base directory and its serialised document."""

    model_config = ConfigDict(frozen=True)

    relative_path: str
    content: str


class FshBuild(BaseModel):
    """Result of a pure FSH build step: artifacts plus human-facing notes (skips, fallbacks)."""

    artifacts: list[FshArtifact] = Field(default_factory=list)
    notes: list[str] = Field(default_factory=list)


class JsonBuild(BaseModel):
    """Result of a pre-built FHIR JSON build step: artifacts plus human-facing notes (skips, fallbacks)."""

    artifacts: list[JsonArtifact] = Field(default_factory=list)
    notes: list[str] = Field(default_factory=list)


class SyncReport(BaseModel):
    """Outcome of syncing generated artifacts into a target subdirectory."""

    written: list[str] = Field(default_factory=list)
    unchanged: list[str] = Field(default_factory=list)
    deleted: list[str] = Field(default_factory=list)


GENERATED_HEADER = "// Generated by d2w fhir generate - do not edit"

#: The header a generated markdown page carries. An HTML comment renders invisibly, so the page
#: reads clean while the sweep can still tell a generated page from a hand-authored one.
GENERATED_MARKDOWN_HEADER = "<!-- Generated by d2w fhir generate - do not edit -->"

#: The extension whose generated files carry the markdown header; everything else takes the FSH one.
_MARKDOWN_SUFFIX = ".md"

#: The file kinds a sweep considers, so a hand-authored file of any other extension is never read.
_SWEPT_PATTERNS = ("*.fsh", "*.md")

#: The extension a JSON sweep deletes; every other file in the target directory is left alone.
_JSON_SWEPT_PATTERN = "*.json"


def generated_header(relative_path: str) -> str:
    """The header one generated file carries, chosen by extension: the markdown comment for `.md`, else FSH."""
    return GENERATED_MARKDOWN_HEADER if relative_path.endswith(_MARKDOWN_SUFFIX) else GENERATED_HEADER


def is_generated_file(path: Path) -> bool:
    """Check whether a file on disk was written by this package - its first line is one of the two headers."""
    first_line = path.read_text(encoding="utf-8").split("\n", 1)[0]
    return first_line in {GENERATED_HEADER, GENERATED_MARKDOWN_HEADER}


def _swept_files(directory: Path) -> list[Path]:
    """Every file under `directory` at any depth a sweep may delete, by extension, in a stable order."""
    return sorted(path for pattern in _SWEPT_PATTERNS for path in directory.rglob(pattern))


def _prune_empty_directories(directory: Path) -> None:
    """Remove every subdirectory left empty under `directory`, deepest first; `directory` itself always stays."""
    subdirectories = [path for path in directory.rglob("*") if path.is_dir()]
    for path in sorted(subdirectories, key=lambda item: len(item.parts), reverse=True):
        if not any(path.iterdir()):
            path.rmdir()


def clean_generated_files(directory: Path) -> list[str]:
    """Delete every header-bearing `.fsh` / `.md` file under `directory` at any depth; return their relative paths.

    The sweep goes to the bottom of the tree, so a generated file a nesting emitter left behind -
    `tracker-programs/<program uid>/<stage uid>.fsh` - is removed wherever it sits, and a subdirectory
    it empties goes with it. Only header-bearing files are deleted, so hand-authored work at any depth
    survives. Paths are reported relative to `directory`, which for a flat directory is the file name.
    """
    deleted: list[str] = []
    if not directory.is_dir():
        return deleted
    for path in _swept_files(directory):
        if is_generated_file(path):
            path.unlink()
            deleted.append(path.relative_to(directory).as_posix())
    _prune_empty_directories(directory)
    return deleted


def write_artifacts(base_directory: Path, artifacts: list[FshArtifact]) -> list[str]:
    """Write artifacts under `base_directory` with their generated header prepended; return relative paths."""
    written: list[str] = []
    for artifact in sorted(artifacts, key=lambda item: item.relative_path):
        destination = base_directory / artifact.relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(_headed_content(artifact), encoding="utf-8")
        written.append(artifact.relative_path)
    return written


def sync_artifacts(base_directory: Path, target_subdirectory: str, artifacts: list[FshArtifact]) -> SyncReport:
    """Write changed/new artifacts and delete stale generated files anywhere under one target subdirectory.

    A target that nests - `tracker-programs/<program uid>/<stage uid>.fsh` - is swept to the
    bottom, so a stage the selection dropped is deleted wherever it sits, and the produced set
    is keyed by path rather than by name so two programs may hold same-named files. Only
    header-bearing files are deleted, so a hand-authored file at any depth survives. A
    subdirectory the sweep empties is removed with it; the target directory itself stays.
    Deleted entries are reported as paths relative to the target.
    """
    report = SyncReport()
    produced: set[str] = set()
    for artifact in sorted(artifacts, key=lambda item: item.relative_path):
        destination = base_directory / artifact.relative_path
        produced.add(destination.relative_to(base_directory).as_posix())
        content = _headed_content(artifact)
        if destination.exists() and destination.read_text(encoding="utf-8") == content:
            report.unchanged.append(artifact.relative_path)
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8")
        report.written.append(artifact.relative_path)
    target = base_directory / target_subdirectory
    if target.is_dir():
        for path in _swept_files(target):
            if path.relative_to(base_directory).as_posix() in produced:
                continue
            if is_generated_file(path):
                path.unlink()
                report.deleted.append(path.relative_to(target).as_posix())
        _prune_empty_directories(target)
    return report


def sync_json_artifacts(base_directory: Path, target_subdirectory: str, artifacts: list[JsonArtifact]) -> SyncReport:
    """Write changed/new JSON verbatim and delete every unproduced `*.json` in the target directory this fully owns.

    JSON carries no comment syntax, so a generated header cannot mark these files and there is no
    `is_generated_file` check on the sweep: `target_subdirectory` belongs entirely to the generator, and any
    hand-authored `.json` placed there is deleted. Files of other extensions and nested subdirectories survive.
    """
    report = SyncReport()
    produced: set[str] = set()
    for artifact in sorted(artifacts, key=lambda item: item.relative_path):
        destination = base_directory / artifact.relative_path
        produced.add(destination.name)
        if destination.exists() and destination.read_text(encoding="utf-8") == artifact.content:
            report.unchanged.append(artifact.relative_path)
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(artifact.content, encoding="utf-8")
        report.written.append(artifact.relative_path)
    target = base_directory / target_subdirectory
    if target.is_dir():
        for path in sorted(target.glob(_JSON_SWEPT_PATTERN)):
            if path.name in produced:
                continue
            path.unlink()
            report.deleted.append(path.name)
    return report


def _headed_content(artifact: FshArtifact) -> str:
    """One artifact's file content: its extension's generated header, a blank line, then the rendered body."""
    return f"{generated_header(artifact.relative_path)}\n\n{artifact.content}"
