"""The generated-artifact contract plus the disk I/O behind it: header bookkeeping, sync, and writes.

`FshArtifact` is what every emitter returns and what this module writes; the
components depend on it rather than on each other. Every file this package
writes starts with `GENERATED_HEADER`; cleanup deletes only files carrying
that first line, so hand-authored FSH in the same tree is never touched.
Sync compares content before writing, so an unchanged run leaves timestamps
and diffs quiet.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class FshArtifact(BaseModel):
    """One generated FSH file, path relative to `ig/input/fsh/`."""

    model_config = ConfigDict(frozen=True)

    relative_path: str
    kind: Literal["aliases", "extension", "terminology-pair", "profile", "instances"]
    fsh_name: str
    content: str


class FshBuild(BaseModel):
    """Result of a pure FSH build step: artifacts plus human-facing notes (skips, fallbacks)."""

    artifacts: list[FshArtifact] = Field(default_factory=list)
    notes: list[str] = Field(default_factory=list)


class SyncReport(BaseModel):
    """Outcome of syncing generated artifacts into a target subdirectory."""

    written: list[str] = Field(default_factory=list)
    unchanged: list[str] = Field(default_factory=list)
    deleted: list[str] = Field(default_factory=list)


GENERATED_HEADER = "// Generated by d2w fhir generate - do not edit"


def clean_generated_files(directory: Path) -> list[str]:
    """Delete `*.fsh` files under `directory` whose first line is the generated header; return their names."""
    deleted: list[str] = []
    if not directory.is_dir():
        return deleted
    for path in sorted(directory.glob("*.fsh")):
        first_line = path.read_text(encoding="utf-8").split("\n", 1)[0]
        if first_line == GENERATED_HEADER:
            path.unlink()
            deleted.append(path.name)
    return deleted


def write_artifacts(fsh_directory: Path, artifacts: list[FshArtifact]) -> list[str]:
    """Write artifacts under `fsh_directory` with the generated header prepended; return relative paths."""
    written: list[str] = []
    for artifact in sorted(artifacts, key=lambda item: item.relative_path):
        destination = fsh_directory / artifact.relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(f"{GENERATED_HEADER}\n\n{artifact.content}", encoding="utf-8")
        written.append(artifact.relative_path)
    return written


def sync_artifacts(fsh_directory: Path, target_subdirectory: str, artifacts: list[FshArtifact]) -> SyncReport:
    """Write changed/new artifacts and delete stale generated files under one target subdirectory."""
    report = SyncReport()
    produced: set[str] = set()
    for artifact in sorted(artifacts, key=lambda item: item.relative_path):
        destination = fsh_directory / artifact.relative_path
        produced.add(destination.name)
        content = f"{GENERATED_HEADER}\n\n{artifact.content}"
        if destination.exists() and destination.read_text(encoding="utf-8") == content:
            report.unchanged.append(artifact.relative_path)
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8")
        report.written.append(artifact.relative_path)
    target = fsh_directory / target_subdirectory
    if target.is_dir():
        for path in sorted(target.glob("*.fsh")):
            if path.name in produced:
                continue
            first_line = path.read_text(encoding="utf-8").split("\n", 1)[0]
            if first_line == GENERATED_HEADER:
                path.unlink()
                report.deleted.append(path.name)
    return report
