// Generated by d2w fhir generate - do not edit

CodeSystem: D2COC_CS
Id: d2-coc-cs
Title: "DHIS2 category option combinations"
Description: "DHIS2 category option combinations the generated questionnaires disaggregate by. Concept codes are DHIS2 category option combo UIDs."
* ^status = #draft
* ^experimental = true
* ^content = #complete
* ^caseSensitive = true
* ^valueSet = Canonical(D2COC_VS)
* ^property[+].code = #dhis2-code
* ^property[=].uri = "http://dhis2.org/fhir/property/dhis2-code"
* ^property[=].description = "DHIS2 category option combo code."
* ^property[=].type = #string
* #pn1upwnbxfn "Damages"
* #pn1upwnbxfn ^property[+].code = #dhis2-code
* #pn1upwnbxfn ^property[=].valueString = "COC_360271"
* #fsFN9T4ck3E "Expired"
* #fsFN9T4ck3E ^property[+].code = #dhis2-code
* #fsFN9T4ck3E ^property[=].valueString = "COC_360270"
* #TxaWpw1pN5G "VVM Change"
* #TxaWpw1pN5G ^property[+].code = #dhis2-code
* #TxaWpw1pN5G ^property[=].valueString = "COC_360272"

ValueSet: D2COC_VS
Id: d2-coc-vs
Title: "DHIS2 category option combinations"
Description: "DHIS2 category option combinations the generated questionnaires disaggregate by. Concept codes are DHIS2 category option combo UIDs."
* ^status = #draft
* ^experimental = true
* include codes from system D2COC_CS
