// Generated by d2w fhir generate - do not edit

CodeSystem: D2OU_Level_CS
Id: d2-ou-level-cs
Title: "DHIS2 organisation unit levels"
Description: "Hierarchy levels of the DHIS2 organisation unit tree."
* ^status = #draft
* ^experimental = true
* ^content = #complete
* ^caseSensitive = true
* ^valueSet = Canonical(D2OU_Level_VS)
* #level-2 "Level 2"
* #level-3 "Level 3"
* #level-4 "Level 4"

ValueSet: D2OU_Level_VS
Id: d2-ou-level-vs
Title: "DHIS2 organisation unit levels"
Description: "Hierarchy levels of the DHIS2 organisation unit tree."
* ^status = #draft
* ^experimental = true
* include codes from system D2OU_Level_CS
