// Generated by d2w fhir generate - do not edit

Instance: D2OrganizationExample
InstanceOf: D2Organization
Title: "Example DHIS2 Organization - Pujehun (bL4ooGhyHRQ)"
Description: "A worked D2Organization: DHIS2 organisation unit Pujehun (bL4ooGhyHRQ) as the legal entity, carrying both DHIS2 identifiers and its hierarchy level."
Usage: #example
* id = "d2-organization-example"
* identifier[dhis2id].system = $DHIS2-OU
* identifier[dhis2id].value = "bL4ooGhyHRQ"
* identifier[dhis2code].system = $DHIS2-OU-CODE
* identifier[dhis2code].value = "OU_260377"
* active = true
* name = "Pujehun"
* type = D2OU_Level_CS#level-2 "Province"

Instance: D2LocationExample
InstanceOf: D2Location
Title: "Example DHIS2 Location - Pujehun (bL4ooGhyHRQ)"
Description: "A worked D2Location: DHIS2 organisation unit Pujehun (bL4ooGhyHRQ) as the physical place, managed by the D2Organization of the same unit."
Usage: #example
* id = "d2-location-example"
* identifier[dhis2id].system = $DHIS2-OU
* identifier[dhis2id].value = "bL4ooGhyHRQ"
* identifier[dhis2code].system = $DHIS2-OU-CODE
* identifier[dhis2code].value = "OU_260377"
* status = #active
* name = "Pujehun"
* description = "A worked D2Location: DHIS2 organisation unit Pujehun (bL4ooGhyHRQ) as the physical place, managed by the D2Organization of the same unit."
* position.longitude = -11.567171
* position.latitude = 7.295009
* extension[level].valueCoding = D2OU_Level_CS#level-2 "Province"
* managingOrganization = Reference(D2OrganizationExample)
