"""FHIR R4 resource schemas for the artifacts this package emits."""

from __future__ import annotations

from dhis2w_fhir.r4.schemas import (
    BOUNDARY_EXTENSION_URL,
    Attachment,
    BackboneElement,
    CodeableConcept,
    CodeSystem,
    CodeSystemConcept,
    CodeSystemConceptDesignation,
    CodeSystemConceptProperty,
    CodeSystemProperty,
    Coding,
    ContactPoint,
    DomainResource,
    Element,
    Extension,
    FhirBase,
    HumanName,
    Identifier,
    Location,
    LocationPosition,
    Meta,
    Organization,
    OrganizationContact,
    Reference,
    Resource,
    ValueSet,
    ValueSetCompose,
    ValueSetInclude,
)

__all__ = [
    "BOUNDARY_EXTENSION_URL",
    "Attachment",
    "CodeSystem",
    "CodeSystemConcept",
    "CodeSystemConceptDesignation",
    "CodeSystemConceptProperty",
    "CodeSystemProperty",
    "CodeableConcept",
    "Coding",
    "ContactPoint",
    "Extension",
    "BackboneElement",
    "DomainResource",
    "FhirBase",
    "Resource",
    "HumanName",
    "Identifier",
    "Location",
    "LocationPosition",
    "Meta",
    "Element",
    "Organization",
    "OrganizationContact",
    "Reference",
    "ValueSet",
    "ValueSetCompose",
    "ValueSetInclude",
]
