// Generated by d2w fhir generate - do not edit

Profile: D2Organization
Parent: Organization
Id: d2-organization
Title: "DHIS2 Organization"
Description: "An organisation unit imported from DHIS2."
* ^status = #draft
* ^experimental = true
* identifier ^slicing.discriminator.type = #value
* identifier ^slicing.discriminator.path = "system"
* identifier ^slicing.rules = #open
* identifier contains dhis2id 1..1 and dhis2code 1..1
* identifier[dhis2id].system = $DHIS2-OU
* identifier[dhis2code].system = $DHIS2-OU-CODE
* active 1..1
* type 1..*
* type from D2OU_Level_VS (extensible)
* name 1..1
* partOf only Reference(D2Organization)

Profile: D2Location
Parent: Location
Id: d2-location
Title: "DHIS2 Location"
Description: "The physical place of a DHIS2 organisation unit."
* ^status = #draft
* ^experimental = true
* identifier ^slicing.discriminator.type = #value
* identifier ^slicing.discriminator.path = "system"
* identifier ^slicing.rules = #open
* identifier contains dhis2id 1..1 and dhis2code 1..1
* identifier[dhis2id].system = $DHIS2-OU
* identifier[dhis2code].system = $DHIS2-OU-CODE
* name 1..1
* status 1..1
* position 0..1 MS
* extension contains http://hl7.org/fhir/StructureDefinition/location-boundary-geojson named boundary 0..1 and D2OrganisationUnitLevel named level 1..1
* extension[boundary] ^short = "The unit's DHIS2 geometry, carried as a GeoJSON Feature in the attachment."
* extension[level] ^short = "The DHIS2 organisation unit level this place sits at."
* managingOrganization 1..1
* managingOrganization only Reference(D2Organization)
* partOf only Reference(D2Location)
