// Generated by d2w fhir generate - do not edit

Instance: D2OrganizationExample
InstanceOf: D2Organization
Title: "Example DHIS2 Organization - Koinadugu (qhqAxPSTUXp)"
Description: "A worked D2Organization: DHIS2 organisation unit Koinadugu (qhqAxPSTUXp) as the legal entity, carrying both DHIS2 identifiers and its hierarchy level."
Usage: #example
* id = "d2-organization-example"
* identifier[dhis2id].system = $DHIS2-OU
* identifier[dhis2id].value = "qhqAxPSTUXp"
* identifier[dhis2code].system = $DHIS2-OU-CODE
* identifier[dhis2code].value = "OU_226213"
* active = true
* name = "Koinadugu"
* type = D2OU_Level_CS#level-2 "Level 2"

Instance: D2LocationExample
InstanceOf: D2Location
Title: "Example DHIS2 Location - Koinadugu (qhqAxPSTUXp)"
Description: "A worked D2Location: DHIS2 organisation unit Koinadugu (qhqAxPSTUXp) as the physical place, managed by the D2Organization of the same unit."
Usage: #example
* id = "d2-location-example"
* identifier[dhis2id].system = $DHIS2-OU
* identifier[dhis2id].value = "qhqAxPSTUXp"
* identifier[dhis2code].system = $DHIS2-OU-CODE
* identifier[dhis2code].value = "OU_226213"
* status = #active
* name = "Koinadugu"
* description = "A worked D2Location: DHIS2 organisation unit Koinadugu (qhqAxPSTUXp) as the physical place, managed by the D2Organization of the same unit."
* position.longitude = -11.344954
* position.latitude = 9.452197
* extension[level].valueCoding = D2OU_Level_CS#level-2 "Level 2"
* managingOrganization = Reference(D2OrganizationExample)
