// Generated by d2w fhir generate - do not edit

Instance: Questionnaire-PsAncVisit1
InstanceOf: Questionnaire
Title: "Questionnaire - ANC follow-up - ANC visit"
Description: "DHIS2 tracker program stage ANC visit (PsAncVisit1) of program ANC follow-up (PrAncCare01) as a data capture form."
Usage: #definition
* id = "PsAncVisit1"
* extension[D2FormType].valueCode = #tracker-event
* extension[D2Repeatable].valueBoolean = true
* extension[D2OrganisationUnitAssignment].valueReference = Reference(List/d2-pr-PrAncCare01-org-units)
* url = "http://example.org/fhir/examples/event-program/Questionnaire/PsAncVisit1"
* identifier[+].system = $DHIS2-PS
* identifier[=].value = "PsAncVisit1"
* identifier[+].system = $DHIS2-PS-CODE
* identifier[=].value = "PsAncVisit1"
* identifier[+].system = $DHIS2-PROGRAM
* identifier[=].value = "PrAncCare01"
* name = "D2PS_PsAncVisit1"
* title = "ANC follow-up - ANC visit"
* description = "DHIS2 tracker program stage ANC visit (PsAncVisit1) of program ANC follow-up (PrAncCare01) as a data capture form."
* status = #draft
* experimental = true
* subjectType = #Patient
* code = D2FormType_CS#tracker-event
* item[+].linkId = "DeAncVisNo1"
* item[=].code = D2DE_CS#DeAncVisNo1 "ANC visit number"
* item[=].text = "ANC visit number"
* item[=].type = #integer
* item[=].required = true
* item[=].extension[+].url = "http://hl7.org/fhir/StructureDefinition/minValue"
* item[=].extension[=].valueInteger = 1
* item[+].linkId = "DeAncBpSys1"
* item[=].code = D2DE_CS#DeAncBpSys1 "ANC systolic blood pressure"
* item[=].text = "ANC systolic blood pressure"
* item[=].type = #integer
* item[+].linkId = "DeAncDanger"
* item[=].code = D2DE_CS#DeAncDanger "ANC danger signs present"
* item[=].text = "ANC danger signs present"
* item[=].type = #boolean
