"""The single `dhis2_cli` MCP tool: run the `dhis2` CLI as a subprocess.

Small local models cannot afford the full `dhis2w-mcp` server's ~337 typed tools (≈50-65k
tokens of schema loaded up front). This module exposes ONE tool instead: the model discovers
the command surface progressively with `--help` and runs commands with `--json`. Everything
stays on the host — the bridge spawns the local `dhis2` binary and never sends data anywhere.

`READ_ONLY_COMMANDS` is the allowlist consulted when `DHIS2_MCP_READONLY=1`: a fail-closed
set of read-only command paths generated by introspecting the Typer/Click command tree
(identical across the v41/v42/v43 plugin trees). `tests/test_cli_bridge.py` re-derives it from
the live tree so it cannot silently drift.
"""

from __future__ import annotations

import asyncio
import contextlib
import json
import os
import shlex
import shutil
import sys
from pathlib import Path
from typing import Any, Final

from pydantic import BaseModel, ConfigDict

#: Environment variable naming an explicit `dhis2` executable (overrides auto-discovery).
DHIS2_CLI_BIN_ENV: Final = "DHIS2_CLI_BIN"
#: Environment variable that, when truthy, restricts the bridge to read-only commands.
READONLY_ENV: Final = "DHIS2_MCP_READONLY"
#: Environment variable overriding the per-command timeout, in seconds.
TIMEOUT_ENV: Final = "DHIS2_MCP_CLI_TIMEOUT"
#: Default per-command timeout when `TIMEOUT_ENV` is unset or invalid.
DEFAULT_TIMEOUT_SECONDS: Final = 120.0

#: Exit code returned when a command exceeds its timeout (matches coreutils `timeout`).
EXIT_TIMEOUT: Final = 124
#: Exit code returned when read-only mode refuses a mutating command.
EXIT_REFUSED: Final = 126
#: Exit code returned when the `dhis2` binary cannot be located or executed.
EXIT_CLI_NOT_FOUND: Final = 127

#: Read-only command paths permitted under `DHIS2_MCP_READONLY=1`. Each tuple is a leaf
#: command path; a request is allowed when one of these is a prefix of its command path.
#: Generated from the Typer command tree — keep in sync via the drift test.
READ_ONLY_COMMANDS: Final[frozenset[tuple[str, ...]]] = frozenset(
    {
        ("analytics", "enrollments", "query"),
        ("analytics", "events", "query"),
        ("analytics", "outlier-detection"),
        ("analytics", "query"),
        ("analytics", "tracked-entities", "query"),
        ("apps", "hub-list"),
        ("apps", "hub-url"),
        ("apps", "list"),
        ("apps", "ls"),
        ("data", "aggregate", "get"),
        ("data", "tracker", "enrollment", "list"),
        ("data", "tracker", "enrollment", "ls"),
        ("data", "tracker", "event", "list"),
        ("data", "tracker", "event", "ls"),
        ("data", "tracker", "get"),
        ("data", "tracker", "list"),
        ("data", "tracker", "ls"),
        ("data", "tracker", "relationship", "list"),
        ("data", "tracker", "relationship", "ls"),
        ("dev", "codegen", "diff"),
        ("dev", "customize", "show"),
        ("doctor", "bugs"),
        ("doctor", "integrity"),
        ("doctor", "metadata"),
        ("files", "documents", "get"),
        ("files", "documents", "list"),
        ("files", "documents", "ls"),
        ("files", "resources", "get"),
        ("maintenance", "dataintegrity", "list"),
        ("maintenance", "dataintegrity", "ls"),
        ("maintenance", "task", "list"),
        ("maintenance", "task", "ls"),
        ("maintenance", "task", "status"),
        ("maintenance", "task", "types"),
        ("maintenance", "validation", "result", "get"),
        ("maintenance", "validation", "result", "list"),
        ("maintenance", "validation", "result", "ls"),
        ("messaging", "get"),
        ("messaging", "list"),
        ("messaging", "ls"),
        ("metadata", "attribute", "find"),
        ("metadata", "attribute", "get"),
        ("metadata", "categories", "get"),
        ("metadata", "category-combos", "get"),
        ("metadata", "category-option-combos", "get"),
        ("metadata", "category-option-combos", "list-for-combo"),
        ("metadata", "category-option-group-sets", "get"),
        ("metadata", "category-option-groups", "get"),
        ("metadata", "category-option-groups", "members"),
        ("metadata", "category-options", "get"),
        ("metadata", "dashboard", "get"),
        ("metadata", "data-element-group-sets", "get"),
        ("metadata", "data-element-groups", "get"),
        ("metadata", "data-element-groups", "members"),
        ("metadata", "data-elements", "get"),
        ("metadata", "data-sets", "get"),
        ("metadata", "diff"),
        ("metadata", "diff-profiles"),
        ("metadata", "get"),
        ("metadata", "indicator-group-sets", "get"),
        ("metadata", "indicator-groups", "get"),
        ("metadata", "indicator-groups", "members"),
        ("metadata", "indicators", "get"),
        ("metadata", "legend-sets", "get"),
        ("metadata", "list"),
        ("metadata", "ls"),
        ("metadata", "map", "get"),
        ("metadata", "options", "attribute", "find"),
        ("metadata", "options", "attribute", "get"),
        ("metadata", "options", "find"),
        ("metadata", "options", "get"),
        ("metadata", "organisation-unit-group-sets", "get"),
        ("metadata", "organisation-unit-groups", "get"),
        ("metadata", "organisation-unit-groups", "members"),
        ("metadata", "organisation-unit-levels", "get"),
        ("metadata", "organisation-units", "get"),
        ("metadata", "organisation-units", "tree"),
        ("metadata", "predictor-groups", "get"),
        ("metadata", "predictor-groups", "members"),
        ("metadata", "predictors", "get"),
        ("metadata", "program-indicator-groups", "get"),
        ("metadata", "program-indicator-groups", "members"),
        ("metadata", "program-indicators", "get"),
        ("metadata", "program-rule", "get"),
        ("metadata", "program-rule", "vars-for"),
        ("metadata", "program-rule", "where-de-is-used"),
        ("metadata", "program-stages", "get"),
        ("metadata", "programs", "get"),
        ("metadata", "export"),
        ("metadata", "search"),
        ("metadata", "usage"),
        ("metadata", "sections", "get"),
        ("metadata", "sql-view", "get"),
        ("metadata", "tracked-entity-attributes", "get"),
        ("metadata", "tracked-entity-types", "get"),
        ("metadata", "type", "list"),
        ("metadata", "type", "ls"),
        ("metadata", "validation-rule-groups", "get"),
        ("metadata", "validation-rule-groups", "members"),
        ("metadata", "validation-rules", "get"),
        ("metadata", "viz", "get"),
        ("profile", "list"),
        ("profile", "ls"),
        ("profile", "oidc-config"),
        ("profile", "show"),
        ("profile", "verify"),
        ("route", "get"),
        ("route", "list"),
        ("route", "ls"),
        ("schema",),
        ("security", "settings"),
        ("system", "info"),
        ("system", "whoami"),
        ("user", "get"),
        ("user", "list"),
        ("user", "ls"),
        ("user", "me"),
        ("user-group", "get"),
        ("user-group", "list"),
        ("user-group", "ls"),
        ("user-role", "authority-list"),
        ("user-role", "get"),
        ("user-role", "list"),
        ("user-role", "ls"),
    }
)

_HELP_FLAGS: Final = frozenset({"--help", "-h", "--version", "-V"})
_READONLY_TRUTHY: Final = frozenset({"1", "true", "yes", "on"})


class CliResult(BaseModel):
    """Outcome of one `dhis2` CLI invocation: the process exit code and captured streams."""

    model_config = ConfigDict(frozen=True)

    exit_code: int
    stdout: str
    stderr: str


def _resolve_binary() -> str | None:
    """Locate the `dhis2` executable: env override, then the active venv, then `PATH`."""
    override = os.environ.get(DHIS2_CLI_BIN_ENV)
    if override:
        return override
    sibling = Path(sys.executable).with_name("dhis2")
    if sibling.exists():
        return str(sibling)
    return shutil.which("dhis2")


def _command_path(args: list[str]) -> tuple[str, ...]:
    """Return the leading positional tokens (the command path), stopping at the first option."""
    path: list[str] = []
    for token in args:
        if token.startswith("-"):
            break
        path.append(token)
    return tuple(path)


def _is_help_or_version(args: list[str]) -> bool:
    """Return True when the invocation only asks for help or version output."""
    return any(token in _HELP_FLAGS for token in args)


_DISK_WRITE_FLAGS = frozenset({"--output", "-o"})


def _writes_to_disk(args: list[str]) -> bool:
    """Return True if argv writes to a local file (e.g. `metadata list --output` / `export -o`)."""
    return any(token in _DISK_WRITE_FLAGS or token.startswith(("--output=", "-o=")) for token in args)


def is_read_only(args: list[str]) -> bool:
    """Return True when `args` targets a known read-only command (or help/version/discovery).

    A read command that writes a local file (`--output`/`-o`) is NOT read-only — under
    DHIS2_MCP_READONLY a confused model could otherwise overwrite arbitrary host files.
    """
    if not args or _is_help_or_version(args):
        return True
    if _writes_to_disk(args):
        return False
    path = _command_path(args)
    return any(path[: len(prefix)] == prefix for prefix in READ_ONLY_COMMANDS)


def _build_argv(binary: str, args: list[str], profile: str | None) -> list[str]:
    """Prepend `--json` (deduped) and optional `-p <profile>` as leading global flags."""
    argv = [binary]
    if "--json" not in args and "-j" not in args:
        argv.append("--json")
    if profile:
        argv += ["-p", profile]
    argv += args
    return argv


def readonly_from_env() -> bool:
    """Return True when `DHIS2_MCP_READONLY` is set to a truthy value."""
    return os.environ.get(READONLY_ENV, "").strip().lower() in _READONLY_TRUTHY


def timeout_from_env() -> float:
    """Return the per-command timeout from `DHIS2_MCP_CLI_TIMEOUT`, or the default."""
    raw = os.environ.get(TIMEOUT_ENV)
    if not raw:
        return DEFAULT_TIMEOUT_SECONDS
    try:
        value = float(raw)
    except ValueError:
        return DEFAULT_TIMEOUT_SECONDS
    return value if value > 0 else DEFAULT_TIMEOUT_SECONDS


def _compact_json(text: str) -> str:
    """Re-serialize JSON output without indentation to cut tokens for the model; pass non-JSON through.

    The CLI pretty-prints `--json` with `indent=2`; that whitespace ~doubles the tokens a model
    has to read. Compacting a large list/object response is a cheap, lossless win on the read side.
    """
    stripped = text.lstrip()
    if not stripped or stripped[0] not in "[{":
        return text
    try:
        return json.dumps(json.loads(text), separators=(",", ":"), ensure_ascii=False)
    except ValueError:
        return text


async def run_cli(
    args: list[str],
    profile: str | None = None,
    *,
    timeout: float = DEFAULT_TIMEOUT_SECONDS,
    read_only: bool = False,
) -> CliResult:
    """Run `dhis2 --json [-p <profile>] <args>` as a subprocess and capture the result."""
    # Some models pack the command into the FIRST arg as one string — either the whole command
    # ("metadata list dataElements --count") or just the command path with the flags following
    # as separate args (["metadata list organisationUnits", "--all", ...]). The command position
    # never holds a legitimate space, so split a space-containing first token (keeping any later
    # args) — so the read-only guard and the CLI both see real tokens.
    if args and " " in args[0]:
        with contextlib.suppress(ValueError):
            args = [*shlex.split(args[0]), *args[1:]]
    if read_only and not is_read_only(args):
        blocked = " ".join(args) or "<empty>"
        reason = "writes a local file (--output/-o)" if _writes_to_disk(args) else "non-read commands"
        return CliResult(
            exit_code=EXIT_REFUSED,
            stdout="",
            stderr=(
                f"refused: read-only mode ({READONLY_ENV}=1) blocks {reason}: {blocked!r}. "
                "Allowed: list/get/show/info/whoami/query/find/tree/members/diff and similar "
                f"reads (without --output), or any `--help`. Unset {READONLY_ENV} for full access."
            ),
        )
    binary = _resolve_binary()
    if binary is None:
        return CliResult(
            exit_code=EXIT_CLI_NOT_FOUND,
            stdout="",
            stderr=(
                "dhis2 CLI not found. Install dhis2w-cli (a dependency of this bridge) or set "
                f"{DHIS2_CLI_BIN_ENV} to the `dhis2` executable path."
            ),
        )
    argv = _build_argv(binary, args, profile)
    try:
        proc = await asyncio.create_subprocess_exec(
            *argv,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=dict(os.environ),
        )
    except (FileNotFoundError, PermissionError) as exc:
        return CliResult(
            exit_code=EXIT_CLI_NOT_FOUND,
            stdout="",
            stderr=f"could not execute dhis2 CLI at {binary!r}: {exc}. Set {DHIS2_CLI_BIN_ENV}.",
        )
    try:
        stdout_raw, stderr_raw = await asyncio.wait_for(proc.communicate(), timeout=timeout)
    except TimeoutError:
        proc.kill()
        await proc.wait()
        return CliResult(
            exit_code=EXIT_TIMEOUT,
            stdout="",
            stderr=f"`dhis2` timed out after {timeout:g}s (set {TIMEOUT_ENV} to adjust).",
        )
    exit_code = proc.returncode if proc.returncode is not None else EXIT_TIMEOUT
    stdout = stdout_raw.decode(errors="replace")
    return CliResult(
        exit_code=exit_code,
        stdout=_compact_json(stdout) if exit_code == 0 else stdout,
        stderr=stderr_raw.decode(errors="replace"),
    )


def register(mcp: Any) -> None:
    """Register the single `dhis2_cli` tool on the FastMCP server."""

    @mcp.tool()
    async def dhis2_cli(args: list[str], profile: str | None = None) -> CliResult:
        """Run a `dhis2` CLI command against a DHIS2 server.

        Never answer counts or data from memory — always run a command.

        OUTPUT CONTRACT (read this first):
          - `--json` is added automatically. On success exit_code is 0 and `stdout` is JSON — parse it.
          - Any non-zero exit_code is a failure: the message is in `stderr` (plain text, NOT JSON).
          - `--help`/`--version` exit 0 with human text (that is discovery output, not data).

        COMMON READS (go direct, no discovery needed):
          - Count any resource: dhis2_cli(["metadata", "list", "<type>", "--count"])
                                -> {"resource": "<type>", "total": N}
          - List a resource:    dhis2_cli(["metadata", "list", "<type>"])
          - One object by UID:  dhis2_cli(["metadata", "get", "<type>", "<uid>"])
          - Find by name/code:  dhis2_cli(["metadata", "search", "<text>"])  (cross-type; the best
                                name->UID resolver). What references a UID:
                                dhis2_cli(["metadata", "usage", "<uid>"])
          - Server version:     dhis2_cli(["system", "info"])
          - Current user:       dhis2_cli(["system", "whoami"])

        The verb is `get` (NOT `show`). Listing ANY resource is `metadata list <type>` —
        there is NO `metadata <type> list`.

        RESOURCE TYPES are plural camelCase and DISTINCT: dataElements, indicators, programs,
        dataSets, organisationUnits, organisationUnitLevels, optionSets, categories,
        categoryOptions, trackedEntityTypes, ... (optionSets != categories != categoryOptions).
        If you are not 100% sure of the exact name, run dhis2_cli(["metadata", "type", "list"])
        and copy it verbatim — do NOT guess.

        NARROWING a list (do it in ONE call — avoid fetch-then-refetch):
          - Pick fields:  --fields id,code,name,description   (default is id,name)
                          presets: :identifiable, :nameable, :owner, :all; exclude with :all,!sharing
          - Filter:       --filter <prop>:<op>:<value>        (e.g. domainType:eq:AGGREGATE)
                ops: eq (exact), ilike (contains), $ilike (starts-with), ilike$ (ends-with),
                     token (word), in:[a,b] (any-of), null / !null (presence). Drop `i` for case-sensitive.
                "contains anc" -> name:ilike:anc   "starts with anc" -> name:$ilike:anc
                nested paths use dots (X belonging to Y): dataSetElements.dataSet.id:eq:<uid>,
                     categoryCombo.id:eq:<uid>, program.id:eq:<uid>
          - Every page:   --all                                (NOT --all-streams)
          - Dump to file: --output <file>   -> {"written": N, "path": ...}. Use for "give me ALL
                          as JSON": report the path; do NOT print the rows yourself.
          - Whole-catalog `metadata export` is HUGE (tens of MB with org-unit geometry): ALWAYS pass
            -o <file> and report the path — never export to stdout.

        ANALYTICS / DATA (aggregate values, event/tracker data) need UIDs, not names:
          dhis2_cli(["analytics", "query", "--dim", "dx:<uid>",
                     "--dim", "pe:LAST_12_MONTHS", "--dim", "ou:<uid>"])
          Flags are --dim (repeatable), NOT --dx/--pe/--ou. Resolve each name to a UID FIRST:
          dhis2_cli(["metadata", "list", "<type>", "--filter", "name:ilike:<text>", "--fields", "id,name"]).

        DISCOVER when unsure (the CLI is self-documenting):
          dhis2_cli(["--help"])                      -> command groups
          dhis2_cli(["metadata", "--help"])          -> drill into a group
          dhis2_cli(["metadata", "list", "--help"])  -> a command's options
          Shape: [<group>, <subgroup?>, <verb>, <args/options...>].

        RESPONDING: the host already shows the user every call and its full output, so do NOT
        re-print large JSON or long lists — just answer (the count, the few rows asked for) or
        summarize briefly. Print raw output only if the user asks for "the raw JSON"/"the full list".
        Prefer narrowing (--count, --filter, --fields) over fetching everything and summarizing after.

        CONNECTING: pass `profile` to select a configured profile (e.g. profile="prod"), or rely on
        the server default. On "no DHIS2 profile is configured", do NOT invent credentials — ask the
        user to run `dhis2 profile add` / `profile bootstrap`.

        WRITES change live data — confirm intent first; refused under DHIS2_MCP_READONLY=1.
          - Author with: metadata <type-kebab> create --name X --short-name X ... — e.g.
            metadata data-elements create --name "Cases" --short-name "Cases" --value-type NUMBER.
            There is NO `metadata create <type>`. Find the required flags with
            `metadata <type-kebab> create --help` (kebab-case: data-elements, data-sets,
            organisation-units, category-combos, indicators, ...).
          - create/get/rename/delete return JSON; relationship verbs (add-element, add-member,
            add-to-ou, ...) print a short summary line, not JSON.
          - Share with the SINGULAR type: metadata share dataElement <uid> --public-access rw------

        Args:
            args: CLI arguments already split into tokens (no shell quoting).
            profile: Optional profile name, injected as `-p <profile>`.
        """
        return await run_cli(
            args,
            profile,
            timeout=timeout_from_env(),
            read_only=readonly_from_env(),
        )
