"""The single `dhis2_cli` MCP tool: run the `d2w` CLI as a subprocess.

Small local models cannot afford the full `dhis2w-mcp` server's ~337 typed tools (≈50-65k
tokens of schema loaded up front). This module exposes ONE tool instead: the model discovers
the command surface progressively with `--help` and runs commands with `--json`. Everything
stays on the host — the bridge spawns the local `d2w` binary and never sends data anywhere.

`READ_ONLY_COMMANDS` is the allowlist consulted when `DHIS2_MCP_READONLY=1`: a fail-closed
set of read-only command paths generated by introspecting the Typer/Click command tree
(identical across the v41/v42/v43 plugin trees). `tests/test_cli_bridge.py` re-derives it from
the live tree so it cannot silently drift.
"""

from __future__ import annotations

import asyncio
import contextlib
import json
import os
import shlex
import shutil
import sys
from pathlib import Path
from typing import Any, Final
from urllib.parse import urlsplit

from pydantic import BaseModel, ConfigDict

#: Environment variable naming an explicit `d2w` executable (overrides auto-discovery).
DHIS2_CLI_BIN_ENV: Final = "DHIS2_CLI_BIN"
#: Environment variable that, when truthy, restricts the bridge to read-only commands.
READONLY_ENV: Final = "DHIS2_MCP_READONLY"
#: Environment variable overriding the comma-separated protected-host patterns. An empty value
#: disables the guard; an unset value falls back to `DEFAULT_PROTECTED_HOSTS`.
PROTECTED_HOSTS_ENV: Final = "DHIS2_MCP_PROTECTED_HOSTS"
#: Hosts on which mutating commands are refused regardless of `DHIS2_MCP_READONLY` — the shared
#: public DHIS2 demo/play instances. A host matches when it equals a pattern or is a subdomain of
#: one. This is a structural backstop so no harness wiring can write to the public demo.
DEFAULT_PROTECTED_HOSTS: Final[tuple[str, ...]] = ("play.dhis2.org", "play.im.dhis2.org", "debug.dhis2.org")
#: Environment variable overriding the per-command timeout, in seconds.
TIMEOUT_ENV: Final = "DHIS2_MCP_CLI_TIMEOUT"
#: Default per-command timeout when `TIMEOUT_ENV` is unset or invalid.
DEFAULT_TIMEOUT_SECONDS: Final = 120.0

#: Exit code returned when a command exceeds its timeout (matches coreutils `timeout`).
EXIT_TIMEOUT: Final = 124
#: Exit code returned when read-only mode refuses a mutating command.
EXIT_REFUSED: Final = 126
#: Exit code returned when the `d2w` binary cannot be located or executed.
EXIT_CLI_NOT_FOUND: Final = 127

#: Read-only command paths permitted under `DHIS2_MCP_READONLY=1`. Each tuple is a leaf
#: command path; a request is allowed when one of these is a prefix of its command path.
#: Generated from the Typer command tree — keep in sync via the drift test.
READ_ONLY_COMMANDS: Final[frozenset[tuple[str, ...]]] = frozenset(
    {
        ("analytics", "enrollments", "query"),
        ("analytics", "events", "query"),
        ("analytics", "outlier-detection"),
        ("analytics", "query"),
        ("analytics", "tracked-entities", "query"),
        ("apps", "hub-list"),
        ("apps", "list"),
        ("apps", "ls"),
        ("data", "aggregate", "get"),
        ("data", "tracker", "enrollment", "list"),
        ("data", "tracker", "enrollment", "ls"),
        ("data", "tracker", "event", "list"),
        ("data", "tracker", "event", "ls"),
        ("data", "tracker", "get"),
        ("data", "tracker", "list"),
        ("data", "tracker", "ls"),
        ("data", "tracker", "relationship", "list"),
        ("data", "tracker", "relationship", "ls"),
        ("datastore", "namespaces"),
        ("datastore", "keys"),
        ("datastore", "get"),
        ("dev", "codegen", "diff"),
        ("customize", "show"),
        ("doctor", "bugs"),
        ("doctor", "integrity"),
        ("doctor", "metadata"),
        ("files", "documents", "get"),
        ("files", "documents", "list"),
        ("files", "documents", "ls"),
        ("files", "resources", "get"),
        ("maintenance", "dataintegrity", "list"),
        ("maintenance", "dataintegrity", "ls"),
        ("maintenance", "task", "list"),
        ("maintenance", "task", "ls"),
        ("maintenance", "task", "status"),
        ("maintenance", "task", "types"),
        ("maintenance", "validation", "result", "get"),
        ("maintenance", "validation", "result", "list"),
        ("maintenance", "validation", "result", "ls"),
        ("messaging", "get"),
        ("messaging", "list"),
        ("messaging", "ls"),
        ("metadata", "attributes", "find"),
        ("metadata", "attributes", "get"),
        ("metadata", "categories", "get"),
        ("metadata", "category-combos", "get"),
        ("metadata", "category-option-combos", "get"),
        ("metadata", "category-option-combos", "list-for-combo"),
        ("metadata", "category-option-group-sets", "get"),
        ("metadata", "category-option-groups", "get"),
        ("metadata", "category-option-groups", "members"),
        ("metadata", "category-options", "get"),
        ("metadata", "dashboards", "get"),
        ("metadata", "data-element-group-sets", "get"),
        ("metadata", "data-element-groups", "get"),
        ("metadata", "data-element-groups", "members"),
        ("metadata", "data-elements", "get"),
        ("metadata", "data-sets", "get"),
        ("metadata", "diff"),
        ("metadata", "diff-profiles"),
        ("metadata", "get"),
        ("metadata", "indicator-group-sets", "get"),
        ("metadata", "indicator-groups", "get"),
        ("metadata", "indicator-groups", "members"),
        ("metadata", "indicators", "get"),
        ("metadata", "legend-sets", "get"),
        ("metadata", "list"),
        ("metadata", "ls"),
        ("metadata", "maps", "get"),
        ("metadata", "option-sets", "attributes", "find"),
        ("metadata", "option-sets", "attributes", "get"),
        ("metadata", "option-sets", "find"),
        ("metadata", "option-sets", "get"),
        ("metadata", "organisation-unit-group-sets", "get"),
        ("metadata", "organisation-unit-groups", "get"),
        ("metadata", "organisation-unit-groups", "members"),
        ("metadata", "organisation-unit-levels", "get"),
        ("metadata", "organisation-units", "get"),
        ("metadata", "organisation-units", "tree"),
        ("metadata", "predictor-groups", "get"),
        ("metadata", "predictor-groups", "members"),
        ("metadata", "predictors", "get"),
        ("metadata", "program-indicator-groups", "get"),
        ("metadata", "program-indicator-groups", "members"),
        ("metadata", "program-indicators", "get"),
        ("metadata", "program-rules", "get"),
        ("metadata", "program-rules", "vars-for"),
        ("metadata", "program-rules", "where-de-is-used"),
        ("metadata", "program-stages", "get"),
        ("metadata", "programs", "get"),
        ("metadata", "export"),
        ("metadata", "search"),
        ("metadata", "usage"),
        ("metadata", "sections", "get"),
        ("metadata", "sql-views", "get"),
        ("metadata", "tracked-entity-attributes", "get"),
        ("metadata", "tracked-entity-types", "get"),
        ("metadata", "type", "list"),
        ("metadata", "type", "ls"),
        ("metadata", "validation-rule-groups", "get"),
        ("metadata", "validation-rule-groups", "members"),
        ("metadata", "validation-rules", "get"),
        ("metadata", "visualizations", "get"),
        ("profile", "list"),
        ("profile", "ls"),
        ("profile", "show"),
        ("profile", "verify"),
        ("route", "get"),
        ("route", "list"),
        ("route", "ls"),
        ("schema",),
        ("security", "settings"),
        ("system", "info"),
        ("system", "whoami"),
        ("system", "settings", "get"),
        ("system", "settings", "list"),
        ("system", "settings", "ls"),
        ("user", "get"),
        ("user", "list"),
        ("user", "ls"),
        ("user", "group", "get"),
        ("user", "group", "list"),
        ("user", "group", "ls"),
        ("user", "role", "authority-list"),
        ("user", "role", "get"),
        ("user", "role", "list"),
        ("user", "role", "ls"),
    }
)

_HELP_FLAGS: Final = frozenset({"--help", "-h", "--version", "-V"})
_READONLY_TRUTHY: Final = frozenset({"1", "true", "yes", "on"})


class CliResult(BaseModel):
    """Outcome of one `d2w` CLI invocation: the process exit code and captured streams."""

    model_config = ConfigDict(frozen=True)

    exit_code: int
    stdout: str
    stderr: str


def _resolve_binary() -> str | None:
    """Locate the `d2w` executable: env override, then the active venv, then `PATH`."""
    override = os.environ.get(DHIS2_CLI_BIN_ENV)
    if override:
        return override
    sibling = Path(sys.executable).with_name("d2w")
    if sibling.exists():
        return str(sibling)
    return shutil.which("d2w")


def _command_path(args: list[str]) -> tuple[str, ...]:
    """Return the leading positional tokens (the command path), stopping at the first option."""
    path: list[str] = []
    for token in args:
        if token.startswith("-"):
            break
        path.append(token)
    return tuple(path)


def _first_option(args: list[str]) -> str | None:
    """Return the first option-like token (starts with `-`), or None when the args are all positional."""
    for token in args:
        if token.startswith("-"):
            return token
    return None


def _is_help_or_version(args: list[str]) -> bool:
    """Return True only when the FIRST option is a standalone help/version flag — genuine discovery.

    Deciding read-vs-write by the command VERB, not by scanning every token, is what makes this safe:
    a `--help` used as an option VALUE (`create --name --help`) is NOT the first option (a
    value-taking `--name` precedes it), so it does not short-circuit and the write command is still
    classified — and refused — as a write. Fail-closed: help is honoured only when it leads the flags.
    """
    return _first_option(args) in _HELP_FLAGS


#: Long option names that make a command write to the local filesystem. Matched against the
#: option NAME (the part before `=`), so `--output=PATH` is caught while the unrelated
#: read-only `--output-id-scheme=SCHEME` is not.
_DISK_WRITE_FLAGS: Final[frozenset[str]] = frozenset(
    {"--output", "--output-dir", "--output-root", "--out", "--directory", "--file"}
)


def _is_disk_write_token(token: str) -> bool:
    """Return True when `token` is an output option in any form Click accepts.

    `-o` is the short form of every output option in the command tree (`--output`, `--out`,
    `--output-dir`), and Click accepts its value attached (`-oPATH`) as well as separated
    (`-o PATH`) and joined (`-o=PATH`), so every single-dash token starting with `-o` counts.
    Long forms match on the option name, which catches `--output=PATH` and leaves the read-only
    `--output-id-scheme` alone.
    """
    if token.startswith("-o") and not token.startswith("--"):
        return True
    return token.split("=", 1)[0] in _DISK_WRITE_FLAGS


def _writes_to_disk(args: list[str]) -> bool:
    """Return True if argv writes to a local file (e.g. `metadata list --output` / `export -oPATH`)."""
    return any(_is_disk_write_token(token) for token in args)


def is_read_only(args: list[str]) -> bool:
    """Return True when `args` targets a known read-only command (or help/version/discovery).

    A read command that writes a local file (`--output`/`-o` and the other output options) is
    NOT read-only — under DHIS2_MCP_READONLY a confused model could otherwise overwrite
    arbitrary host files.
    """
    if not args or _is_help_or_version(args):
        return True
    if _writes_to_disk(args):
        return False
    path = _command_path(args)
    return any(path[: len(prefix)] == prefix for prefix in READ_ONLY_COMMANDS)


#: Root profile flags. The tool's `profile` parameter is the only way to choose a profile, so
#: these are refused inside `args` — see `_profile_in_args_refusal`.
_PROFILE_FLAGS: Final[frozenset[str]] = frozenset({"--profile", "-p"})


def _profile_flag_in_args(args: list[str]) -> str | None:
    """Return the root profile flag carried by `args`, or None when there is none.

    Click reads root options only up to the first positional token, so a profile flag reaches the
    root callback only ahead of the command path — that leading option region is what this scans,
    in every form Click accepts: `--profile NAME`, `--profile=NAME`, `-p NAME`, `-pNAME`. A `-p`
    after the command path belongs to that subcommand (`--program`, `--predictor`) and is left
    alone.
    """
    for token in args:
        if token == "--" or not token.startswith("-"):
            return None
        if token in _PROFILE_FLAGS or token.startswith("--profile="):
            return token
        if token.startswith("-p") and not token.startswith("--"):
            return token
    return None


def _profile_in_args_refusal(args: list[str]) -> CliResult | None:
    """Return a refusal when `args` carries a root profile flag, else None.

    The tool's `profile` parameter is the single source of the target profile: it is what the
    protected-host guard resolves and what `_build_argv` injects. A profile flag inside `args`
    lands after the injected one and wins at the Click parser, so the guarded host and the
    executed host would be different instances. Refused before anything is built or spawned.
    """
    token = _profile_flag_in_args(args)
    if token is None:
        return None
    return CliResult(
        exit_code=EXIT_REFUSED,
        stdout="",
        stderr=(
            f"refused: {token!r} in args. Profile is chosen by the profile parameter, not inside "
            'args. Call the tool with profile="<name>" and drop the flag from args.'
        ),
    )


def _build_argv(binary: str, args: list[str], profile: str | None) -> list[str]:
    """Prepend `--json` (deduped) and optional `-p <profile>` as leading global flags.

    `args` arrives free of root profile flags — `run_cli` refuses those before anything is built
    or spawned — so the injected `-p <profile>` is the only profile Click sees.
    """
    argv = [binary]
    if "--json" not in args and "-j" not in args:
        argv.append("--json")
    if profile:
        argv += ["-p", profile]
    argv += args
    return argv


def readonly_from_env() -> bool:
    """Return True when `DHIS2_MCP_READONLY` is set to a truthy value."""
    return os.environ.get(READONLY_ENV, "").strip().lower() in _READONLY_TRUTHY


def protected_hosts() -> tuple[str, ...]:
    """Return the write-protected host patterns (`DHIS2_MCP_PROTECTED_HOSTS` override, else defaults)."""
    raw = os.environ.get(PROTECTED_HOSTS_ENV)
    if raw is None:
        return DEFAULT_PROTECTED_HOSTS
    return tuple(host.strip().lower() for host in raw.split(",") if host.strip())


def _host_is_protected(host: str, patterns: tuple[str, ...]) -> bool:
    """Return True when `host` equals or is a subdomain of any protected pattern."""
    host = host.lower()
    return any(host == pattern or host.endswith(f".{pattern}") for pattern in patterns)


def _resolve_base_url(profile: str | None) -> str | None:
    """Resolve the active profile's base URL in-process; None if it cannot be resolved.

    Uses the same precedence chain as the `d2w` CLI (`resolve_profile`). Resolved fresh on every
    mutating command — reading the local TOML is cheap, and the MCP server is long-lived, so a
    profile edit made while it runs must be reflected by the very next write guard check. Fails
    open — a resolution error returns None so the underlying command runs and reports its own
    error, rather than the guard blocking on a transient lookup failure.
    """
    from dhis2w_core.profile import resolve_profile  # lazy: only when a mutating command runs

    try:
        return resolve_profile(profile).base_url
    except Exception:  # noqa: BLE001 — fail open: never block a command on a host-resolution hiccup
        return None


def _protected_host_refusal(args: list[str], profile: str | None) -> CliResult | None:
    """Return a refusal when `args` mutates against a protected host, else None."""
    base_url = _resolve_base_url(profile)
    if base_url is None:
        return None
    host = urlsplit(base_url).hostname or ""
    if not _host_is_protected(host, protected_hosts()):
        return None
    blocked = " ".join(args) or "<empty>"
    return CliResult(
        exit_code=EXIT_REFUSED,
        stdout="",
        stderr=(
            f"refused: {host!r} is a write-protected host; mutating command blocked: {blocked!r}. "
            f"Reads are allowed. Point the profile at a local instance to write, or override "
            f"{PROTECTED_HOSTS_ENV} (empty value disables the guard)."
        ),
    )


def timeout_from_env() -> float:
    """Return the per-command timeout from `DHIS2_MCP_CLI_TIMEOUT`, or the default."""
    raw = os.environ.get(TIMEOUT_ENV)
    if not raw:
        return DEFAULT_TIMEOUT_SECONDS
    try:
        value = float(raw)
    except ValueError:
        return DEFAULT_TIMEOUT_SECONDS
    return value if value > 0 else DEFAULT_TIMEOUT_SECONDS


def _compact_json(text: str) -> str:
    """Re-serialize JSON output without indentation to cut tokens for the model; pass non-JSON through.

    The CLI pretty-prints `--json` with `indent=2`; that whitespace ~doubles the tokens a model
    has to read. Compacting a large list/object response is a cheap, lossless win on the read side.
    """
    stripped = text.lstrip()
    if not stripped or stripped[0] not in "[{":
        return text
    try:
        return json.dumps(json.loads(text), separators=(",", ":"), ensure_ascii=False)
    except ValueError:
        return text


async def run_cli(
    args: list[str],
    profile: str | None = None,
    *,
    timeout: float = DEFAULT_TIMEOUT_SECONDS,
    read_only: bool = False,
) -> CliResult:
    """Run `d2w --json [-p <profile>] <args>` as a subprocess and capture the result."""
    # Some models pack the command into the FIRST arg as one string — either the whole command
    # ("metadata list dataElements --count") or just the command path with the flags following
    # as separate args (["metadata list organisationUnits", "--all", ...]). The command position
    # never holds a legitimate space, so split a space-containing first token (keeping any later
    # args) — so the read-only guard and the CLI both see real tokens.
    if args and " " in args[0]:
        with contextlib.suppress(ValueError):
            args = [*shlex.split(args[0]), *args[1:]]
    profile_refusal = _profile_in_args_refusal(args)
    if profile_refusal is not None:
        return profile_refusal
    read = is_read_only(args)
    if read_only and not read:
        blocked = " ".join(args) or "<empty>"
        reason = "writes a local file (an output option)" if _writes_to_disk(args) else "non-read commands"
        return CliResult(
            exit_code=EXIT_REFUSED,
            stdout="",
            stderr=(
                f"refused: read-only mode ({READONLY_ENV}=1) blocks {reason}: {blocked!r}. "
                "Allowed: list/get/show/info/whoami/query/find/tree/members/diff and similar "
                f"reads (without --output), or any `--help`. Unset {READONLY_ENV} for full access."
            ),
        )
    # Structural backstop: refuse mutating commands against a shared public host regardless of
    # read-only mode, so no harness can write to the public demo by mis-wiring env vars.
    if not read:
        refusal = _protected_host_refusal(args, profile)
        if refusal is not None:
            return refusal
    binary = _resolve_binary()
    if binary is None:
        return CliResult(
            exit_code=EXIT_CLI_NOT_FOUND,
            stdout="",
            stderr=(
                "d2w CLI not found. Install dhis2w-cli (a dependency of this bridge) or set "
                f"{DHIS2_CLI_BIN_ENV} to the `d2w` executable path."
            ),
        )
    argv = _build_argv(binary, args, profile)
    try:
        proc = await asyncio.create_subprocess_exec(
            *argv,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=dict(os.environ),
        )
    except (FileNotFoundError, PermissionError) as exc:
        return CliResult(
            exit_code=EXIT_CLI_NOT_FOUND,
            stdout="",
            stderr=f"could not execute d2w CLI at {binary!r}: {exc}. Set {DHIS2_CLI_BIN_ENV}.",
        )
    try:
        stdout_raw, stderr_raw = await asyncio.wait_for(proc.communicate(), timeout=timeout)
    except TimeoutError:
        proc.kill()
        await proc.wait()
        return CliResult(
            exit_code=EXIT_TIMEOUT,
            stdout="",
            stderr=f"`d2w` timed out after {timeout:g}s (set {TIMEOUT_ENV} to adjust).",
        )
    exit_code = proc.returncode if proc.returncode is not None else EXIT_TIMEOUT
    stdout = stdout_raw.decode(errors="replace")
    return CliResult(
        exit_code=exit_code,
        stdout=_compact_json(stdout) if exit_code == 0 else stdout,
        stderr=stderr_raw.decode(errors="replace"),
    )


def register(mcp: Any) -> None:
    """Register the single `dhis2_cli` tool on the FastMCP server."""

    @mcp.tool()
    async def dhis2_cli(args: list[str], profile: str | None = None) -> CliResult:
        """Run a `d2w` CLI command against a DHIS2 server.

        Never answer counts or data from memory — always run a command.

        OUTPUT CONTRACT (read this first):
          - `--json` is added automatically. On success exit_code is 0 and `stdout` is JSON — parse it.
          - Any non-zero exit_code is a failure: the message is in `stderr` (plain text, NOT JSON).
          - `--help`/`--version` exit 0 with human text (that is discovery output, not data).

        COMMON READS (go direct, no discovery needed):
          - Count any resource: dhis2_cli(["metadata", "list", "<type>", "--count"])
                                -> {"resource": "<type>", "total": N}
          - List a resource:    dhis2_cli(["metadata", "list", "<type>"])
          - One object by UID:  dhis2_cli(["metadata", "get", "<type>", "<uid>"])
          - Find by name/code:  dhis2_cli(["metadata", "search", "<text>"])  (cross-type; the best
                                name->UID resolver). What references a UID:
                                dhis2_cli(["metadata", "usage", "<uid>"])
          - Server version:     dhis2_cli(["system", "info"])
          - Current user:       dhis2_cli(["system", "whoami"])
          - Fields of a type:   dhis2_cli(["schema", "<type>"])  -> the typed field list for <type>
                                (e.g. dataElement, trackerEvent). Use this to answer "what fields
                                does X have" / "the schema of X" — do NOT guess field names.

        The verb is `get` (NOT `show`). Listing ANY resource is `metadata list <type>` —
        there is NO `metadata <type> list`.

        RESOURCE TYPES are plural camelCase and DISTINCT: dataElements, indicators, programs,
        dataSets, organisationUnits, organisationUnitLevels, optionSets, categories,
        categoryOptions, trackedEntityTypes, ... (optionSets != categories != categoryOptions).
        If you are not 100% sure of the exact name, run dhis2_cli(["metadata", "type", "list"])
        and copy it verbatim — do NOT guess.

        NARROWING a list (do it in ONE call — avoid fetch-then-refetch):
          - Pick fields:  --fields id,code,name,description   (default is id,name)
                          presets: :identifiable, :nameable, :owner, :all; exclude with :all,!sharing
          - Filter:       --filter <prop>:<op>:<value>        (e.g. domainType:eq:AGGREGATE)
                ops: eq (exact), ilike (contains), $ilike (starts-with), ilike$ (ends-with),
                     token (word), in:[a,b] (any-of), null / !null (presence). Drop `i` for case-sensitive.
                "contains anc" -> name:ilike:anc   "starts with anc" -> name:$ilike:anc
                nested paths use dots (X belonging to Y): dataSetElements.dataSet.id:eq:<uid>,
                     categoryCombo.id:eq:<uid>, program.id:eq:<uid>
          - Every page:   --all                                (NOT --all-streams)
          - Dump to file: --output <file>   -> {"written": N, "path": ...}. Use for "give me ALL
                          as JSON": report the path; do NOT print the rows yourself.
          - Whole-catalog `metadata export` is HUGE (tens of MB with org-unit geometry): ALWAYS pass
            -o <file> and report the path — never export to stdout.

        ANALYTICS / DATA (aggregate values, event/tracker data) need UIDs, not names:
          dhis2_cli(["analytics", "query", "--dim", "dx:<uid>",
                     "--dim", "pe:LAST_12_MONTHS", "--dim", "ou:<uid>"])
          Flags are --dim (repeatable), NOT --dx/--pe/--ou. Resolve each name to a UID FIRST:
          dhis2_cli(["metadata", "list", "<type>", "--filter", "name:ilike:<text>", "--fields", "id,name"]).

        DISCOVER when unsure (the CLI is self-documenting):
          dhis2_cli(["--help"])                      -> command groups
          dhis2_cli(["metadata", "--help"])          -> drill into a group
          dhis2_cli(["metadata", "list", "--help"])  -> a command's options
          Shape: [<group>, <subgroup?>, <verb>, <args/options...>].

        RESPONDING: the host already shows the user every call and its full output, so do NOT
        re-print large JSON or long lists — just answer (the count, the few rows asked for) or
        summarize briefly. Print raw output only if the user asks for "the raw JSON"/"the full list".
        Prefer narrowing (--count, --filter, --fields) over fetching everything and summarizing after.

        CONNECTING: pass `profile` to select a configured profile (e.g. profile="prod"), or rely on
        the server default. On "no DHIS2 profile is configured", do NOT invent credentials — ask the
        user to run `d2w profile add` / `profile bootstrap`. Never put `-p` / `--profile` in `args`:
        a profile flag there is refused, because `profile` is the only source of the target profile.

        WRITES change live data — confirm intent first; refused under DHIS2_MCP_READONLY=1.
          - Author with: metadata <type-kebab> create --name X --short-name X ... — e.g.
            metadata data-elements create --name "Cases" --short-name "Cases" --value-type NUMBER.
            There is NO `metadata create <type>`. Find the required flags with
            `metadata <type-kebab> create --help` (kebab-case: data-elements, data-sets,
            organisation-units, category-combos, indicators, ...).
          - create/get/rename/delete return JSON; relationship verbs (add-element, add-member,
            add-to-ou, ...) print a short summary line, not JSON.
          - Share with the SINGULAR type: metadata share dataElement <uid> --public-access rw------

        Args:
            args: CLI arguments already split into tokens (no shell quoting).
            profile: Optional profile name, injected as `-p <profile>`.
        """
        return await run_cli(
            args,
            profile,
            timeout=timeout_from_env(),
            read_only=readonly_from_env(),
        )
