// Generated by d2w fhir generate - do not edit

Instance: QuestionnaireResponse-A03MvHHogjR-example-1
InstanceOf: D2TrackerEventResponse
Title: "Example response - Child Programme - Birth"
Description: "Example QuestionnaireResponse against the DHIS2 tracker program stage Child Programme - Birth (A03MvHHogjR)."
Usage: #example
* id = "A03MvHHogjR-example-1"
* extension[D2FormType].valueCode = #tracker-event
* extension[D2TrackerEnrollment].valueIdentifier.system = $DHIS2-TRACKER-ENROLLMENT
* extension[D2TrackerEnrollment].valueIdentifier.value = "VJV3arKomV0"
* extension[D2OrganisationUnit].valueReference = Reference(Location/qhqAxPSTUXp)
* questionnaire = "http://example.org/fhir/examples/patient-summary/Questionnaire/A03MvHHogjR"
* status = #completed
* subject.type = "Patient"
* subject.identifier.system = $DHIS2-TE
* subject.identifier.value = "yhpvt4pX4xD"
* authored = "2026-08-20T12:00:00Z"
* item[+].linkId = "a3kGcGDCuk6"
* item[=].answer[+].valueDecimal = 23.3
* item[+].linkId = "H6uSAMO5WLD"
* item[=].answer[+].valueString = "Example MCH Apgar comment"
* item[+].linkId = "UXz7xuGCEhU"
* item[=].answer[+].valueDecimal = 66.6
* item[+].linkId = "wQLfBvPrXqq"
* item[=].answer[+].valueCoding = D2OS_f38bstJioPs_CS#ww8JVblo4SI "Others"
* item[+].linkId = "bx6fsa0t90x"
* item[=].answer[+].valueBoolean = true
* item[+].linkId = "ebaJjqltK5N"
* item[=].answer[+].valueCoding = D2OS_kzgQRhOCadd_CS#VBGXfSXgJzv "Dose 3"
* item[+].linkId = "X8zyunlgUfM"
* item[=].answer[+].valueCoding = D2OS_x31y45jvIQL_CS#odMfnhhpjUj "Mixed"
