// Generated by d2w fhir generate - do not edit

Instance: QuestionnaireResponse-IpHINAT79UW-example-1
InstanceOf: D2TrackerRegistrationResponse
Title: "Example response - Child Programme"
Description: "Example QuestionnaireResponse against the DHIS2 tracker program registration Child Programme (IpHINAT79UW)."
Usage: #example
* id = "IpHINAT79UW-example-1"
* extension[D2FormType].valueCode = #tracker
* extension[D2TrackerEnrollment].valueIdentifier.system = $DHIS2-TRACKER-ENROLLMENT
* extension[D2TrackerEnrollment].valueIdentifier.value = "jvImhO30zrp"
* extension[D2OrganisationUnit].valueReference = Reference(Location/qhqAxPSTUXp)
* extension[D2EnrolledAt].valueDateTime = "2026-08-05T08:00:00Z"
* extension[D2IncidentAt].valueDateTime = "2026-08-01T09:00:00Z"
* questionnaire = "http://example.org/fhir/examples/patient-summary/Questionnaire/IpHINAT79UW"
* status = #completed
* subject.type = "Patient"
* subject.identifier.system = $DHIS2-TE
* subject.identifier.value = "ByaTNM2MoVs"
* authored = "2026-07-29T22:00:00Z"
* item[+].linkId = "w75KJ2mc4zz"
* item[=].answer[+].valueString = "Example First name"
* item[+].linkId = "zDhUuAYrxNC"
* item[=].answer[+].valueString = "Example Last name"
* item[+].linkId = "cejWyOfXge6"
* item[=].answer[+].valueCoding = D2OS_pC3N9N77UmT_CS#Mnp3oXrpAbK "Female"
* item[+].linkId = "lZGmxYbs97q"
* item[=].answer[+].valueString = "Unique ID ByaTNM2MoVs"
