// Generated by d2w fhir generate - do not edit

Instance: QuestionnaireResponse-ZzYYXq4fJie-example-1
InstanceOf: D2TrackerEventResponse
Title: "Example response - Child Programme - Baby Postnatal"
Description: "Example QuestionnaireResponse against the DHIS2 tracker program stage Child Programme - Baby Postnatal (ZzYYXq4fJie)."
Usage: #example
* id = "ZzYYXq4fJie-example-1"
* extension[D2FormType].valueCode = #tracker-event
* extension[D2TrackerEnrollment].valueIdentifier.system = $DHIS2-TRACKER-ENROLLMENT
* extension[D2TrackerEnrollment].valueIdentifier.value = "gxMz7Qje7pk"
* extension[D2OrganisationUnit].valueReference = Reference(Location/ImspTQPwCqd)
* questionnaire = "http://example.org/fhir/examples/patient-summary/Questionnaire/ZzYYXq4fJie"
* status = #completed
* subject.type = "Patient"
* subject.identifier.system = $DHIS2-TE
* subject.identifier.value = "tPpcmcRWO0g"
* authored = "2026-07-29T15:00:00Z"
* item[+].linkId = "GQY2lXrypjO"
* item[=].answer[+].valueDecimal = 5.1
* item[+].linkId = "X8zyunlgUfM"
* item[=].answer[+].valueCoding = D2OS_x31y45jvIQL_CS#odMfnhhpjUj "Mixed"
* item[+].linkId = "FqlgKAG8HOu"
* item[=].answer[+].valueBoolean = false
* item[+].linkId = "vTUhAUZFoys"
* item[=].answer[+].valueCoding = D2OS_kzgQRhOCadd_CS#lFFqylGiWLk "Dose 1"
* item[+].linkId = "rxBfISxXS2U"
* item[=].answer[+].valueBoolean = false
* item[+].linkId = "lNNb3truQoi"
* item[=].answer[+].valueCoding = D2OS_nH8Y04zS7UV_CS#KGtyXqAprCc "IPT 3"
* item[+].linkId = "pOe0ogW4OWd"
* item[=].answer[+].valueCoding = D2OS_udkr3ihaeD3_CS#RqLFM2C8RnE "Dose 2"
* item[+].linkId = "HLmTEmupdX0"
* item[=].answer[+].valueBoolean = true
* item[+].linkId = "cYGaxwK615G"
* item[=].answer[+].valueCoding = D2OS_oXR37f2wOb1_CS#JWyCKF6i9l1 "Positive (Confirmed)"
* item[+].linkId = "hDZbpskhqDd"
* item[=].answer[+].valueCoding = D2OS_OGmE3wUMEzu_CS#vOSo0R6LuI1 "PCR"
* item[+].linkId = "sj3j9Hwc7so"
* item[=].answer[+].valueCoding = D2OS_dgsftM0rXu2_CS#bopJ9PaLnAZ "ABC/ddl/LPV/r -2"
* item[+].linkId = "aei1xRjSU2l"
* item[=].answer[+].valueCoding = D2OS_XdI8KRJiRoZ_CS#kzKxayEMqZB "No"
* item[+].linkId = "BeynU4L6VCQ"
* item[=].answer[+].valueCoding = D2OS_XdI8KRJiRoZ_CS#AAgDQGRuOHB "Yes"
* item[+].linkId = "OuJ6sgPyAbC"
* item[=].answer[+].valueString = "Example MCH Visit Comment"
