"""FHIR facade over a generated IG project: serves its resources and receives QuestionnaireResponse captures.

Each module owns its schemas; this module is the one stable import surface over them, so
`from dhis2w_fhir_serve import ResourceStore` keeps working however the internals are arranged.

What is deliberately NOT here is the capture UI. `dhis2w_fhir_serve.ui` and the `/uiconfig` document
exist so the built React bundle can work, they are reached by running the server with
`settings.ui`, and `create_app` is the only thing that mounts them. `UiBundleMissingError` is the
one exception: `create_app` raises it while building, so a caller of `create_app` has to be able to
catch it by name.
"""

from dhis2w_fhir_serve.app import create_app
from dhis2w_fhir_serve.auth import (
    AUTHENTICATION_REALM,
    BROWSER_SAFE_BASIC_SCHEME,
    CREDENTIAL_CACHE_SECONDS,
    DHIS2_IDENTITY_PATH,
    SERVE_TOKENS_VARIABLE,
    AuthState,
    CredentialCache,
    RequestIdentity,
    ServeAuthConfigurationError,
    UnauthenticatedError,
    ValidatedCredential,
    challenge_for,
    matches_a_serve_token,
    open_jwt_verifier,
    preflight_auth,
    read_serve_tokens,
    request_identity,
    require_authenticated,
    validate_with_dhis2,
)
from dhis2w_fhir_serve.capability import JWT_ISSUER_EXTENSION_URL, build_security, build_server_capability
from dhis2w_fhir_serve.capture import (
    DEFAULT_STRICT_CODES,
    GENERATE_SEED_IDENTIFIER_SEGMENT,
    AmbiguousCodingError,
    CaptureIndex,
    CaptureIndexCache,
    CaptureIssue,
    CaptureLifecyclePostures,
    CaptureNaming,
    CaptureQuestion,
    CaptureRejection,
    CodingResolver,
    CodingResolverSet,
    ResolvedCoding,
    UnreadableQuestionnaireError,
    UnresolvableCodingError,
    ValidatedCapture,
    build_capture_index,
    rejection_outcome,
    success_outcome,
    validate_response,
)
from dhis2w_fhir_serve.errors import (
    FHIR_JSON_MEDIA_TYPE,
    BadOperationError,
    BadSearchError,
    CaptureDisabledError,
    MethodNotAllowedError,
    NoPublishedSubjectTypeError,
    NotFoundError,
    NotServedError,
    NotServedFromCompiledIgError,
    ProjectionEmptyError,
    ProjectionNotConfiguredError,
    RecordDisabledError,
    RegisterDisabledError,
    RegisterListingDisabledError,
    ServeError,
    UpstreamError,
    outcome,
    register_error_handlers,
)
from dhis2w_fhir_serve.evaluation import (
    FHIRPATH_RESULT_NAME,
    DiagnosticKind,
    EvaluationDiagnostic,
    EvaluationLanguage,
    EvaluationOutcome,
    EvaluationResult,
    evaluate_source,
    json_safe,
    syntax_diagnostic,
)
from dhis2w_fhir_serve.history.projection import ProjectedEvent, ProjectedRecord, RecordProjection
from dhis2w_fhir_serve.history.wire import (
    TRACKED_ENTITY_RECORD_FIELDS,
    RecordedEvent,
    RecordedValue,
    TrackedEntityRecord,
    fetch_tracked_entity_record,
)
from dhis2w_fhir_serve.live import build_live_store, open_live_client
from dhis2w_fhir_serve.log import RequestLogMiddleware, configure_logging
from dhis2w_fhir_serve.metadata import build_metadata_body
from dhis2w_fhir_serve.oidc import (
    CLOCK_LEEWAY_SECONDS,
    JWKS_MINIMUM_CACHE_SECONDS,
    JWT_ALGORITHMS,
    JwtVerifier,
    OidcIssuerUnavailableError,
    PublishedKeys,
    TokenRefusedError,
    VerifiedToken,
    cache_seconds,
    discover_issuer,
    fetch_issuer_discovery,
    fetch_published_keys,
)
from dhis2w_fhir_serve.passthrough import (
    FACADE_PROVENANCE_HEADER,
    CallerCredentialReader,
    PassThroughUnavailableError,
    RegisterNotForwardableError,
    RegisterReader,
    UpstreamRefusalError,
    caller_reader,
    open_pass_through_client,
    register_reader,
)
from dhis2w_fhir_serve.projection.base import (
    IndexedName,
    NameMatch,
    NameMatches,
    NameQuery,
    NameSearchIndex,
    ProjectedResource,
    ProjectedResourceKey,
    ProjectionBatch,
    ProjectionCursor,
    ProjectionEndpoint,
    ProjectionPage,
    ProjectionQuery,
    ProjectionStore,
    ProjectionWatermarks,
)
from dhis2w_fhir_serve.projection.dhis2_names import Dhis2NameSearchIndex
from dhis2w_fhir_serve.projection.factory import build_name_search_index, build_projection_store, projection_path
from dhis2w_fhir_serve.projection.schema import (
    ProjectedIdentifierRow,
    ProjectedNameRow,
    ProjectedResourceRow,
    ProjectionBase,
    ProjectionWatermarkRow,
)
from dhis2w_fhir_serve.projection.serving import PROJECTION_AS_OF_HEADER, as_of, as_of_entry, as_of_headers
from dhis2w_fhir_serve.projection.sqlite_names import SqliteNameSearchIndex
from dhis2w_fhir_serve.projection.sqlite_store import SqliteProjectionStore
from dhis2w_fhir_serve.projection.sync import (
    SYNC_STEPS,
    SyncCursorMove,
    SyncMode,
    SyncNarrator,
    SyncReport,
    SyncResourceCounts,
    run_sync,
)
from dhis2w_fhir_serve.register.index import (
    NominatedAttributeError,
    PublishedAttribute,
    PublishedTrackedEntityType,
    TrackedEntityIndex,
)
from dhis2w_fhir_serve.register.listing import (
    COUNT_PARAMETER,
    PAGE_PARAMETER,
    ListingCursor,
    RegisterListingPage,
    read_listing_page,
)
from dhis2w_fhir_serve.register.projection import PERSON_RESOURCE_TYPES, registered_entity_for
from dhis2w_fhir_serve.register.surface import RegisterSurface, ServedRegister
from dhis2w_fhir_serve.register.wire import (
    INCLUDE_DELETED_PARAMETER,
    POLL_ORDER,
    POLL_PAGE_SIZE,
    SEARCH_ORG_UNIT_MODE,
    TOTAL_PAGES_PARAMETER,
    TRACKED_ENTITY_FIELDS,
    UPDATED_AFTER_PARAMETER,
    TouchedPage,
    TouchedRow,
    count_tracked_entity_pages,
    fetch_tracked_entity,
    list_tracked_entities,
    poll_enrollments,
    poll_tracked_entities,
    search_tracked_entities,
)
from dhis2w_fhir_serve.routes import ServeRouters, accept_head_wherever_get_is_served, register_routes, serve_routers
from dhis2w_fhir_serve.routes.cds import (
    CDS_SERVICE_PATH,
    CDS_SERVICES_PATH,
    CQL_LIBRARY_SERVICE_HOOK,
    CQL_LIBRARY_SERVICE_ID,
    CdsCard,
    CdsCardSource,
    CdsDiscovery,
    CdsHookRequest,
    CdsHookResponse,
    CdsService,
    CqlLibraryHookContext,
)
from dhis2w_fhir_serve.routes.context import caller_client, live_client, projection_store, serve_context
from dhis2w_fhir_serve.routes.enrollments import (
    TRACKED_ENTITY_ENROLLMENTS_PATH,
    TrackedEntityEnrollment,
    TrackedEntityEnrollments,
)
from dhis2w_fhir_serve.routes.evaluate import (
    EVALUATE_PATH,
    EvaluationRequest,
    InlineResourceContext,
    RegisteredEntityContext,
    StoredResourceContext,
)
from dhis2w_fhir_serve.routes.history import (
    TRACKED_ENTITY_EVENT_PATH,
    TRACKED_ENTITY_EVENTS_PATH,
    RecordPage,
)
from dhis2w_fhir_serve.routes.negotiation import require_json_is_acceptable
from dhis2w_fhir_serve.routes.spool import (
    SPOOL_PATH,
    SpoolCounts,
    SpoolImport,
    SpoolListing,
    SpoolRejection,
    SpoolRejectionIssue,
    SpoolResponseSummary,
    SpoolWithdrawal,
)
from dhis2w_fhir_serve.routes.terminology import CODE_LOOKUP_PATH, VALIDATE_CODE_PATH
from dhis2w_fhir_serve.routes.translate import TranslateRequest, TranslationMatch, find_translations
from dhis2w_fhir_serve.routes.whoami import (
    TOKEN_CALLER_NAME,
    WHOAMI_PATH,
    AuthenticatedCaller,
    authenticated_caller,
)
from dhis2w_fhir_serve.runtime import (
    ServeContext,
    ServeRuntime,
    attach_serve_runtime,
    build_store,
    facade_provenance,
    open_projection_store,
    open_serve_runtime,
    server_version,
)
from dhis2w_fhir_serve.settings import ServeInvocation, ServeSettings
from dhis2w_fhir_serve.spool import (
    FORWARDED_RESPONSES_RELATIVE_PATH,
    IMPORT_REPORT_SUFFIX,
    RECEIVED_RESPONSES_RELATIVE_PATH,
    REJECTED_RESPONSES_RELATIVE_PATH,
    SPOOL_RELATIVE_PATH,
    WITHDRAWN_RESPONSES_RELATIVE_PATH,
    ResponseLifecycle,
    ResponseSpool,
    SpoolCursor,
    SpoolPage,
    StoredReceipt,
    StoredResponseEnvelope,
    UnreadableReceiptError,
    current_instant,
    new_response_id,
    page_of,
    requested_cursor,
    requested_page_size,
)
from dhis2w_fhir_serve.store import (
    COMPILED_RESOURCES_RELATIVE_PATH,
    CompiledIgMissingError,
    IdentifierToken,
    ResourceStore,
    SearchQuery,
    StoreEntry,
    StoreSummary,
    load_compiled_store,
)
from dhis2w_fhir_serve.summary import SummaryDoses, recorded_doses
from dhis2w_fhir_serve.synthesize import (
    DEFAULT_PERIOD_TYPE,
    GENERATED_STATUS,
    MAXIMUM_SEED,
    DateWindow,
    draw_seed,
    generate_response,
    resolve_period_type,
)
from dhis2w_fhir_serve.terminology import (
    ConceptProperty,
    LookedUpCode,
    LookupCodeSystem,
    LookupConcept,
    LookupConceptProperty,
    LookupValueSet,
    LookupValueSetCompose,
    LookupValueSetInclude,
    TerminologyState,
    ValidatedCode,
    load_terminology,
)
from dhis2w_fhir_serve.ui import UiBundleMissingError

__all__ = [
    "accept_head_wherever_get_is_served",
    "AmbiguousCodingError",
    "as_of",
    "as_of_entry",
    "as_of_headers",
    "attach_serve_runtime",
    "authenticated_caller",
    "AuthenticatedCaller",
    "AUTHENTICATION_REALM",
    "AuthState",
    "BadOperationError",
    "BadSearchError",
    "BROWSER_SAFE_BASIC_SCHEME",
    "build_capture_index",
    "build_live_store",
    "build_metadata_body",
    "build_name_search_index",
    "build_projection_store",
    "build_security",
    "build_server_capability",
    "build_store",
    "cache_seconds",
    "caller_client",
    "caller_reader",
    "CallerCredentialReader",
    "CaptureDisabledError",
    "CaptureIndex",
    "CaptureIndexCache",
    "CaptureIssue",
    "CaptureLifecyclePostures",
    "CaptureNaming",
    "CaptureQuestion",
    "CaptureRejection",
    "CDS_SERVICE_PATH",
    "CDS_SERVICES_PATH",
    "CdsCard",
    "CdsCardSource",
    "CdsDiscovery",
    "CdsHookRequest",
    "CdsHookResponse",
    "CdsService",
    "challenge_for",
    "CLOCK_LEEWAY_SECONDS",
    "CODE_LOOKUP_PATH",
    "CodingResolver",
    "CodingResolverSet",
    "COMPILED_RESOURCES_RELATIVE_PATH",
    "CompiledIgMissingError",
    "ConceptProperty",
    "configure_logging",
    "COUNT_PARAMETER",
    "count_tracked_entity_pages",
    "CQL_LIBRARY_SERVICE_HOOK",
    "CQL_LIBRARY_SERVICE_ID",
    "CqlLibraryHookContext",
    "create_app",
    "CREDENTIAL_CACHE_SECONDS",
    "CredentialCache",
    "current_instant",
    "DateWindow",
    "DEFAULT_PERIOD_TYPE",
    "DEFAULT_STRICT_CODES",
    "DHIS2_IDENTITY_PATH",
    "Dhis2NameSearchIndex",
    "DiagnosticKind",
    "discover_issuer",
    "draw_seed",
    "EVALUATE_PATH",
    "evaluate_source",
    "EvaluationDiagnostic",
    "EvaluationLanguage",
    "EvaluationOutcome",
    "EvaluationRequest",
    "EvaluationResult",
    "facade_provenance",
    "FACADE_PROVENANCE_HEADER",
    "fetch_issuer_discovery",
    "fetch_published_keys",
    "fetch_tracked_entity",
    "fetch_tracked_entity_record",
    "FHIR_JSON_MEDIA_TYPE",
    "FHIRPATH_RESULT_NAME",
    "find_translations",
    "FORWARDED_RESPONSES_RELATIVE_PATH",
    "generate_response",
    "GENERATE_SEED_IDENTIFIER_SEGMENT",
    "GENERATED_STATUS",
    "IdentifierToken",
    "IMPORT_REPORT_SUFFIX",
    "INCLUDE_DELETED_PARAMETER",
    "IndexedName",
    "InlineResourceContext",
    "json_safe",
    "JWKS_MINIMUM_CACHE_SECONDS",
    "JWT_ALGORITHMS",
    "JWT_ISSUER_EXTENSION_URL",
    "JwtVerifier",
    "list_tracked_entities",
    "ListingCursor",
    "live_client",
    "load_compiled_store",
    "load_terminology",
    "LookedUpCode",
    "LookupCodeSystem",
    "LookupConcept",
    "LookupConceptProperty",
    "LookupValueSet",
    "LookupValueSetCompose",
    "LookupValueSetInclude",
    "matches_a_serve_token",
    "MAXIMUM_SEED",
    "MethodNotAllowedError",
    "NameMatch",
    "NameMatches",
    "NameQuery",
    "NameSearchIndex",
    "new_response_id",
    "NominatedAttributeError",
    "NoPublishedSubjectTypeError",
    "NotFoundError",
    "NotServedError",
    "NotServedFromCompiledIgError",
    "OidcIssuerUnavailableError",
    "open_jwt_verifier",
    "open_live_client",
    "open_pass_through_client",
    "open_projection_store",
    "open_serve_runtime",
    "outcome",
    "page_of",
    "PAGE_PARAMETER",
    "PassThroughUnavailableError",
    "PERSON_RESOURCE_TYPES",
    "poll_enrollments",
    "POLL_ORDER",
    "POLL_PAGE_SIZE",
    "poll_tracked_entities",
    "preflight_auth",
    "ProjectedEvent",
    "ProjectedIdentifierRow",
    "ProjectedNameRow",
    "ProjectedRecord",
    "ProjectedResource",
    "ProjectedResourceKey",
    "ProjectedResourceRow",
    "PROJECTION_AS_OF_HEADER",
    "projection_path",
    "projection_store",
    "ProjectionBase",
    "ProjectionBatch",
    "ProjectionCursor",
    "ProjectionEmptyError",
    "ProjectionEndpoint",
    "ProjectionNotConfiguredError",
    "ProjectionPage",
    "ProjectionQuery",
    "ProjectionStore",
    "ProjectionWatermarkRow",
    "ProjectionWatermarks",
    "PublishedAttribute",
    "PublishedKeys",
    "PublishedTrackedEntityType",
    "read_listing_page",
    "read_serve_tokens",
    "RECEIVED_RESPONSES_RELATIVE_PATH",
    "RecordDisabledError",
    "recorded_doses",
    "RecordedEvent",
    "RecordedValue",
    "RecordPage",
    "RecordProjection",
    "register_error_handlers",
    "register_reader",
    "register_routes",
    "RegisterDisabledError",
    "registered_entity_for",
    "RegisteredEntityContext",
    "RegisterListingDisabledError",
    "RegisterListingPage",
    "RegisterNotForwardableError",
    "RegisterReader",
    "RegisterSurface",
    "REJECTED_RESPONSES_RELATIVE_PATH",
    "rejection_outcome",
    "request_identity",
    "requested_cursor",
    "requested_page_size",
    "RequestIdentity",
    "RequestLogMiddleware",
    "require_authenticated",
    "require_json_is_acceptable",
    "resolve_period_type",
    "ResolvedCoding",
    "ResourceStore",
    "ResponseLifecycle",
    "ResponseSpool",
    "run_sync",
    "SEARCH_ORG_UNIT_MODE",
    "search_tracked_entities",
    "SearchQuery",
    "serve_context",
    "serve_routers",
    "SERVE_TOKENS_VARIABLE",
    "ServeAuthConfigurationError",
    "ServeContext",
    "ServedRegister",
    "ServeError",
    "ServeInvocation",
    "server_version",
    "ServeRouters",
    "ServeRuntime",
    "ServeSettings",
    "SPOOL_PATH",
    "SPOOL_RELATIVE_PATH",
    "SpoolCounts",
    "SpoolCursor",
    "SpoolImport",
    "SpoolListing",
    "SpoolPage",
    "SpoolRejection",
    "SpoolRejectionIssue",
    "SpoolResponseSummary",
    "SpoolWithdrawal",
    "SqliteNameSearchIndex",
    "SqliteProjectionStore",
    "StoredReceipt",
    "StoredResourceContext",
    "StoredResponseEnvelope",
    "StoreEntry",
    "StoreSummary",
    "success_outcome",
    "SummaryDoses",
    "SYNC_STEPS",
    "SyncCursorMove",
    "SyncMode",
    "SyncNarrator",
    "SyncReport",
    "SyncResourceCounts",
    "syntax_diagnostic",
    "TerminologyState",
    "TOKEN_CALLER_NAME",
    "TokenRefusedError",
    "TOTAL_PAGES_PARAMETER",
    "TouchedPage",
    "TouchedRow",
    "TRACKED_ENTITY_ENROLLMENTS_PATH",
    "TRACKED_ENTITY_EVENT_PATH",
    "TRACKED_ENTITY_EVENTS_PATH",
    "TRACKED_ENTITY_FIELDS",
    "TRACKED_ENTITY_RECORD_FIELDS",
    "TrackedEntityEnrollment",
    "TrackedEntityEnrollments",
    "TrackedEntityIndex",
    "TrackedEntityRecord",
    "TranslateRequest",
    "TranslationMatch",
    "UiBundleMissingError",
    "UnauthenticatedError",
    "UnreadableQuestionnaireError",
    "UnreadableReceiptError",
    "UnresolvableCodingError",
    "UPDATED_AFTER_PARAMETER",
    "UpstreamError",
    "UpstreamRefusalError",
    "VALIDATE_CODE_PATH",
    "validate_response",
    "validate_with_dhis2",
    "ValidatedCapture",
    "ValidatedCode",
    "ValidatedCredential",
    "VerifiedToken",
    "WHOAMI_PATH",
    "WITHDRAWN_RESPONSES_RELATIVE_PATH",
]
