"""FHIR facade over a generated IG project: serves its resources and receives QuestionnaireResponse captures.

Each module owns its schemas; this module is the one stable import surface over them, so
`from dhis2w_fhir_serve import ResourceStore` keeps working however the internals are arranged.
"""

from dhis2w_fhir_serve.app import ServeContext, build_store, create_app, server_version
from dhis2w_fhir_serve.capability import build_server_capability
from dhis2w_fhir_serve.capture import (
    DEFAULT_STRICT_CODES,
    GENERATE_SEED_IDENTIFIER_SEGMENT,
    AmbiguousCodingError,
    CaptureIndex,
    CaptureIndexCache,
    CaptureIssue,
    CaptureNaming,
    CaptureQuestion,
    CaptureRejection,
    CodingResolver,
    CodingResolverSet,
    ResolvedCoding,
    UnreadableQuestionnaireError,
    UnresolvableCodingError,
    ValidatedCapture,
    build_capture_index,
    rejection_outcome,
    success_outcome,
    validate_response,
)
from dhis2w_fhir_serve.errors import (
    FHIR_JSON_MEDIA_TYPE,
    BadOperationError,
    BadSearchError,
    MethodNotAllowedError,
    NotFoundError,
    NotServedError,
    ServeError,
    outcome,
    register_error_handlers,
)
from dhis2w_fhir_serve.log import RequestLogMiddleware, configure_logging
from dhis2w_fhir_serve.metadata import build_metadata_body
from dhis2w_fhir_serve.routes.spool import (
    SPOOL_PATH,
    SpoolCounts,
    SpoolListing,
    SpoolRejection,
    SpoolRejectionIssue,
    SpoolResponseSummary,
)
from dhis2w_fhir_serve.settings import ServeSettings
from dhis2w_fhir_serve.spool import (
    FORWARDED_RESPONSES_RELATIVE_PATH,
    RECEIVED_RESPONSES_RELATIVE_PATH,
    REJECTED_RESPONSES_RELATIVE_PATH,
    REJECTION_REPORT_SUFFIX,
    SPOOL_RELATIVE_PATH,
    ResponseLifecycle,
    ResponseSpool,
    StoredReceipt,
    StoredResponseEnvelope,
    UnreadableReceiptError,
    current_instant,
    new_response_id,
)
from dhis2w_fhir_serve.store import (
    COMPILED_RESOURCES_RELATIVE_PATH,
    CompiledIgMissingError,
    IdentifierToken,
    ResourceStore,
    SearchQuery,
    StoreEntry,
    StoreSummary,
    load_compiled_store,
)
from dhis2w_fhir_serve.synthesize import (
    DEFAULT_PERIOD_TYPE,
    GENERATED_STATUS,
    MAXIMUM_SEED,
    DateWindow,
    draw_seed,
    generate_response,
    resolve_period_type,
)
from dhis2w_fhir_serve.ui import (
    STATIC_DIRECTORY,
    UiBundleMissingError,
    UiStaticFiles,
    mount_ui_assets,
    mount_ui_shell,
    ui_bundle_present,
)

__all__ = [
    "COMPILED_RESOURCES_RELATIVE_PATH",
    "DEFAULT_PERIOD_TYPE",
    "DEFAULT_STRICT_CODES",
    "FHIR_JSON_MEDIA_TYPE",
    "FORWARDED_RESPONSES_RELATIVE_PATH",
    "GENERATED_STATUS",
    "GENERATE_SEED_IDENTIFIER_SEGMENT",
    "MAXIMUM_SEED",
    "RECEIVED_RESPONSES_RELATIVE_PATH",
    "REJECTED_RESPONSES_RELATIVE_PATH",
    "REJECTION_REPORT_SUFFIX",
    "SPOOL_PATH",
    "SPOOL_RELATIVE_PATH",
    "STATIC_DIRECTORY",
    "AmbiguousCodingError",
    "BadOperationError",
    "BadSearchError",
    "CaptureIndex",
    "CaptureIndexCache",
    "CaptureIssue",
    "CaptureNaming",
    "CaptureQuestion",
    "CaptureRejection",
    "CodingResolver",
    "CodingResolverSet",
    "CompiledIgMissingError",
    "DateWindow",
    "IdentifierToken",
    "MethodNotAllowedError",
    "NotFoundError",
    "NotServedError",
    "RequestLogMiddleware",
    "ResolvedCoding",
    "ResourceStore",
    "ResponseLifecycle",
    "ResponseSpool",
    "SearchQuery",
    "ServeContext",
    "ServeError",
    "ServeSettings",
    "SpoolCounts",
    "SpoolListing",
    "SpoolRejection",
    "SpoolRejectionIssue",
    "SpoolResponseSummary",
    "StoreEntry",
    "StoreSummary",
    "StoredReceipt",
    "StoredResponseEnvelope",
    "UiBundleMissingError",
    "UiStaticFiles",
    "UnreadableQuestionnaireError",
    "UnreadableReceiptError",
    "UnresolvableCodingError",
    "ValidatedCapture",
    "build_capture_index",
    "build_metadata_body",
    "build_server_capability",
    "build_store",
    "configure_logging",
    "create_app",
    "current_instant",
    "draw_seed",
    "generate_response",
    "load_compiled_store",
    "mount_ui_assets",
    "mount_ui_shell",
    "new_response_id",
    "outcome",
    "register_error_handlers",
    "rejection_outcome",
    "resolve_period_type",
    "server_version",
    "success_outcome",
    "ui_bundle_present",
    "validate_response",
]
