"""Version-invariant security domain logic shared by every security plugin tree.

The authority taxonomy, severity model, guardrail contract, audit orchestration,
and report rendering are security opinions, not version concerns: they live once
here and are consumed by the thin per-tree plugin shims under
`dhis2w_core.v{41,42,43}.plugins.security`. Only genuinely version-divergent wire
extraction lives per tree.
"""

from __future__ import annotations

from dhis2w_core.security_core.apps import HubApp, InstalledApp, evaluate_apps
from dhis2w_core.security_core.audit_config import evaluate_audit_config
from dhis2w_core.security_core.auth_methods import LoginProviderView, OAuth2ClientView, evaluate_auth_methods
from dhis2w_core.security_core.authorities import (
    AUTHORITY_CATEGORIES,
    AuthorityCategory,
    build_account_authorities,
    categorise_authorities,
    evaluate_account_authorities,
)
from dhis2w_core.security_core.controls import (
    CONTROL_CATALOG,
    CheckOutcome,
    ControlLog,
    ControlOutcome,
    ControlSpec,
    ControlStatus,
)
from dhis2w_core.security_core.credentials import (
    CredentialProbeResult,
    ProbeOutcome,
    classify_probe_status,
    evaluate_credential_probe,
)
from dhis2w_core.security_core.csp import CspDirectives, grade_csp, parse_csp
from dhis2w_core.security_core.dhisconf import (
    AuditPosture,
    AuditScopeMatrix,
    RedactedSecret,
    parse_dhis_conf,
)
from dhis2w_core.security_core.findings import (
    HIGH_RISK_ROLE_CATEGORIES,
    SEVERITY_ORDER,
    AuditFinding,
    Severity,
    finding_sort_key,
    role_severity,
    severity_rank,
)
from dhis2w_core.security_core.guardrails import (
    CONNECT_PATHS,
    CREDENTIAL_PROBE_PATHS,
    DEFAULT_PROBE_PASSWORD,
    DEFAULT_PROBE_USERNAME,
    GET_ALLOWLIST,
    MAX_PROBE_ATTEMPTS,
    REPORT_GUARDRAIL_NOTE,
    GuardrailViolation,
    guardrail_request_hook,
    probe_client,
)
from dhis2w_core.security_core.guest import (
    ANONYMOUS_PROBE_TARGETS,
    AnonymousResult,
    GuestProbeTarget,
    evaluate_guest,
)
from dhis2w_core.security_core.hygiene import (
    SEED_USERNAME,
    TwoFactorSource,
    TwoFactorSummary,
    UserHygiene,
    build_user_hygiene,
    evaluate_hygiene,
    evaluate_two_factor_from_endpoint,
    evaluate_two_factor_from_user_field,
)
from dhis2w_core.security_core.models import AccountAuthorities, CategoryMatch
from dhis2w_core.security_core.options import AuditOptions
from dhis2w_core.security_core.orchestrator import run_audit
from dhis2w_core.security_core.registry import (
    CANONICAL_CHECKS,
    BoundCheck,
    CheckSpec,
    canonical_keys,
    label_for,
    resolve_check_keys,
    select_keys,
)
from dhis2w_core.security_core.releases import RELEASES_FEED_URL, ReleaseFeed, ReleaseLine, fetch_release_feed
from dhis2w_core.security_core.report.base import ProgressReporter, ReportRenderer, StreamingRenderer
from dhis2w_core.security_core.report.csv import CsvRenderer
from dhis2w_core.security_core.report.html import HtmlRenderer
from dhis2w_core.security_core.report.markdown import MarkdownRenderer
from dhis2w_core.security_core.report.model import (
    AuditReport,
    AuditSummary,
    CheckResult,
    CheckStatus,
    RunManifest,
)
from dhis2w_core.security_core.report.progress import PlainLogReporter, RichProgressReporter, make_reporter
from dhis2w_core.security_core.report.text import TextRenderer
from dhis2w_core.security_core.report.view import (
    ControlView,
    GroupView,
    ItemView,
    ReportMeta,
    ReportView,
    Scorecard,
    SectionView,
    build_report_view,
)
from dhis2w_core.security_core.roles import RoleAudit, build_role_audit, evaluate_roles
from dhis2w_core.security_core.routes import RouteTarget, evaluate_routes
from dhis2w_core.security_core.settings_audit import (
    MIN_RECOMMENDED_PASSWORD_LENGTH,
    CorsWhitelist,
    SettingsLike,
    evaluate_settings,
)
from dhis2w_core.security_core.sharing import (
    SHARING_CAVEATS,
    SHARING_FOCUS_TYPES,
    SHARING_SCHEMA_VERSION,
    AccessBits,
    EffectiveAccess,
    EffectiveGrant,
    ExplorerRenderer,
    FetchedGroup,
    FetchedObject,
    FetchedRole,
    FetchedShare,
    FetchedUser,
    ManageEdge,
    MembershipEdge,
    ObjectNode,
    PrincipalKind,
    ProvenanceKind,
    ResolvedFocusType,
    RoleGrantEdge,
    RoleNode,
    SchemaShareability,
    ShareEdge,
    SharingExplorerMeta,
    SharingFocusType,
    SharingGraph,
    SharingView,
    TypeInventory,
    TypeSummary,
    UserGroupNode,
    UserNode,
    build_sharing_graph,
    build_sharing_view,
    compute_effective_access,
    evaluate_sharing,
    resolve_focus_types,
)
from dhis2w_core.security_core.streaming import ReportWriter
from dhis2w_core.security_core.tokens import TokenAllowlists, TokensInventory, TokenView, evaluate_tokens
from dhis2w_core.security_core.transport import CORS_PROBE_ORIGIN, TransportHeaders, evaluate_transport
from dhis2w_core.security_core.versions import (
    ADVISORY_PATCH_FLOOR,
    ADVISORY_PATCH_FLOOR_REVIEWED,
    MIN_SUPPORTED_LINE,
    AdvisoryFloor,
    ParsedVersion,
    VersionPosture,
    build_version_posture,
    evaluate_version,
    parse_dhis2_version,
)

__all__ = [
    "ADVISORY_PATCH_FLOOR",
    "ADVISORY_PATCH_FLOOR_REVIEWED",
    "ANONYMOUS_PROBE_TARGETS",
    "AUTHORITY_CATEGORIES",
    "CANONICAL_CHECKS",
    "CONTROL_CATALOG",
    "CONNECT_PATHS",
    "CORS_PROBE_ORIGIN",
    "CREDENTIAL_PROBE_PATHS",
    "DEFAULT_PROBE_PASSWORD",
    "DEFAULT_PROBE_USERNAME",
    "GET_ALLOWLIST",
    "HIGH_RISK_ROLE_CATEGORIES",
    "MAX_PROBE_ATTEMPTS",
    "MIN_RECOMMENDED_PASSWORD_LENGTH",
    "MIN_SUPPORTED_LINE",
    "RELEASES_FEED_URL",
    "REPORT_GUARDRAIL_NOTE",
    "SEED_USERNAME",
    "SEVERITY_ORDER",
    "SHARING_CAVEATS",
    "SHARING_FOCUS_TYPES",
    "SHARING_SCHEMA_VERSION",
    "AccessBits",
    "AccountAuthorities",
    "AdvisoryFloor",
    "AnonymousResult",
    "AuditFinding",
    "AuditOptions",
    "AuditPosture",
    "AuditReport",
    "AuditScopeMatrix",
    "AuditSummary",
    "AuthorityCategory",
    "BoundCheck",
    "CategoryMatch",
    "CheckOutcome",
    "CheckResult",
    "CheckSpec",
    "CheckStatus",
    "ControlLog",
    "ControlOutcome",
    "ControlSpec",
    "ControlStatus",
    "ControlView",
    "CorsWhitelist",
    "CredentialProbeResult",
    "CspDirectives",
    "CsvRenderer",
    "EffectiveAccess",
    "EffectiveGrant",
    "ExplorerRenderer",
    "FetchedGroup",
    "FetchedObject",
    "FetchedRole",
    "FetchedShare",
    "FetchedUser",
    "GroupView",
    "GuardrailViolation",
    "GuestProbeTarget",
    "HtmlRenderer",
    "HubApp",
    "InstalledApp",
    "ItemView",
    "LoginProviderView",
    "ManageEdge",
    "MarkdownRenderer",
    "MembershipEdge",
    "OAuth2ClientView",
    "ObjectNode",
    "ParsedVersion",
    "PlainLogReporter",
    "PrincipalKind",
    "ProbeOutcome",
    "ProgressReporter",
    "ProvenanceKind",
    "RedactedSecret",
    "ReleaseFeed",
    "ReleaseLine",
    "ReportMeta",
    "ReportRenderer",
    "ReportView",
    "ReportWriter",
    "ResolvedFocusType",
    "RichProgressReporter",
    "RoleAudit",
    "RoleGrantEdge",
    "RoleNode",
    "RouteTarget",
    "RunManifest",
    "SchemaShareability",
    "Scorecard",
    "SectionView",
    "SettingsLike",
    "Severity",
    "ShareEdge",
    "SharingExplorerMeta",
    "SharingFocusType",
    "SharingGraph",
    "SharingView",
    "StreamingRenderer",
    "TextRenderer",
    "TokenAllowlists",
    "TokenView",
    "TokensInventory",
    "TransportHeaders",
    "TwoFactorSource",
    "TwoFactorSummary",
    "TypeInventory",
    "TypeSummary",
    "UserGroupNode",
    "UserHygiene",
    "UserNode",
    "VersionPosture",
    "build_account_authorities",
    "build_report_view",
    "build_role_audit",
    "build_sharing_graph",
    "build_sharing_view",
    "build_user_hygiene",
    "build_version_posture",
    "canonical_keys",
    "categorise_authorities",
    "classify_probe_status",
    "compute_effective_access",
    "evaluate_account_authorities",
    "evaluate_apps",
    "evaluate_audit_config",
    "evaluate_auth_methods",
    "evaluate_credential_probe",
    "evaluate_guest",
    "evaluate_hygiene",
    "evaluate_roles",
    "evaluate_routes",
    "evaluate_settings",
    "evaluate_sharing",
    "evaluate_tokens",
    "evaluate_transport",
    "evaluate_two_factor_from_endpoint",
    "evaluate_two_factor_from_user_field",
    "evaluate_version",
    "fetch_release_feed",
    "finding_sort_key",
    "grade_csp",
    "guardrail_request_hook",
    "label_for",
    "make_reporter",
    "parse_csp",
    "parse_dhis2_version",
    "parse_dhis_conf",
    "probe_client",
    "resolve_check_keys",
    "resolve_focus_types",
    "role_severity",
    "run_audit",
    "select_keys",
    "severity_rank",
]
